### ISSUE TITLE
Can /etc/machine-id be used for default InitiatorName?

### ISSUE THREAD

**Issue by xnox** [open-iscsi/open-iscsi#10]
If InitiatorName has not been provided, can /etc/machine-id be used with a default prefix to assemble a stable InitiatorName?

**Comment by mikechristie** [comment]
On 05/11/2015 07:03 AM, Dimitri John Ledkov wrote:
> If InitiatorName has not been provided, can /etc/machine-id be used with
> a default prefix to assemble a stable InitiatorName?
> 

Most require the name in the format defined by the iSCSI RFC:

https://www.ietf.org/rfc/rfc3720.txt

so they normally want you to have the form:


                   Naming     String defined by
      Type  Date    Auth      "example.com" naming authority
     +--++-----+ +---------+ +--------------------------------+
     |  ||     | |         | |                                |

     iqn.2001-04.com.example:storage:diskarrays-sn-a8675309


They normally just care about the format. Most targets do not care if
the naming auth is valid and do not care bout the part after the ":", so
for the last part you can use the machine id if it is unique (if you
have multiple initiators with the same name you will get bouncing logins).

**Comment by gonzoleeman** [comment]
@xnox, are you still interested in this? If so, you could propose a helper command that generates the initiator name based on the machine ID, in the proper/legal format. Such a script could then be incorporated into the installation code and could be used to either generate the initiator name the first time (which is something we have to do now anyway) or to regenerate the name, if needed.

**Comment by gonzoleeman** [comment]
No response for over a year, so closing this issue.

**Comment by xnox** [comment]
I cannot remember what we ended up doing there. But my understanding was that automagically using machine-id would still be desirable.
