### ISSUE TITLE
command "iscsiadm --mode session -P 3" segfaults

### ISSUE THREAD

**Issue by AffableZonkey** [open-iscsi/open-iscsi#102]
Hi, running Fedora 28 as client, connecting to a Centos 7 target. iscsiadm version 6.2.0.874 generates segfault on the command above, whether the integer is 1, 2, or 3. I can't tell if this is the issue mentioned in your release notes? 
Kernel is 4.16.6-302

When adding --debug 4 I get this output;

iscsiadm --mode session --print 3 -d 4
iscsiadm: Max file limits 1024 4096
iscsiadm: sysfs_attr_get_value: open '/module/scsi_transport_iscsi'/'version'
iSCSI Transport Class version 2.0-870
version 6.2.0.874
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session1'/'targetname'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session1'/'username'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session1'/'password'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session1'/'username_in'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session1'/'password_in'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session1'/'recovery_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session1'/'lu_reset_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session1'/'tgt_reset_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session1'/'abort_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session1'/'tpgt'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection1:0'/'persistent_address'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection1:0'/'address'
iscsiadm: Could not read attr address on path /class/iscsi_connection/connection1:0
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection1:0'/'persistent_port'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection1:0'/'port'
iscsiadm: Could not read attr port on path /class/iscsi_connection/connection1:0
iscsiadm: sysfs_device_get: open '/class/iscsi_session/session1'
iscsiadm: sysfs_resolve_link: path link '/class/iscsi_session/session1' points to '../../devices/platform/host6/session1/iscsi_session/session1'
iscsiadm: sysfs_resolve_link: base '/class/iscsi_session/session1', tail 'devices/platform/host6/session1/iscsi_session/session1', back 2
iscsiadm: sysfs_resolve_link: after moving back ''

- there is more output, but not sure if it is helpful...

**Comment by gonzoleeman** [comment]
This is a known issue, fixed in 2.0.875. See commit c8e6198dca7118a9
