### ISSUE TITLE
iscsiadm login twice and duplicated LUN occur

### ISSUE THREAD

**Issue by zhuozh** [open-iscsi/open-iscsi#108]
Hi, Recently we found if we login simultaneously, iscsi target will be connected twice.
I am just wondering wether it can be considered as a bug？

open-iscsi version:
centos7.4
device-mapper-multipath-0.4.9-111.el7_4.2.x86_64

[root@sds-10-20 ~]# cat test.sh 
iscsiadm -m node --loginall=automatic &
iscsiadm -m node --loginall=automatic &
[root@sds-10-20 ~]# 
[root@sds-10-20 ~]# iscsiadm -m discovery -t st -p 10.128.3.94 3260 
10.128.3.94:3260,1 iqn.2003-01.com.redhat.iscsi-gw0
10.128.2.104:3260,2 iqn.2003-01.com.redhat.iscsi-gw0
10.128.3.94:3260,1 iqn.2003-01.com.redhat.iscsi-gw1
10.128.2.104:3260,2 iqn.2003-01.com.redhat.iscsi-gw1
[root@sds-10-20 ~]# 
[root@sds-10-20 ~]# sh iscsiadm.sh 
[root@sds-10-20 ~]# Logging in to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw1, portal: 10.128.3.94,3260] (multiple)
Logging in to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw1, portal: 10.128.2.104,3260] (multiple)
Logging in to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw0, portal: 10.128.3.94,3260] (multiple)
Logging in to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw0, portal: 10.128.2.104,3260] (multiple)
iscsiadm: could not read session targetname: 5
iscsiadm: could not find session info for session170
Logging in to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw0, portal: 10.128.3.94,3260] (multiple)
Logging in to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw0, portal: 10.128.2.104,3260] (multiple)
Login to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw1, portal: 10.128.3.94,3260] successful.
Login to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw1, portal: 10.128.2.104,3260] successful.
Login to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw0, portal: 10.128.3.94,3260] successful.
Login to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw0, portal: 10.128.2.104,3260] successful.
Login to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw0, portal: 10.128.3.94,3260] successful.
Login to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw0, portal: 10.128.2.104,3260] successful.
[root@sds-10-20 ~]#   
[root@sds-10-20 ~]# iscsiadm -m node
10.128.3.94:3260,1 iqn.2003-01.com.redhat.iscsi-gw1
10.128.2.104:3260,2 iqn.2003-01.com.redhat.iscsi-gw1
10.128.3.94:3260,1 iqn.2003-01.com.redhat.iscsi-gw0
10.128.2.104:3260,2 iqn.2003-01.com.redhat.iscsi-gw0
[root@sds-10-20 ~]# 
[root@sds-10-20 ~]# 
[root@sds-10-20 ~]# iscsiadm -m session
tcp: [169] 10.128.3.94:3260,1 iqn.2003-01.com.redhat.iscsi-gw1 (non-flash)
tcp: [170] 10.128.2.104:3260,2 iqn.2003-01.com.redhat.iscsi-gw1 (non-flash)
tcp: [171] 10.128.3.94:3260,1 iqn.2003-01.com.redhat.iscsi-gw0 (non-flash)
tcp: [172] 10.128.2.104:3260,2 iqn.2003-01.com.redhat.iscsi-gw0 (non-flash)
tcp: [173] 10.128.3.94:3260,1 iqn.2003-01.com.redhat.iscsi-gw0 (non-flash)
tcp: [174] 10.128.2.104:3260,2 iqn.2003-01.com.redhat.iscsi-gw0 (non-flash)
[root@sds-10-20 ~]# 
[root@sds-10-20 ~]# multipath -ll
mpathb (360014059d34c74db4044d1a840043560) dm-1 LIO-ORG ,TCMU device     
size=10G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
|-+- policy='queue-length 0' prio=50 status=active
| - 180:0:0:0 sdh 8:112 active ready running
-+- policy='queue-length 0' prio=10 status=enabled
-- 179:0:0:0 sdf 8:80  active ready running
mpatha (36001405f8cd12e866a2475cabc7c0679) dm-0 LIO-ORG ,TCMU device     
size=100G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
|-+- policy='queue-length 0' prio=50 status=active
| - 182:0:0:0 sdi 8:128 active ready running
|-+- policy='queue-length 0' prio=50 status=enabled
| - 184:0:0:0 sdk 8:160 active ready running
|-+- policy='queue-length 0' prio=10 status=enabled
| - 181:0:0:0 sdg 8:96  active ready running
-+- policy='queue-length 0' prio=10 status=enabled
-- 183:0:0:0 sdj 8:144 active ready running

**Comment by gonzoleeman** [comment]
I am able to reproduce this as long as I have my initiator and target on separate systems.
What iscsid really needs is session locking, i.e. anything touching the session puts a lock on it, and other threads wait. But that would require massive changes IMHO. And part of the problem is that the effects of creating a session are not complete until the info from that session shows up in sysfs, and that is asynchronous. So it would be very difficult to keep the session locked until the sysfs entries showed up.
So in lieu of a complete fix, this patch seems to fix the issue for the normal case of allowing one session per node. Do you want to test it out?

```
diff --git a/usr/session_mgmt.c b/usr/session_mgmt.c
index 596085b1f640..e3c6044bb21e 100644
--- a/usr/session_mgmt.c
+++ b/usr/session_mgmt.c
@@ -189,9 +189,10 @@ int iscsi_login_portal(void *data, struct list_head *list, struct node_rec *rec)
 
        /*
         * Ensure the record's 'multiple' flag is set so __iscsi_login_portal
-        * will allow multiple logins.
+        * will allow multiple logins, but only if we support more than one.
         */
-       rec->session.multiple = 1;
+       if (rec->session.nr_sessions > 1)
+               rec->session.multiple = 1;
        for (i = session_count; i < rec->session.nr_sessions; ++i) {
                log_debug(1, "%s: Creating session %d/%d", rec->iface.name,
                          i + 1, rec->session.nr_sessions);
```
