### ISSUE TITLE
when writing data there exists a series of read requests.

### ISSUE THREAD

**Issue by shiniaas** [open-iscsi/open-iscsi#109]
when I launch a write request, I find the target gets a series of read requests and then the write request, the read requests again. why? 
I find the sequence is consistent with the read requests when the Initiator log into the Target.

**Comment by cleech** [comment]
The iSCSI drivers provide a transport for SCSI commands and don't control the issuing of read and write requests.  How do you "launch a write request"?  Is it a whole multiple of disk blocks?  If not, the block layer needs to do a read-modify-write cycle.  Is it going though a filesystem?  If so there's any number of things that could be happening.

Feel free to comment and provide more detail if you want, but I'm closing this for now as not being an issue.
