### ISSUE TITLE
Are there plans for persistent isid support?

### ISSUE THREAD

**Issue by mayurcools** [open-iscsi/open-iscsi#116]
is there any plan to add the support for persistent isid? if yes then is there any document which has this feature defined?

**Comment by gonzoleeman** [comment]
No, there are no plans that I know of. I'm unfamiliar with the issue being solved.

**Comment by gonzoleeman** [comment]
I believe I answered your question, so closing the issue, unless you wish to add such support (and can explain why you want it).
