### ISSUE TITLE
running iscsiadm -m session -P1 or P2 or P3 causes coredump on Fedora 28

### ISSUE THREAD

**Issue by RobbieTheK** [open-iscsi/open-iscsi#124]
`4.17.19-200.fc28.x86_64`

```
iscsiadm -m session -P1 
Segmentation fault (core dumped)
```

[core file here](https://storm.cis.fordham.edu/~rkudyba/core.iscsiadm.0.e0cf687273fe47fea482a27bd78b6769.2950.1536681593000000.gz).

gdb backtrace:
```
#0  session_info_print (info_level=<optimized out>, info=<optimized out>, do_show=0) at session_info.c:426
#1  0x000055658cce3e68 in main (argc=4, argv=0x7ffdcda514f8) at iscsiadm.c:3716
```

**Comment by gonzoleeman** [comment]
Yes, that issue was fixed on 4/22/2017. That should be fixed in 2.0.875 forward.
