### ISSUE TITLE
at the moment nic_nl_open retval is neither correct nor handled

### ISSUE THREAD

**Issue by cpaelzer** [open-iscsi/open-iscsi#125]
Hi,
we were just trying to debug something and came by this code and where wondering.
The RC of nic_nl_open is defined as ["0 on success, negative on error"](https://github.com/open-iscsi/open-iscsi/blob/master/iscsiuio/src/unix/nic_nl.c#L533)

But while the code sets rc to some values and might break to the error: label, it then does
[return 0;](https://github.com/open-iscsi/open-iscsi/blob/master/iscsiuio/src/unix/nic_nl.c#L679)

I wonder if it should actually initialize `rc = 0` at the beginning and `return rc;` eventually.

Furthermore on the [call to the function](https://github.com/open-iscsi/open-iscsi/blob/master/iscsiuio/src/unix/main.c) it totally ignored the retval which should maybe lead to a bad exit of the service.

These were just the thoughts when looking at the code, thanks to [Smoser](https://github.com/smoser) for making me aware of all of this. I just wanted to file it to get your opinion on it.

So do you agree to the review?
Would you want a PR to fix it or are we missing part of the concept how this is supposed to work?

**Comment by gonzoleeman** [comment]
This is in iscsiuio, which admittedly doesn't get as much use/scrutiny as iscsid and iscsiadm.

No, that just looks like a bug, as you concluded. A simple change of "return 0" to "return rc" is all that is needed I think. Yes, feel free to submit a pull request.

**Comment by cpaelzer** [comment]
Ok, while not that important (I don't have a real associated problem and think the change is functionally a no-op for now) lets clean it up still.
