### ISSUE TITLE
requirement to use systemd make build fail on non-systemd distros

### ISSUE THREAD

**Issue by lulcat** [open-iscsi/open-iscsi#149]
Hi, I am not sure how to mark a paritcular commit or so, but the commit from 16102018 needs to _check_ for systemd header, else it will fail to compile on non systemd linux.

The commit id is 93fb910880604fe9509e7efa7b8d32098fc0ef1f and so easy to revert at the moment, but as I said, should have some logic in autoconf or have #IFDEF systemd.h then add that code stuff.

Cheers.

**Comment by gonzoleeman** [comment]
I was not aware of any platforms where systemd is not used. The direction of open-iscsi has been moving towards systemd for a couple of years now IIRC.

What system are you using that does not support systemd? I have no issue with ensuring open-iscsi works on any open, unix-like operating systems, but my problem is testing -- I do not have any such systems. And I loathe to make changes that can't easily be tested.

**Comment by gonzoleeman** [comment]
I have since found out that some anti-systemd distros do exist, such as Void Unix. I've updated the Issue description to better reflect the problem.

I am willing to take a pull request to make systemd usage/inclusion a build-time option.

**Comment by Vaelatern** [comment]
Please consider that Void Linux is not anti-systemd, but systemd deliberately does not work for our use case (they are glibc only, we are also available on musl).

Other than that, we appreciate any and all help in making systemd optional for this project. Thank you!

**Comment by Whissi** [comment]
Gentoo Linux, which is about choices, supports OpenRC **and** systemd. So we are also interested in keeping open-iscsi working on non-systemd systems.

**Comment by gonzoleeman** [comment]
Understood.

**Comment by gonzoleeman** [comment]
Should have been fixed with issue #164

**Comment by lulcat** [comment]
Thanks. Sorry, didn't ever get back to you. It doesn't matter, if it was fixed. I am non of the above, but not all linuxes are systemd (still not, and going strong, including this). The init is a statically compiled non glibc dependent init, unliested. Thank you for the great work.
