### ISSUE TITLE
Domain name expired

### ISSUE THREAD

**Issue by tuxd00d** [open-iscsi/open-iscsi#15]
Looks like the domain name open-iscsi.org hasn't been renewed.

**Comment by mikechristie** [comment]
Shoot. Thanks. Will fix that.

**Comment by zackp30** [comment]
Any news on this, @mikechristie (sorry to bother)?

**Comment by mikechristie** [comment]
I have not heard back from the person that originally handled it, so I am looking into hosting and getting the domain name.

**Comment by rcsheets** [comment]
In case it's useful (and in particular in case control of open-iscsi.org can't be regained), I've registered open-iscsi.com. For now it's just set up to redirect to http://github.com/mikechristie/open-iscsi.

**Comment by mikechristie** [comment]
Thanks!

**Comment by gonzoleeman** [comment]
Hi, @rcsheets , can you point that at http://github.con/open-iscsi/open-iscsi?

@mikechristie , what is the status of open-iscsi.org?  Have you heard anything?

**Comment by cleech** [comment]
If we can get the DNS records set to open-iscsi.github.io I can put a basic landing page there.  I don't want to mess around with other web hosting, but a static page on github I could take care of.

**Comment by rcsheets** [comment]
If someone sets up a useful page at open-iscsi.github.io, I can set up the cname and redirect.

Also if someone else should own this domain name, please let me know. I'm happy to transfer it to someone else. I just bought it when I did so that it wouldn't become unavailable. I was just paranoid that if I mentioned it in public and it was unregistered, it would get snatched up by someone.

**Comment by gonzoleeman** [comment]
I believe a page is set up now at http://open-iscsi.github.io/

@rcsheets, do you _want_ to continue to own this domain name, or would you rather it was out of your hands?

**Comment by cleech** [comment]
Yeah, I put up a basic page for now based on the old sites description and some links to the repo and list.  Meant to mention that here.

**Comment by rcsheets** [comment]
The new page looks great. I'll get the domain pointing at it shortly.

I don't have a strong opinion one way or the other on owning the domain name. I just didn't want anyone to have any impression that I was unwilling to reassign it to someone officially involved with the project.

**Comment by rcsheets** [comment]
I have updated the redirection to refer to the new GitHub Page. I've also opened [a pull request](https://github.com/open-iscsi/open-iscsi.github.io/pull/1) to add CNAME support so the site can be served directly from the www.open-iscsi.com domain.

**Comment by cleech** [comment]
I pulled the CNAME file but now I think it's created a redirect loop with your current DNS settings

**Comment by rcsheets** [comment]
Sorry, that was unexpected. I'll fix it momentarily.

**Comment by rcsheets** [comment]
The DNS zone is being updated now. The fix should be live in a few hours.

**Comment by gonzoleeman** [comment]
Can we close this issue now?

**Comment by cleech** [comment]
closing, we're using open-iscsi.com now
