### ISSUE TITLE
iscsi.service reports as success even if it exited with bad error code

### ISSUE THREAD

**Issue by igo95862** [open-iscsi/open-iscsi#152]
Try starting iscsi.service in situations when it should fail. (for example no configuration, iscsid not running) The unit will report that it successfully started even though iscsiadm returned the non zero code.

The issue is ExecStart argument in iscsi.service is prefixed with "-" which means it will be considered as success no matter the exit code. This will start any other units that rely for ISCSI targets to be connected (for example mount units) even if ISCSI is not connected properly. 

Removing the "-" prefix will make iscsi.service to be successful only on clean exit.

Also SuccessExitStatus=21 should be removed to make 0 exit code the only success value.

**Comment by gonzoleeman** [comment]
This would be a non-issue if iscsi.service required iscsid.service, as per your other issue.

And we cannot remove SuccessExitStatus=21 because that's the status that is returned if there are no targets, which is a perfectly legal use case and shouldn't signal that the service failed IMHO.

**Comment by igo95862** [comment]
SuccessExitStatus=21 can be kept then.

However, "-" will make any status code or signal to be valid. For example, iscsiadm may cause SIGSEGV segmentation fault and it would still be considered to be successfully completed.

I think having a fine grade control on what is success or failure would be better and will make easier time identifying the failure point when it happens.

**Comment by gonzoleeman** [comment]
I believe you are correct. I can't remember for sure, but I can only assume I left the minus sign in there from previous testing. But I just tested again, and the minus sign should not be needed with the "SuccessExitStatus=21" setting.

So please submit another pull request and I'll be glad to fix this.

Thank you for testing this. The iscsi.service layer doesn't seem to get much exercise.

**Comment by igo95862** [comment]
Submitted. #156

**Comment by gonzoleeman** [comment]
closing as resolved.
