### ISSUE TITLE
iscsi.service should require iscsid.service 

### ISSUE THREAD

**Issue by igo95862** [open-iscsi/open-iscsi#153]
Right now iscsi.service only has After= dependency. This means it is possible to load the iscsi.service even if daemon is not up. (for example it failed to load or was not enabled)

Adding Requires=iscsid.service will make sure that daemon is loaded, enabled for boot or in case it failed iscsi.service will not try to load.

**Comment by gonzoleeman** [comment]
Please submit a pull request.

**Comment by igo95862** [comment]
#154 Submitted

**Comment by gonzoleeman** [comment]
Merged.
