### ISSUE TITLE
"Could not create Target in configFS" even with ConfigFS Mounted. (requires remount)

### ISSUE THREAD

**Issue by thehaxxa** [open-iscsi/open-iscsi#158]
**Details:**
Running Proxmox 5.3 (Debian 9): 
Open ISCSI Version: 
` 
Target fabric module iscsi: Datera Inc. iSCSI Target v4.1.0 `

--------------------------------------------------------------------------

Open-ISCSI fails to detect ConfigFS is mounted and only works after issuing `mount -t configfs none /config` returning: 

` mount: none is already mounted or /config busy
       none is already mounted on /config" `

Fstab Entry: 

`configfs /config configfs defaults 0 0`

Systemd Mount: (/lib/systemd/system/config.mount)

```
[Unit]
Description=Configuration File System Config
Documentation=https://www.kernel.org/doc/Documentation/filesystems/configfs/configfs.txt
Documentation=http://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
DefaultDependencies=no
ConditionPathExists=/config
ConditionCapability=CAP_SYS_RAWIO
After=systemd-modules-load.service
Before=sysinit.target

[Mount]
What=none
Where=/config
Type=configfs

[Install]
WantedBy=multi-user.target
```

I even added a cron entry on reboot to no avail: 
`@reboot mount -t configfs none /config`

I'm not sure why but it only works after issuing the mount command from shell. 
I used _ls_ to test config was mounted correctly as shown:

` 
root@Home-Server-U1:/config# ls
pci_ep  rdma_cm  target
`

------------------------------------------------------------------------

Really not sure what I can do as the only way I can get Open SCSI to work is to issue the mount command from shell upon reboot and then restart the Open-SCSI service, mounting via any other mechanism does not work and I can't understand why?

Any ideas what this might pertain to? 
Thanks

**Comment by gonzoleeman** [comment]
You are having issues with your iscsi _target_, not your iscsi initiator. open-iscsi is an initiator.

It appears you are using targetcli from Datera, which is quite old now, and has mostly been replaced with the free branch of that project, at github.com/open-iscsi/targetcli-fb.

I am not familiar with Proxmox nor Debian in general. On my systems, configfs gets mounted from a "modprobe configfs", or a modprobe of a module that requires configfs (such as iscsi_target_mod).

In the targetcli replacement targetcli-fb, this gets done automatically by the python code, if needed, at startup. And, bonus points: there is a mailing list that supports targetcli-fb. I'm honestly not sure what the support status is for the Datera. It looks like the project is still on github at https://github.com/Datera/targetcli but no changes have been made for 5 years.

If you feel like upgrding, replace configshell, rtslib, and targetcli with the "*-fb" versions. I _believe_ they will work with python2 or python3 (though python2 support will not last forever).

**Comment by thehaxxa** [comment]
I have since moved the issue to here: https://github.com/open-iscsi/targetcli-fb/issues/130

I should note I _am_ using targetcli-fb as installed directly from the Debian repositories. I have also posted the relevant information in the targetcli-fb mailing list. 

I should also note the configfs is loaded as a module and adding it directly to /etc/modules has no effect.
