### ISSUE TITLE
How to build ISCSI driver by using source code on linux with kernel version 3.14.xx or later?

### ISSUE THREAD

**Issue by lizhenfeiok** [open-iscsi/open-iscsi#167]
I want to compile iscsi driver (some xxx.ko files) on linux with kernel version 3.14.xx or later which has been converted into closed source OS named YHKylin.  But I find the source code seem to only support to compile iscsi driver on kernel version 2.6.14 - 2.6.34. Is that so？

**Comment by gonzoleeman** [comment]
I have no idea, since your sources are closed. The current open-iscsi works with the newest linux kernels AFAIK.

**Comment by gonzoleeman** [comment]
Marking as closed since no response
