### ISSUE TITLE
Question - Are there guarantees about the stability of the netlink API?

### ISSUE THREAD

**Issue by Logibox** [open-iscsi/open-iscsi#177]
Apologies is this already answered in some documentation I've missed.

Are there API guarantees between the kernel space and user space component of open-iscsi? For example can I use a newer version of the user space tool `iscsiadm` with an older module? Or do the user space and kernel space components need to be built at the same time?

The use case here is running `iscsiadm` from a privileged container, while relying on the host supplied kernel module.

**Comment by cleech** [comment]
The netlink API should be stable, in fact there are some minor issues with it that have been ignored rather than breaking the API.

Running iscsiadm and/or iscsid in a container does require using a privileged container with the host network namespace.

**Comment by Logibox** [comment]
Thanks!
