### ISSUE TITLE
The Current Portal and Persistent Portal are inconsistent

### ISSUE THREAD

**Issue by HHHSong** [open-iscsi/open-iscsi#179]
Hi.
    I have a question，Why the Current Portal and Persistent Portal are inconsistent ?
    I used 'iscsiadm -m discovery -t st -p 172.23.2.50:3260'  to discovery a target.
   Then i get a target  '172.23.2.50:3260,1 iqn.2016-02.com.smatx:system-gs-7150'. 
   Next i used 'iscsiadm  -m node  -T iqn.2016-02.com.smatx:system-gs-7150  -p 172.23.2.50:3260 -l '
   The end , i used 'iscsiadm  -m session -P 1'
    
   the print is :

       
Target: iqn.2016-02.com.smatx:system-gs-7150
  Current Portal: 172.23.2.51:3261,1
  Persistent Portal: 172.23.2.50:3260,1
  **********
  Interface:
  **********
  Iface Name: default
  Iface Transport: tcp
  Iface Initiatorname: iqn.2016-02.com.smatx:system-gs-7150
  Iface IPaddress: 172.23.7.150
  Iface HWaddress: <empty>
  Iface Netdev: <empty>
  SID: 741
  iSCSI Connection State: LOGGED IN
  iSCSI Session State: LOGGED_IN
  Internal iscsid Session State: NO CHANGE

why the  Current Portal is  172.23.2.51:3261,1  ?   

then get the connection ip  by SID: 741;
'cat  /sys/class/iscsi_connection/connection741\:0/address'  is '172.23.2.51'

On RFC  7143 ,  
4.3. iSCSI Session Types 
      iSCSI defines two types of sessions: 
     a) Normal operational session - an unrestricted session
     b) Discovery session - a session only opened for target discovery.The target MUST ONLY accept Text Requests with the SendTargets  key and a Logout Request with reason "close the session". All
other requests MUST be rejected.
    The session type is defined during login with the SessionType=value
 parameter in the login command.

the portal '172.23.2.50:3260' is The discvoery session used Portal,  and the portal'172.23.2.51:3261' is 
the Normal session used portal,  is that right ?

but why The Current Portal and Persistent Portal are inconsistent ?

Thanks.

**Comment by gonzoleeman** [comment]
This is from iscsi redirect. See [RFC3270](https://tools.ietf.org/html/rfc3720) page 162.

This allows a single target to represent multiple targets. For example, let's say you have 100 iSCSI targets in your storage product, and it's served by a cluster of computers running an iSCSI target. But you do not want all of your targets implemented on just one host, as that would be a bottle neck. So your storage software might create new targets on a rotating basis to different hosts in the cluster. This means that the cluster computers share the load.

Now as far as your initiator, it needs to know the IP address of the target, and it does this using discovery, usually using the "SendTargets" iSCSI command sent to a know IP address (or host name). Let's say you are contacting host "A". As part of this discovery, if you discover a target that host A knows about, but it is on host B, host A can return a login redirect. (See "status class" in the referenced RFC.) There's actually two types of "target moving": temporary or permanent. In open-iscsi, a "temp move" is handled by a retry, whereas a "permanent move" 

So I'm guessing you have a hardware target, and it is using iSCSI redirect. I believe you can get more information from iscsiadm by running debug level above 3, in which case you should see this message if redirected:

> 	log_debug(3, "login redirect ...");

(from usr/initiator.c:iscsi_login_redirect())

**Comment by gonzoleeman** [comment]
I will assume this issue is closed. Please reopen if needed.
