### ISSUE TITLE
Please cut a release

### ISSUE THREAD

**Issue by clefru** [open-iscsi/open-iscsi#18]
I am fixing bugs in the nixos packaging of open-iscsi that would depend on fixes already in HEAD but are not released. Could somebody tag a release? Even an rc is fine. Thanks!

**Comment by penetal** [comment]
Agree that an RC or similar might be a good idea, packagers have to recommend compiling from source such as the [AUR package](https://wiki.archlinux.org/index.php/InfiniBand#Bug_with_multiple_iSER_devices.2C_workarounds) or have to pre build packages from certain commits like Ubuntu `open-iscsi 2.0.873+git0.3b4b4500`.

An RC could tidy it up for packagers.

**Comment by cleech** [comment]
I finally tagged a 2.0.874
