### ISSUE TITLE
iscsi_trx goes 100% CPU usage, OOM

### ISSUE THREAD

**Issue by abbbi** [open-iscsi/open-iscsi#181]
hi,

i came around following situation while sharing MHVTL tape devices via target/cli that reproducibly crashes the iscsi target system.

My setup:

Centos8  with latest kernel 4.18.0-80.11.2.el8_0.x86_64

MHVTL Installed and tape device is shared via PSCSI backend.

Attempting following write operation from the ISCSI Client (which of course uses an uncommon big block multiplier):

` tar -b 4096 -cvf /dev/nst0 /etc/fstab
`

causes the target system to go OOM within seconds.
I was unable to catch the exact process but the following can be seen while situation goes nuts:

1) Memory usage is pretty normal up to a point where the writing process starts:

```
MiB Mem :   4829.0 total,   4504.7 free,    161.3 used,    162.9 buff/cache
MiB Mem :   4829.0 total,   2404.0 free,   2261.8 used,    163.2 buff/cache
```
2) At the point the memory usage raises, iscsi_trx's cpu usage goes from 0.0
to 100%:

```
  973 root      20   0       0      0      0 S   0.0   0.0   0:00.00 iscsi_trx
  973 root      20   0       0      0      0 R  80.0   0.0   0:00.08 iscsi_trx
  973 root      20   0       0      0      0 R  99.9   0.0   0:00.19 iscsi_trx
```

3) OOM is hit, and the target system goes unresponsive. I was able to catch OOM through netconsole but that doesnt help much because all kind of processes are reported to cause OOM.

This issue seems to be limited to the PSCSI backend of course. Im not sure if this is the right place to report this issue.. thanks anyway.

**Comment by abbbi** [comment]
I was able to catch some perf records,

here is an PERF record with regular block multiplier:

![perf](https://user-images.githubusercontent.com/3919561/70138518-b706cf80-1690-11ea-9b96-9c429c9dbaf8.jpg)

this perf record shows one which crashes the system:

![perf_4096](https://user-images.githubusercontent.com/3919561/70138544-c71eaf00-1690-11ea-8346-66000344fc35.jpg)

**Comment by yinwei18** [comment]
The kernel bug！infinite loop in “pscsi_map_sg “。But no fix。
The number of SCSI sectors  is greater than max_hw_sectors（/sys/block/sdb/queue/max_hw_sectors_kb），causing function “bio_add_pc_page“ to fail to return

**Comment by jgross1** [comment]
For patches see https://lore.kernel.org/linux-scsi/20210324071412.GC647@lst.de/T/#m7913b88621e44d86730976b077f8afeccd4e7e99

**Comment by gonzoleeman** [comment]
> For patches see https://lore.kernel.org/linux-scsi/20210324071412.GC647@lst.de/T/#m7913b88621e44d86730976b077f8afeccd4e7e99

Cool. Good job Martin. :) So I'm marking this as resolved, since it's an LIO/kernel issue, not an open-iscsi issue.
