### ISSUE TITLE
Centos7 iscsi stopping before unmounting on shutdown

### ISSUE THREAD

**Issue by scem-david** [open-iscsi/open-iscsi#19]
G'day All,

I have installed and set up an iSCSI volume.  Created and LVM LV of it, done a mkfs on it.  Mounted
it.  No problem.

It's when I shut the server down and the iscsi volume is mounted, I get issues.

My fstab entry is:

/dev/Owncloud/Owncloud          /raid/Owncloud      ext4    defaults,auto,_netdev,user_xattr,acl    0 0

I've looked at various links on this, and supposedly the issue was fixed in Centos 7.1.  However, I've just installed a fresh Centos 7.2 box (CentOS Linux release 7.2.1511 (Core)) and the issue exists.

see: https://groups.google.com/forum/#!topic/open-iscsi/8U9mAXutlyE

I have one other, possibly related, issue upon start up.  The iscsi
connection is not automatically "logged" into.  I have to do this manually.
 Not sure why, as the iscsi systemd files have lines in them saying to auto
login.  I get this message when the server is starting up:

NFSD: starting 90-second grace period (net ffffffff81a25e00)

I think this is where it's trying to mount the iscsi volume, and cannot.

Any help with resolving this is very much appreciated.

**Comment by gonzoleeman** [comment]
If your kernel hangs when you try to shutdown and there is a session then it's a bug in your kernel I believe.

Is this still an issue?

**Comment by scem-david** [comment]
Wow ! That was so long ago. Your email got tagged as spam too, and I didn't see it until today.

I remember that the issue got solved. The initial problem, I think, was due to a sequence issue with iscsi and nfs. I think it was iscsi mounts were dropped before the nfs mounts using the iscsi volumes were shut down.

The second part of the problem was caused by me manually mounting the iscsi volume, trying to get things working, and dracut?? took exception to this, and would no longer automatically mount the volume. I was instructed to check and change some flag, and it all worked again....

Sorry for no concrete details. Time dims the mind. Sorry for not reporting the resolution too, as I think it got resolved in another forum.... Again, not 100% sure.

**Comment by gonzoleeman** [comment]
No problem. Glad it got taken care of.
