### ISSUE TITLE
iscsi login fails during Fedora install with "buf[20] !sufficient to decode string[66]" since 2.1.0

### ISSUE THREAD

**Issue by AdamWill** [open-iscsi/open-iscsi#192]
Since iscsi-initiator-utils 2.1.0 ('6.2.1.0', in Fedora versioning) appeared in Fedora in November 2019, iSCSI installs are failing. On the client end we see these messages:

    20:56:16,457 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Running Thread: AnaTaskThread-ISCSILoginTask-1 (140310385428224)
    20:56:16,464 INFO kernel:scsi host3: iSCSI Initiator over TCP/IP
    20:56:16,473 INFO iscsid:iscsid: conn 0 login rejected: initiator error (02/00)
    20:56:16,473 INFO kernel: connection1:0: detected conn error (1020)
    20:56:16,476 INFO iscsid:iscsid: Connection1:0 to [target: iqn.2016-06.local.domain:support.target1, portal: 10.0.2.110,3260] through [iface: default] is shutdown.
    20:56:16,479 WARNING org.fedoraproject.Anaconda.Modules.Storage:WARNING:blivet:iSCSI: could not log into iqn.2016-06.local.domain:support.target1: Failed to call Login method on /org/freedesktop/UDisks2/Manager with ('iqn.2016-06.local.domain:support.target1', 1, '10.0.2.110', 3260, 'default', {'username': <'test'>, 'password': <'weakpassword'>, 'node.startup': <'automatic'>}) arguments: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Login failed: initiator reported error (19 - encountered non-retryable iSCSI login failure)
    20:56:16,479 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Thread Failed: AnaTaskThread-ISCSILoginTask-1 (140310385428224)
    20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-ISCSILoginTask-1 has failed: Traceback (most recent call last):
    20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.8/site-packages/pyanaconda/threading.py", line 280, in run
    20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
    20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.8/threading.py", line 870, in run
    20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
    20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.8/site-packages/pyanaconda/modules/common/task/task.py", line 95, in _task_run_callback
    20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
    20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.8/site-packages/pyanaconda/modules/storage/iscsi/discover.py", line 139, in run
    20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._log_into_node(node_info, self._credentials)
    20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.8/site-packages/pyanaconda/modules/storage/iscsi/discover.py", line 178, in _log_into_node
    20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise StorageDiscoveryError(msg)

on the server end, we see this error at the same time:

    Nov 19 12:56:16 support.domain.local tgtd[12010]: tgtd: chap_decode_string(279) buf[20] !sufficient to decode string[66]

I have [reported this downstream](https://bugzilla.redhat.com/show_bug.cgi?id=1774746) and the bug is assigned to @cleech , but he has not responded at all. I am now filing upstream as he seems more active here and I hope he'll see the issue.

This is a Fedora 32 Final release blocker, as iSCSI installs are required to work in Fedora final releases.

**Comment by gonzoleeman** [comment]
Hi:

> On Feb 26, 2020, at 3:26 PM, Adam Williamson <notifications@github.com> wrote:
> 
> Since iscsi-initiator-utils 2.1.0 ('6.2.1.0', in Fedora versioning) appeared in Fedora in November 2019, iSCSI installs are failing. On the client end we see these messages:
> 
> 20:56:16,457 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Running Thread: AnaTaskThread-ISCSILoginTask-1 (140310385428224)
> 20:56:16,464 INFO kernel:scsi host3: iSCSI Initiator over TCP/IP
> 20:56:16,473 INFO iscsid:iscsid: conn 0 login rejected: initiator error (02/00)
> 20:56:16,473 INFO kernel: connection1:0: detected conn error (1020)
> 20:56:16,476 INFO iscsid:iscsid: Connection1:0 to [target: iqn.2016-06.local.domain:support.target1, portal: 10.0.2.110,3260] through [iface: default] is shutdown.
> 20:56:16,479 WARNING org.fedoraproject.Anaconda.Modules.Storage:WARNING:blivet:iSCSI: could not log into iqn.2016-06.local.domain:support.target1: Failed to call Login method on /org/freedesktop/UDisks2/Manager with ('iqn.2016-06.local.domain:support.target1', 1, '10.0.2.110', 3260, 'default', {'username': <'test'>, 'password': <'weakpassword'>, 'node.startup': <'automatic'>}) arguments: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Login failed: initiator reported error (19 - encountered non-retryable iSCSI login failure)
> 20:56:16,479 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Thread Failed: AnaTaskThread-ISCSILoginTask-1 (140310385428224)
> 20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-ISCSILoginTask-1 has failed: Traceback (most recent call last):
> 20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.8/site-packages/pyanaconda/threading.py", line 280, in run
> 20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
> 20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.8/threading.py", line 870, in run
> 20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
> 20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.8/site-packages/pyanaconda/modules/common/task/task.py", line 95, in _task_run_callback
> 20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
> 20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.8/site-packages/pyanaconda/modules/storage/iscsi/discover.py", line 139, in run
> 20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._log_into_node(node_info, self._credentials)
> 20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.8/site-packages/pyanaconda/modules/storage/iscsi/discover.py", line 178, in _log_into_node
> 20:56:16,482 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise StorageDiscoveryError(msg)
> 
> on the server end, we see this error at the same time:
> 
> Nov 19 12:56:16 support.domain.local tgtd[12010]: tgtd: chap_decode_string(279) buf[20] !sufficient to decode string[66]

It looks like it’s an issue Chris found and fixed in the 2nd commit after 2.1.0, i.e. commit d3daa7a2bc3f. You can try building the latest upstream, or posting a reference to this commit in your redhat bug report.

I believe the issue was that Chris added support for new CHAP algorithms, but it broke some older targets, so the referenced commit makes it possible for open-iscsi to support both old and new algorithms.

Note that I just tagged version 2.1.1, so perhaps redhat will update their version? (Tagging makes that easier.)
> I have reported this downstream <https://bugzilla.redhat.com/show_bug.cgi?id=1774746> and the bug is assigned to @cleech <https://github.com/cleech> , but he has not responded at all. I am now filing upstream as he seems more active here and I hope he'll see the issue.
> 
> This is a Fedora 32 Final release blocker, as iSCSI installs are required to work in Fedora final releases.
> 

-- 
Lee Duncan

"We're only imortal for a very short time." -- Rush

**Comment by AdamWill** [comment]
Thanks! I can check if that is indeed the fix easily enough - I'm a provenpackager for Fedora so I can update the package, but until now I didn't know if there was a potential fix to apply. I'll try that one (either via the new release or by backporting it).

**Comment by cleech** [comment]
Sorry about that, I do tend to overlook Fedora issues sometimes.  I can update the package, and we can move this discussion into bugzilla.  With the new configuration options, we can default to CHAP-MD5 only and keep these targets happy while still allowing users to enable additional improved security authentication if they need to.

I haven't looked at tgtd is a long time, it seems like a different but related issue to older LIO/targetcli setups.
