### ISSUE TITLE
iscsi initiator read-cache 

### ISSUE THREAD

**Issue by Hi-Angel** [open-iscsi/open-iscsi#199]
While searching for ways to improve IOPS over iscsi, I noted that there seem to not be a read cache on the iscsi initiator side. Is it something there's support for? I also found [this paper about iscsi caching strategy](https://cis.temple.edu/~he/publications/Conferences/iCache.pdf), have it been implemented?

# Steps to reproduce lack of read cache

1.  Make sure iscsi target is up and iscsi initiator is logged in to it. Let the connection on the initiator side be represented by device sdX *(I'm hoping you'll forgive me for omitting details here)*
2. Run `sudo tcpdump -i any port iscsi-target`.
3. Run `for i in seq 1 3; do hexdump -C -n 64 /dev/sdX; done` on the initiator side.
4. Check the output of tcpdump for packets with largest length *(that is a block size + some overhead)*. These represent the block being requested by initiator from the target.

## Expected

Just one such packet, since initiator should've cached the read.

## Actual

There's 3 such packets: once for each read made by `hexdump` on the initiator side.

## Version
open-iscsi 2.0.874-5ubuntu2.7

**Comment by cleech** [comment]
1) Directly opening the block device this way will bypass the kernel page cache, most use will be through filesystems which will make use of the page cache.  Direct IO users generally don't want any caching out of their control.

2) Implementing a block layer caching solution in each initiator driver would be a bad plan.  If you really want a block layer cache, I'd suggest looking at device mapper and dm-cache.
