### ISSUE TITLE
licensing issues

### ISSUE THREAD

**Issue by rickysarraf** [open-iscsi/open-iscsi#208]
With commit https://github.com/open-iscsi/open-iscsi/commit/48a4e5b475836bcb952fb53a8bde45bdf68fe38f#diff-e32ffea735ed54d1625c505e6d147826, a dependency on openssl is introduced. `open-iscsi` is GPLv2 and it may not be correct to make use of openssl here.

https://lintian.debian.org/tags/possible-gpl-code-linked-with-openssl.html
https://people.gnome.org/~markmc/openssl-and-the-gpl

What is your view  here ?

**Comment by gonzoleeman** [comment]
Hi @rickysarraf -- I disagree that this dependency was created with recent changes -- open-iscsi depended on openssl before that, if I understand correctly. The change you reference just required a newer version of SSL. @cleech , please correct me if I'm wrong.

I know virtually nothing about this code, since Chris made these changes. After looking at [this reference I found](https://people.gnome.org/~markmc/openssl-and-the-gpl), I believe adding a disclaimer to our license might be a good enough work around. I also have no objections to changing to a different encryption package, though openssl does seem to be the best.

I'm personally not worried about this. I think people have better things to do than to rip off open-iscsi/openssl code. But I'm also not a lawyer.

**Comment by rafaeldtinoco** [comment]
@rickysarraf 

As a possible orthogonal comment, but worth mentioning, re-working debian/copyright file in the new version:

https://salsa.debian.org/linux-blocks-team/open-iscsi/-/merge_requests/4

Makes lintian not to complain about licensing issues. Possibly because object files linkedin to openssl have the correct disclaimers ?

**Comment by rickysarraf** [comment]
@gonzoleeman This goes almost 10 years ago. There was a similar problem. And Mike Christie helped fix it. https://salsa.debian.org/linux-blocks-team/open-iscsi/-/commit/89b2a6a60215f3b5c37f5125193a1d6cf28b7453

I think a similar fix would be much preferred. It would be quick.

Or license exception/disclaimer too, but I guess that'd mean it run through a legal review.

**Comment by rickysarraf** [comment]
For Debian, I only saw this issue recently when trying to update to version 2.1.1.
The current version in Debian, 2.0.874, doesn't have the hard dependency.
https://sources.debian.org/src/open-iscsi/2.0.874-7.1/usr/auth.c/

**Comment by rickysarraf** [comment]
That change goes back to when `open-isns` was in the same tree.

**Comment by cleech** [comment]
I know Fedora has taken the position that OpenSSL is a system library as defined by the GPL, which is probably why I didn't run into issues with license check tools when I added the OpenSSL code.

I'd consider a patch to disable OpenSSL use, but our build isn't in the best shape for those types of options right now.  I'd be happier to add an OpenSSL exemption if there was a standard form that would keep other distros happy.

**Comment by rafaeldtinoco** [comment]
I still need to test but I think something like this:

https://github.com/rafaeldtinoco/open-iscsi/commit/cc231b68e3d1356fd60d512661d32172d1e42f19

Will work for us (Debian) as a delta to be carried over - and maintained - until there is a better solution for the impass here. This will keep *at least* MD5 as CHAP auth algos to be used and might be enough for Debian (as it was for the past 10 years, like you said).

I'll prepare the quilt patch for:

https://salsa.debian.org/rafaeldtinoco-guest/open-iscsi/-/commits/experimental

and, @rickysarraf, if you are okay then please consider to review the merge request from my experimental branch after that.

Thank you!

**Comment by rickysarraf** [comment]
> I know Fedora has taken the position that OpenSSL is a system library as defined by the GPL, which is probably why I didn't run into issues with license check tools when I added the OpenSSL code.
> 
> I'd consider a patch to disable OpenSSL use, but our build isn't in the best shape for those types of options right now. I'd be happier to add an OpenSSL exemption if there was a standard form that would keep other distros happy.

The standard content to add the exemption would be something like:

```
 * In addition, as a special exception, the copyright holders give
 * permission to link the code of portions of this program with the
 * OpenSSL library under certain conditions as described in each
 * individual source file, and distribute linked combinations
 * including the two.
 * You must obey the GNU General Public License in all respects
 * for all of the code used other than OpenSSL.  If you modify
 * file(s) with this exception, you may extend this exception to your
 * version of the file(s), but you are not obligated to do so.  If you
 * do not wish to do so, delete this exception statement from your
 * version.  If you delete this exception statement from all source
 * files in the program, then also delete it here.
```

If it is easy, I would opt for adding the above exemption. I'm not sure what process you'd have to follow though. From the git history, there are a bunch of committers to that file

**Comment by rickysarraf** [comment]
> I still need to test but I think something like this:
> 
> [rafaeldtinoco@cc231b6](https://github.com/rafaeldtinoco/open-iscsi/commit/cc231b68e3d1356fd60d512661d32172d1e42f19)
> 
> Will work for us (Debian) as a delta to be carried over - and maintained - until there is a better solution for the impass here. This will keep _at least_ MD5 as CHAP auth algos to be used and might be enough for Debian (as it was for the past 10 years, like you said).
> 
> I'll prepare the quilt patch for:
> 
> https://salsa.debian.org/rafaeldtinoco-guest/open-iscsi/-/commits/experimental
> 
> and, @rickysarraf, if you are okay then please consider to review the merge request from my experimental branch after that.
> 
> Thank you!

Thanks for working on the revert @rafaeldtinoco 
I like the work and it will speed up the upload for Debian. But lets take the conversation to Salsa.
Let's keep this bug report about tracking the licensing issue

**Comment by gonzoleeman** [comment]
Bump ... I need to consult with @mikechristie , since I believe he crafted most of the current COPYING license file, though I've updated it.

**Comment by mikechristie** [comment]
I don't care about licensing too much and I'm not a lawyer. If you need me to change a license or give permission for something I'm ok with it.

However, for specifically the COPYING file and actually a lot of the code, I am not the primary author. Before I maintained open-iscsi, Dmitry Yusupov and Alex Aizman had created the project, written the code and maintained it.  I think some of the code also came from or is based on other projects like the linux-iscsi project, but I'm not 100% sure what is what.

**Comment by rickysarraf** [comment]
Just a follow-up on this task.
Recent stand in the Debian teams, now treat OpenSSL linkage, treating it more like a system library.
http://meetbot.debian.net/debian-ftp/2020/debian-ftp.2020-03-13-20.02.html

With that stand, I have finally gotten rid of the deviation we've had in Debian. The open-iscsi version in Debian is now in-line with what the upstream ships. 
https://tracker.debian.org/news/1192781/accepted-open-iscsi-212-1-source-amd64-all-into-unstable-unstable/

So, closing this issue now.
