### ISSUE TITLE
Hardcoded pkg-config path in Makefiles

### ISSUE THREAD

**Issue by malikbenkirane** [open-iscsi/open-iscsi#215]
If pkg-config is not in `/usr/bin/pkg-config` make will fail

As a workaround, we could as well set PKG_CONFIG like this
```
make PKG_CONFIG=$(which pkg-config)
```

see https://github.com/open-iscsi/open-iscsi/commit/623a81123c494f5c69dc6616bd72e838862e2f1f#r40138633 and https://github.com/open-iscsi/open-iscsi/commit/623a81123c494f5c69dc6616bd72e838862e2f1f#r40138674

**Comment by gonzoleeman** [comment]
Yes, I'm not sure there's a better solutions. I'm not comfortable with having the Makefile search for pkg-config, and so far open-iscsi has avoided using autoconf.

**Comment by malikbenkirane** [comment]
Alright
