### ISSUE TITLE
Unable to compile open-iscsi

### ISSUE THREAD

**Issue by JitendraKhasdev** [open-iscsi/open-iscsi#225]
I cloned the open-iscsi repo and trying to compile, but the build is failing with the following error.  

idbm.c: In function '_idbm_node_rec_link':
idbm.c:262:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (unsigned int _i = 0; _i < ARRAY_LEN(_org->_name); _i++) { \
  ^
idbm.c:1042:2: note: in expansion of macro '_rec_int_list'
  _rec_int_list(SESSION_CHAP_ALGS, recs, node, session.auth.chap_algs,
  ^
idbm.c:262:2: note: use option -std=c99 or -std=gnu99 to compile your code
  for (unsigned int _i = 0; _i < ARRAY_LEN(_org->_name); _i++) { \
  ^
idbm.c:1042:2: note: in expansion of macro '_rec_int_list'
  _rec_int_list(SESSION_CHAP_ALGS, recs, node, session.auth.chap_algs,
  ^
idbm.c:263:18: error: comparison is always true due to limited range of data type [-Werror=type-limits]
   if (_org->_name[_i] != ~0UL) { \
                  ^
idbm.c:1042:2: note: in expansion of macro '_rec_int_list'
  _rec_int_list(SESSION_CHAP_ALGS, recs, node, session.auth.chap_algs,
  ^
idbm.c:264:4: error: 'for' loop initial declarations are only allowed in C99 mode
    for (unsigned int _j = 0; _j < ARRAY_LEN(_tbl); _j++) { \
    ^
idbm.c:1042:2: note: in expansion of macro '_rec_int_list'
  _rec_int_list(SESSION_CHAP_ALGS, recs, node, session.auth.chap_algs,
  ^
cc1: all warnings being treated as errors
make[1]: *** [idbm.o] Error 1

Do I need to modify any flags? I am just following the readme to compile it.

**Comment by gonzoleeman** [comment]
What platform, are you on? 32- or 64-bit? What OS? What compiler and version are you using?

It sounds like your compiler is old, based on the "C99" error. You might be able to work around that, if using an older gcc, using "-std=c99" or "-ansi" (see the man page for your compiler). The CHAP error comes from new code from  @cleech I believe? Chris?

**Comment by JitendraKhasdev** [comment]
I was using OL7, 64 bit. Looks it has a bit older version of the compiler. This issue got resolved when I switched to OL8. It got compiled perfectly fine without adding any extra flags.

**Comment by JitendraKhasdev** [comment]
Since this issue got resolved so I am closing this issue. Thanks @gonzoleeman
