### ISSUE TITLE
Command Output not displaying correct information

### ISSUE THREAD

**Issue by victorock** [open-iscsi/open-iscsi#23]
Hello,
When running iscsiadm some fields are not being populated correctly (empty), even if they do have information in SYSFS.

Follow below an example for "ipaddress" under "iscsi_host":

[root@lnx01 ~]# iscsiadm -m host -P3
Host Number: 0
    State: running
    Transport: <empty>
    Initiatorname: <empty>
    IPaddress: <empty>
    HWaddress: <empty>
    Netdev: <empty>

[root@lnx01 ~]# systool -c iscsi_host -av
Class = "iscsi_host"

  Class Device = "host3"
  Class Device path = "/sys/devices/platform/host3/iscsi_host/host3"
    hwaddress           = "(null)"
    initiatorname       = "(null)"
    ipaddress           = "10.XX.XX.XX"
    netdev              = "(null)"
    uevent              =

```
Device = "host3"
Device path = "/sys/devices/platform/host3"
  uevent              = "DEVTYPE=scsi_host"
```

**Comment by gonzoleeman** [comment]
No reply, so closing this issue. Please re-open or re-file if it re-occurs.
