### ISSUE TITLE
How to know when iscsi has finished syncing?

### ISSUE THREAD

**Issue by ivanperez-keera** [open-iscsi/open-iscsi#235]
I have a volume mounted from a drive shared using iscsi.

Copying to that volume is quick. Too quick, I would say. I suspect the data cannot have been sent over the network that quickly.

How can I tell when the iscsi local device has finished syncing with the upstream iscsi server?

**Comment by gonzoleeman** [comment]
The operating system is treating your iSCSI-backed disc like a local disc as far as caching. In general, block caching hides much of the actual read/write IO. It doesn't "sync" exactly, but it periodically flushes IO. You can schedule flushes with the "sync" command, or you can unmount the disc if you really want every bit flushed. I also believe there are mountain options for direct-IO, but I'm not sure you'll like the performance if you could indeed disable caching.

**Comment by gonzoleeman** [comment]
Having not heard back, I will go ahead and assume I've answered your question and close this issue. Please re-open if needed or file a new issue, as appropriate.
