### ISSUE TITLE
2.1.3: missing/removed libiscsi library

### ISSUE THREAD

**Issue by kloczek** [open-iscsi/open-iscsi#245]
Looks like in latest version from the source code havs been removed libiscsi library.
My understanding is that thi library is now provided in some other repo.
May I ask where libiscsi source code is now available? (some projects still need that library)

**Comment by gonzoleeman** [comment]
I have no way of knowing what distribution or package(s) you are talking about. Are you talking about this github repository?

There is no _libiscsi_ as part of open-iscsi, but there is a _libopeniscsiusr_. Are you mixed up about our library name, or are you thinking of some other library? There **is** a libiscsi in the kernel ...

**Comment by cleech** [comment]
@kloczek are you referring to the libiscsi python interface that exists in the Fedora and RHEL packages?  It's never really had an upstream, was deemed unfit for merging into Open-iSCSI (wrapped around the internals of tools that wasn't written to be used as a lib) and in general should be replaced with libopeniscsiusr.

**Comment by gonzoleeman** [comment]
Closing this, as we have no libiscsi.
