### ISSUE TITLE
iscsistart leaves session data in partially-started state

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/open-iscsi#249]
Discovered when working on issue #241 

When `iscsistart` is used to establish a session with a target, it leaves that session in a partially-setup state. After a session is established with `iscsistart`, if you try to end that session with `iscsiadm`/`iscsid`, you get an error message, as shown here:

```
root# iscsistart -i iqn.1996-04.de.suse:01:2b8475176285 -t iqn.2003-01.org.linux-iscsi.linux-tw.x8664:sn.e29c473ac9d0 -g 1 -a 192.168.101.3 -p 3260
iscsistart: Connection1:0 to [target: iqn.2003-01.org.linux-iscsi.linux-tw.x8664:sn.e29c473ac9d0, portal: 192.168.101.3,3260] through [iface: default] is operational now
root# iscsiadm -m session
tcp: [1] 192.168.101.3:3260,1 iqn.2003-01.org.linux-iscsi.linux-tw.x8664:sn.e29c473ac9d0 (non-flash)
root# iscsiadm -m session -u
Logging out of session [sid: 1, target: iqn.2003-01.org.linux-iscsi.linux-tw.x8664:sn.e29c473ac9d0, portal: 192.168.101.3,3260]
iscsiadm: Could not logout of [sid: 1, target: iqn.2003-01.org.linux-iscsi.linux-tw.x8664:sn.e29c473ac9d0, portal: 192.168.101.3,3260].
iscsiadm: initiator reported error (2 - session not found)
iscsiadm: Could not logout of all requested sessions
root# iscsiadm -m session -u
Logging out of session [sid: 1, target: iqn.2003-01.org.linux-iscsi.linux-tw.x8664:sn.e29c473ac9d0, portal: 192.168.101.3,3260]
Logout of [sid: 1, target: iqn.2003-01.org.linux-iscsi.linux-tw.x8664:sn.e29c473ac9d0, portal: 192.168.101.3,3260] successful.
```

As you can see, `iscsistart` is able to create a working session, in that (1) a new disc shows up representing the now-connected target, and (2) asking `iscsiadm` to list sessions shows that the session is indeed present.

But when `iscsiadm` is asked to end the session (log out), it fails on its first attempt, claiming the session is not found. But the next attempt at exactly the same command works.

Note that after the second attempt to log out, which seems to work, there is no longer a local disc associated with the remote target, and there is no session listed by `iscsiadm -m session`. Also, if one runs the `iscsistart` login command again, it is able to login to the target again, also confirming that the session had correctly been terminated.

Hence, `iscsistart` is not setting up the session correctly, in some way that interferes with stopping/ending the session, even though the session does seem to be functional.

Note that `iscsiadm`/`iscsid` does not have this issue when logging into a target.

**Comment by mikechristie** [comment]
iscsistart is only used for those initial sessions that were needed in the initramfs before we pivot. iscsid is not running or used at this time.

If you run iscsistart it will create a session in the kernel. There is nothing in iscsid then. If you run the iscsiadm -m session command then it just scans sysfs.

If you run a command that then contacts iscsid then iscsid can be started up via system or the iscsid.startup value. So if you run the logout command then it would start iscsid and initially it would not see a session running in the daemon's list. iscsid would sync the kernel sessions eventually and so if you ran iscsiadm again if the sessions were done syncing then it would see it and logout.

**Comment by gonzoleeman** [comment]
Since Mike described what's happening here, I see no reason to keep this issue open.
