### ISSUE TITLE
iface.c:36:21: fatal error: libkmod.h: No such file or directory with 3.10.0-957.10.1.el7.x86_64

### ISSUE THREAD

**Issue by dusane** [open-iscsi/open-iscsi#251]
All,

I am getting libkmod compilation error with 3.10 kernel.

What am i missing here ?

Regards,
-Manish

$ make
make -C libopeniscsiusr
make[1]: Entering directory `<path>/libopeniscsiusr'
cc -O2 -g -Wall -Werror -Wextra -fvisibility=hidden -fPIC    -c -o iface.o iface.c
iface.c:36:21: fatal error: libkmod.h: No such file or directory
 #include <libkmod.h>
                     ^
compilation terminated.
make[1]: *** [iface.o] Error 1
make[1]: Leaving directory `<path>/libopeniscsiusr'
make: *** [user] Error 2

**Comment by gonzoleeman** [comment]
Wow. 3.10 is pretty old, and the HEAD of open-iscsi isn't designed to be backwards compatible.

In particular, I don't believe libkmod came into existance until after that, but I'm not a libkmod expert. [Check here](http://www.jonmasters.org/blog/2011/12/20/libkmod-replaces-module-init-tools/) for how libkmod replaced module-init-tools. Before open-iscsi used libkmod, it used to fork/exec modprobe to ensure the transport module was loaded.

Have a look at commit:

> 2da7176acc36 Use libkmod instead of fork/exec of modprobe.

Where I switched from fork/exec to libkmod. I believe you will have to compile your own fork and reverse this commit if you want to try to run on 3.10, though I suspect there will be other issues, like the fact that the kernel iscsi code is not in sync with iscsid.

Can you not use an older version of open-iscsi? I believe this was introduced in 2.0.877, so 2.0.876?

**Comment by dusane** [comment]
Thanks @gonzoleeman , This is indeed very old. Had to try a strange combo. I can use older version, will try 2.0.876 as you suggested.

**Comment by gonzoleeman** [comment]
You need to make sure you have the libkmod development package.

**Comment by gonzoleeman** [comment]
No movement on this for 6 months, so closing. Please re-open if this is still an issue.
