### ISSUE TITLE
Segmentation fault when updating node starting with 2.1.3

### ISSUE THREAD

**Issue by bswartz** [open-iscsi/open-iscsi#252]
When I upgraded from 2.1.2 to 2.1.3, I started seeing segmentation faults when updating a node.

```
[arch@dev ~]$ sudo iscsiadm -m discoverydb -t st -p 192.168.0.1:3260 -D
192.168.0.1:3260,1 iqn.1991-05.com.microsoft:example
[arch@dev ~]$ sudo iscsiadm -m node -p 192.168.0.1:3260 -T iqn.1991-05.com.microsoft:example -o update -n node.session.scan -v manual
Segmentation fault (core dumped)
```

**Comment by gonzoleeman** [comment]
Fixed with this commit:

> 19f1ae0b7bbc Fix iscsistart login issue when target is delayed.

Note that the core dump occurs as iscsiadm is exiting, so the requested action (in your case) actually worked.

**Comment by gonzoleeman** [comment]
Fixed with **this** commit:

> 76a5ebf95570 Fix iscsiadm segfault when exiting

(I briefly posted the wrong commit)

NOTE that this problem makes iscsiadm core dump right as it is exiting with success.
