### ISSUE TITLE
Problem to terminate connection at shutdown in yunohost based on debian 10

### ISSUE THREAD

**Issue by boistordu** [open-iscsi/open-iscsi#262]
Hi,

So [here](https://forum.yunohost.org/t/iscsi-and-un-responsiveness-at-shutdown/15546) is the post I originally made about my problem with iscsi thinking tht it would be like plug and play but not at all apparently past a certain point .
So yunohost is kind of a big webapp integrated with the OS for managing a self hosted server.
So this webapp is hosting several other webapps that you can install at will like peertube, wordpress etc. 
So I wanted more space for peertube among other things so I've made my links like I did for the nextcloud storage. 
But the peertube implementation here for storage is in `/home/yunohost.apps/peertube` 
Since it's part from the user file system it got apparently complicated for the OS to actually close the connection as shown on the photo in the post.
also I had a failed launch at every boot but as explained further in the post (in french but I can summarize in english if needed), I manage to arrange that by deleting the wrong/old links and by adding a iscsi initramfs like for the diskless rasp pi setup available multiple times on a browser search.

So In you doc I've seen that I should change the ping timer but you didn't specify the file where I should change those lines and I didn't quite find them. And to be honest, even if your README is really good, the documentation or experiments of other people on the web is quite lacking here. So it would be nice to specify the file at the beginning of every chapter you make so that we know what we are talking about? 

I've tried also to put `ISCSI_ROOT_KEEP_ALL_SESSIONS_AT_SHUTDOWN=0` at 1 but I don't know, since no doc available, if it was the right syntax to do so? 
And I've included the mounting points where the disks are mounted in /media (there is binding in the fstab to repurpose them to the good place) 
But now the VM would not stop at all.
So I'm going to try without the mounting points and with the settings at 1 and see if there is a difference...

Some guidance would be nice.

**Comment by boistordu** [comment]
Also I would like to know some specifications.
The shutdown of the network service is previous to the unmounting filesystems. 
is that a problem to open-iscsi? From my common sense it is a real big problem but maybe you can tell me otherwise.

Or maybe open-iscsi open a nother link and don't rely on network services?

**Comment by boistordu** [comment]
I'm going to copy paste a shutdown sequence from my syslog. 
I just want to confirm that's because of the unsuccessfull unmounting of one of the iscsi instance, which is here peertube, the whole thing goes to shit and won't reboot:
```
Apr 29 20:04:17 testing systemd[1]: unattended-upgrades.service: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Stopped target Timers.
Apr 29 20:04:17 testing systemd[1]: Stopping GitLab Runit supervision process...
Apr 29 20:04:17 testing systemd[1]: Stopped target Sound Card.
Apr 29 20:04:17 testing systemd[1]: Unmounting /home/yunohost.multimedia...
Apr 29 20:04:17 testing syncthing[3131]: [monitor] INFO: Signal 15 received; exiting
Apr 29 20:04:17 testing syncthing[3131]: [YM3QV] INFO: Disconnected from relay relay://78.46.186.181:22067
Apr 29 20:04:17 testing syncthing[3131]: [YM3QV] INFO: QUIC listener ([::]:22000) shutting down
Apr 29 20:04:17 testing syncthing[3131]: [YM3QV] INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down
Apr 29 20:04:17 testing systemd[1]: Stopping Syncthing - Open Source Continuous File Synchronization for ...
Apr 29 20:04:17 testing systemd[1]: Unmounting /home/yunohost.backup...
Apr 29 20:04:17 testing systemd[1]: apt-daily-upgrade.timer: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Stopped Daily apt upgrade and clean activities.
Apr 29 20:04:17 testing systemd[1]: Unmounting /home/yunohost.app/funkwhale...
Apr 29 20:04:17 testing systemd[1]: Stopped target Graphical Interface.
Apr 29 20:04:17 testing systemd[1]: phpsessionclean.timer: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Stopped Clean PHP session files every 30 mins.
Apr 29 20:04:17 testing systemd[1]: logrotate.timer: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Stopped Daily rotation of log files.
Apr 29 20:04:17 testing systemd[1]: man-db.timer: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Stopped Daily man-db regeneration.
Apr 29 20:04:17 testing systemd[1]: Unmounting /run/user/0...
Apr 29 20:04:17 testing systemd[1]: apt-daily.timer: Succeeded.
Apr 29 20:04:17 testing systemd[16018]: home-yunohost.multimedia.mount: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Stopped Daily apt download activities.
Apr 29 20:04:17 testing systemd[1]: Stopping Session 17 of user root.
Apr 29 20:04:17 testing systemd[1]: Unmounting /home/yunohost.app/peertube...
Apr 29 20:04:17 testing systemd[1]: systemd-tmpfiles-clean.timer: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Stopped Daily Cleanup of Temporary Directories.
Apr 29 20:04:17 testing systemd[16018]: home-yunohost.app-funkwhale.mount: Succeeded.
Apr 29 20:04:17 testing systemd[16018]: home-yunohost.backup.mount: Succeeded.
Apr 29 20:04:17 testing umount[4400]: umount: /run/user/0: la cible est active.
Apr 29 20:04:17 testing umount[4401]: umount: /home/yunohost.app/peertube: la cible est active.
Apr 29 20:04:17 testing systemd[1]: run-user-0.mount: Mount process exited, code=exited, status=32/n/a


Apr 29 20:04:17 testing systemd[1]: Failed unmounting /run/user/0.
Apr 29 20:04:17 testing systemd[1]: home-yunohost.app-peertube.mount: Mount process exited, code=exited, status=32/n/a
Apr 29 20:04:17 testing systemd[1]: Failed unmounting /home/yunohost.app/peertube.
Apr 29 20:04:17 testing systemd[1]: home-yunohost.multimedia.mount: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Unmounted /home/yunohost.multimedia.
Apr 29 20:04:17 testing systemd[1]: home-yunohost.app-funkwhale.mount: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Unmounted /home/yunohost.app/funkwhale.
Apr 29 20:04:17 testing systemd[1]: home-yunohost.backup.mount: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Unmounted /home/yunohost.backup.
Apr 29 20:04:17 testing systemd[1]: Unmounting /home...
Apr 29 20:04:17 testing umount[4402]: umount: /home: la cible est active.
Apr 29 20:04:17 testing systemd[1]: home.mount: Mount process exited, code=exited, status=32/n/a
Apr 29 20:04:17 testing systemd[1]: Failed unmounting /home.
Apr 29 20:04:17 testing systemd[1]: systemd-fsck@dev-disk-by\x2duuid-391ef6a0\x2dc96d\x2d4382\x2d9c96\x2d79cfcbd94060.service: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Stopped File System Check on /dev/disk/by-uuid/391ef6a0-c96d-4382-9c96-79cfcbd94060.
Apr 29 20:04:17 testing systemd[1]: session-17.scope: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Stopped Session 17 of user root.
Apr 29 20:04:17 testing systemd[1]: Stopping User Manager for UID 0...
Apr 29 20:04:17 testing systemd[16018]: Stopped target Default.
Apr 29 20:04:17 testing systemd[16018]: Stopped target Basic System.
Apr 29 20:04:17 testing systemd[16018]: Stopped target Timers.
Apr 29 20:04:17 testing systemd[16018]: Stopped target Sockets.



Apr 29 20:04:17 testing systemd[16018]: dbus.socket: Succeeded.
Apr 29 20:04:17 testing systemd[16018]: Closed D-Bus User Message Bus Socket.
Apr 29 20:04:17 testing systemd[16018]: Stopped target Paths.
Apr 29 20:04:17 testing systemd[16018]: Reached target Shutdown.
Apr 29 20:04:17 testing systemd[16018]: systemd-exit.service: Succeeded.
Apr 29 20:04:17 testing systemd[16018]: Started Exit the Session.
Apr 29 20:04:17 testing systemd[16018]: Reached target Exit the Session.
Apr 29 20:04:17 testing systemd[1]: user@0.service: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Stopped User Manager for UID 0.
Apr 29 20:04:17 testing systemd[1]: Stopping User Runtime Directory /run/user/0...
Apr 29 20:04:17 testing systemd[1]: run-user-0.mount: Failed with result 'exit-code'.
Apr 29 20:04:17 testing systemd[1]: user-runtime-dir@0.service: Succeeded.
Apr 29 20:04:17 testing systemd[1]: Stopped User Runtime Directory /run/user/0.
Apr 29 20:04:17 testing systemd[1]: Removed slice User Slice of UID 0.
Apr 29 20:04:17 testing kernel: [ 5005.525885] sd 6:0:0:3: Power-on or device reset occurred
Apr 29 20:04:17 testing kernel: [ 5005.538046] sd 6:0:0:0: Power-on or device reset occurred
Apr 29 20:04:17 testing envdir[1966]: [2021-04-29 18:04:17,971: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
Apr 29 20:04:17 testing syncthing[3131]: [YM3QV] INFO: TCP listener ([::]:22000) shutting down
Apr 29 20:04:17 testing syncthing[3131]: [YM3QV] INFO: Exiting
Apr 29 20:04:18 testing systemd[1]: syncthing.service: Succeeded.
Apr 29 20:04:18 testing systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for .
Apr 29 20:04:19 testing systemd[1]: gitlab-runsvdir.service: Succeeded.
Apr 29 20:04:19 testing systemd[1]: Stopped GitLab Runit supervision process.
Apr 29 20:04:19 testing systemd[1]: Stopped target Multi-User System.
Apr 29 20:04:19 testing systemd[1]: sysstat.service: Succeeded.
Apr 29 20:04:19 testing systemd[1]: Stopped Resets System Activity Data Collector.
Apr 29 20:04:19 testing systemd[1]: Stopping librephotos-backend...
Apr 29 20:04:19 testing systemd[1]: Stopping librephotos-image-similarity...
Apr 29 20:04:19 testing systemd[1]: Stopping funkwhale celery worker...
Apr 29 20:04:19 testing systemd[1]: Stopping Etherpad-lite, the collaborative editor....
Apr 29 20:04:19 testing systemd[1]: Stopping Galène: videoconferencing server...
Apr 29 20:04:19 testing systemd[1]: Stopping YunoHost API Server...
Apr 29 20:04:19 testing systemd[1]: Stopping Droppy: self-hosted file storage server...
Apr 29 20:04:19 testing systemd[1]: Stopping ClamAV virus database updater...
Apr 29 20:04:19 testing droppy[561]: 2021-04-29 20:04:19 [INFO] Received SIGTERM - Shutting down ...
Apr 29 20:04:19 testing systemd[1]: Stopping LSB: Metronome XMPP Server...
Apr 29 20:04:19 testing freshclam[617]: Thu Apr 29 20:04:19 2021 -> Update process terminated
Apr 29 20:04:19 testing systemd-memcached-wrapper[602]: Signal handled: Terminated.
Apr 29 20:04:19 testing systemd[1]: Stopping YunoHost Firewall...
Apr 29 20:04:19 testing systemd[1]: Stopping memcached daemon...
Apr 29 20:04:19 testing systemd[1]: Stopping Zero Knowledge realtime collaborative editor....
Apr 29 20:04:19 testing npm[1983]: 2021-04-29T18:04:19.658Z info: #011HedgeDoc has been killed by signal, try to exit gracefully...
Apr 29 20:04:19 testing pipenv[606]: [C 2021-04-29 20:04:19.659 JupyterHub app:2827] Received signal SIGTERM, initiating shutdown...
Apr 29 20:04:19 testing pipenv[606]: [I 2021-04-29 20:04:19.660 JupyterHub app:2468] Cleaning up single-user servers...
Apr 29 20:04:19 testing pipenv[606]: [I 2021-04-29 20:04:19.660 JupyterHub proxy:735] Cleaning up proxy[2804]...
Apr 29 20:04:19 testing pipenv[606]: [I 2021-04-29 20:04:19.660 JupyterHub app:2500] ...done
Apr 29 20:04:19 testing systemd[1]: Stopping HedgeDoc: collaborative Markdown notes...
Apr 29 20:04:19 testing pipenv[606]: 20:04:19.661 [ConfigProxy] #033[33mwarn#033[39m: Terminated
Apr 29 20:04:19 testing systemd[1]: Stopping JupyterLab...
Apr 29 20:04:19 testing systemd[1]: Stopping calibreweb...
Apr 29 20:04:19 testing systemd[1]: Stopping Deferred execution scheduler...
Apr 29 20:04:19 testing systemd[1]: Stopping RabbitMQ Messaging Server...
Apr 29 20:04:19 testing systemd[1]: Stopping Name Service Cache Daemon...
Apr 29 20:04:19 testing systemd[1]: Stopping Image hosting and sharing service...
Apr 29 20:04:19 testing systemd[1]: Stopping Gotify a simple server for sending and receiving messages...
Apr 29 20:04:19 testing systemd[1]: Stopping LSB: Provide limited super user privileges to specific users...
Apr 29 20:04:19 testing systemd[1]: Stopping PostSRSd Daemon...
Apr 29 20:04:19 testing systemd[1]: Stopping Erlang Port Mapper Daemon...
Apr 29 20:04:19 testing ntpd[666]: ntpd exiting on signal 15 (Terminated)
Apr 29 20:04:19 testing ntpd[666]: 212.112.228.242 local addr 172.20.0.37 -> <null>
Apr 29 20:04:19 testing ntpd[666]: 78.46.162.102 local addr 172.20.0.37 -> <null>
Apr 29 20:04:19 testing ntpd[666]: 176.221.42.125 local addr 172.20.0.37 -> <null>
Apr 29 20:04:19 testing ntpd[666]: 213.209.109.45 local addr 172.20.0.37 -> <null>
Apr 29 20:04:19 testing ntpd[666]: 131.234.220.231 local addr 172.20.0.37 -> <null>
Apr 29 20:04:19 testing ntpd[666]: 5.199.135.170 local addr 172.20.0.37 -> <null>
Apr 29 20:04:19 testing systemd[1]: Stopping Network Time Service...
Apr 29 20:04:19 testing systemd[1]: Stopping Supervisor process control system for UNIX...
Apr 29 20:04:19 testing mysqld[985]: 2021-04-29 20:04:19 40 [Warning] Aborted connection 40 to db: 'etherpad_mypads' user: 'etherpad_mypads' host: 'localhost' (Got an error reading communication packets)
Apr 29 20:04:19 testing systemd[1]: Stopping ffsync uWSGI app...
Apr 29 20:04:19 testing systemd[1]: Stopping librephotos-backend...
```

**Comment by gonzoleeman** [comment]
You have asked several things. It's much easier to answer one question at a time, but I'll take a stab at answering some of your queries.

You didn't list your version of open-iscsi nor what distribution you are on. Please include those when asking questions.

First of all, yes, you will have problems if you shut down the network before you shut down open-iscsi. Assuming you are using systemd, you need to ensure that the networking and open-iscsi have their dependencies set correctly. This is distribution-specific, and not related directly to open-iscsi.

Second, I have no idea what you're talking about with ISCSI_ROOT_KEEP_ALL_SESSIONS_AT_SHUTDOWN=0. There is no such variable/macro in open-iscsi. Perhaps this is distribution-specific?

**Comment by boistordu** [comment]
@gonzoleeman thanks to take the time to answer me, really :) much appreciated.

So indeed I've asked several things but all related to the same thing which is an actual problem of race condition between shutdown target, shutdown networking and shutdown open-iscsi link.
Nevertheless I think my problem is primarly caused by the webapp peertube but I will put that aside for the moment to answer to your questions.

So to answer it briefly, it's all in the title: 

> in yunohost based on debian 10

whether it's debian 10.1 or 10.3 I think it's pretty safe to assume if the guy on the other side is not specifying it, it's because it's just up-to-date. 

And Yunohost would have the direct answer to your question which I've explained what it is there: 

> So yunohost is kind of a big webapp integrated with the OS for managing a self hosted server.
> So this webapp is hosting several other webapps that you can install at will like peertube, wordpress etc.

But if you want more specifics: 
https://commons.wikimedia.org/wiki/Category:YunoHost
https://en.everybodywiki.com/YunoHost

I think it has a space in every open-source conference for 10 years now.  like at the FOSDEM for example: https://www.youtube.com/watch?v=BFL-pIWMldA

`4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux`

So for the variable I was referencing it's based on Debian documentation actually. So I don't know which was the first system you've developped open-iscsi for but don't think this file is specified to yunohost only.
the file is `/etc/default/open-iscsi `

and the content is like this: 
```
# List of LVMed iSCSI Volume Groups.
# Multiple Volume Groups can be specified with spaces
#
# This list defines the Volume Groups that should be activated at boot
# after iSCSI has been activated. If you use dynamic activation of LVM
# volumes (lvmetad), you can (and should) leave this empty.
#
# On shutdown, this setting typically has no effect, since open-iscsi
# tries to determine all active VGs on iSCSI and deactivate them.
# However, if you have a really complicated stacking setup that isn't
# automatically detected, volume groups defined here will also be
# deactivated.
#
# To see whether open-iscsi is able to properly detect your setup for
# shutdown, execute the following on a running system:
#    /lib/open-iscsi/umountiscsi.sh --dry-run
# This will tell you what steps will betaken at shutdown before logging
# out of the iSCSI session.
LVMGROUPS=""


# Handle _netdev devices
# You can specify your iSCSI (LVMed or Multipathed or DM Encrypted)
# devices with the _netdev mount option and open-iscsi will treat them
# accordingly.
#
# Note: however, handling _netdev devices comes with the caveat that
# other _netdev mounts, like an NFS share, also get pulled in with it.
#
# If this option is set to 0, no iSCSI mounts in /etc/fstab will be
# automatically mounted on systems running sysvinit. This setting is
# not necessary when using systemd as init system (Debian's default).
HANDLE_NETDEV=1


# Additional mounts to exclude at shutdown.
#
# If you have additional mounts on iSCSI that shouldn't be umounted at
# shutdown by open-iscsi (by default, open-iscsi excludes / and on
# systemd systems als /usr), place them here. iSCSI sessions that carry
# these mounts will also be kept open.
#
# If any of these mountpoints contain spaces, please use the same
# escaping as in /etc/fstab, i.e. replace the spaces with \040.
#EXCLUDE_MOUNTS_AT_SHUTDOWN="/media/storage,/media/back,/media/media_share"

EXCLUDE_MOUNTS_AT_SHUTDOWN=""


# Don't logout from ANY iSCSI session on shutdown
#
# When shutting down, if the root filesystem is on iSCSI, open-iscsi
# tries to determine which sessions are still required for the root
# filesystem. By default, the host will still logout from all other
# sessions.
#
# If you are running a very complicated setup of your root filesystem
# (multiple mapping levels stacked on top of each other), it may be the
# case that the autodetection logic doesn't work propery. You may then
# enable this setting to keep around all iSCSI sessions.
#
# Note that /etc/iscsi/iscsi.initramfs must exist for this option to
# have any effect at all.
#
# This was the default behavior in previous versions of this package
# up to the version that shipped with Debian 8 (Jessie).
#
ISCSI_ROOT_KEEP_ALL_SESSIONS_AT_SHUTDOWN=1
```
So must I conclude that this is not part of your master package? And so that you are not maintaining the debian package ?

So if apt is correct the version of open-iscsi is: `open-iscsi/stable,now 2.0.874-7.1 amd64`

How would I be sure that the maintainers of the package have done the work properly and that the iscsi links are not cut after the network is down?

**Comment by gonzoleeman** [comment]
> @gonzoleeman thanks to take the time to answer me, really :) much appreciated.
> 
> So indeed I've asked several things but all related to the same thing which is an actual problem of race condition between shutdown target, shutdown networking and shutdown open-iscsi link.
> Nevertheless I think my problem is primarly caused by the webapp peertube but I will put that aside for the moment to answer to your questions.
> 
> So to answer it briefly, it's all in the title:
> 
> > in yunohost based on debian 10
> 
> whether it's debian 10.1 or 10.3 I think it's pretty safe to assume if the guy on the other side is not specifying it, it's because it's just up-to-date.
> 
> And Yunohost would have the direct answer to your question which I've explained what it is there:
> 
> > So yunohost is kind of a big webapp integrated with the OS for managing a self hosted server.
> > So this webapp is hosting several other webapps that you can install at will like peertube, wordpress etc.
> 
> But if you want more specifics:
> https://commons.wikimedia.org/wiki/Category:YunoHost
> https://en.everybodywiki.com/YunoHost
> 
> I think it has a space in every open-source conference for 10 years now. like at the FOSDEM for example: https://www.youtube.com/watch?v=BFL-pIWMldA
> 
> `4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux`

Ok, it's a many-layered application suite that uses (among other things) open-iscsi, with LVM layered on top of the open-iscsi volumes.

> 
> So for the variable I was referencing it's based on Debian documentation actually. So I don't know which was the first system you've developped open-iscsi for but don't think this file is specified to yunohost only.
> the file is `/etc/default/open-iscsi `
> 
> and the content is like this:
> 
> ```
> # List of LVMed iSCSI Volume Groups.
> # Multiple Volume Groups can be specified with spaces
> #
> ... (cut since not needed)
> 
> # Don't logout from ANY iSCSI session on shutdown
> #
> # When shutting down, if the root filesystem is on iSCSI, open-iscsi
> # tries to determine which sessions are still required for the root
> # filesystem. By default, the host will still logout from all other
> # sessions.
> #
> # If you are running a very complicated setup of your root filesystem
> # (multiple mapping levels stacked on top of each other), it may be the
> # case that the autodetection logic doesn't work propery. You may then
> # enable this setting to keep around all iSCSI sessions.
> #
> # Note that /etc/iscsi/iscsi.initramfs must exist for this option to
> # have any effect at all.
> #
> # This was the default behavior in previous versions of this package
> # up to the version that shipped with Debian 8 (Jessie).
> #
> ISCSI_ROOT_KEEP_ALL_SESSIONS_AT_SHUTDOWN=1
> ```
> 
> So must I conclude that this is not part of your master package? And so that you are not maintaining the debian package ?

Yes, that is Debian (and/or RH) specific. This stuff is trying hard to fix an unfixable problem. That problem is that things can be layered somewhat arbitrarily, and that means that they have to be started up and shut down in the proper order. The simplest example is LVM on top of open-iscsi on top of the network. This script and it's friends try to make sure things are sequenced properly, I believe. (I didn't write this, nor do I have to support it, since SUSE doesn't do this.)

> 
> So if apt is correct the version of open-iscsi is: `open-iscsi/stable,now 2.0.874-7.1 amd64`
> 
> How would I be sure that the maintainers of the package have done the work properly and that the iscsi links are not cut after the network is down?

I believe you need to file a bug with Debian. Or maybe there's a mailing list?

**Comment by boistordu** [comment]
Okey thanks for all those enlightenment and I'm not sure I would have known that it was developed originally under opensuse as you just said it if you  didn't have said it. 
It would be maybe nice to add a remark about that in the erasme.

I think I found the problem which is external to yours, it seems that peertube left a process opened which impeach home to be unmounted. And so of course your package was still needed after the termination of the network to unmount /home
I will try to work it out with peertube maintainer for yunohost. 
And if I found it I will do a ticket in Debian to talk about this.

If you ever come across or have any idea about which section of Debian I should target in their ticket system or any mailing list lead, don't hesitate to communicate to me :) 
Thanks again

**Comment by gonzoleeman** [comment]
On May 5, 2021, at 4:21 PM, Impostor syndrom ***@***.***> wrote:
> 
> 
> Okey thanks for all those enlightenment and I'm not sure I would have known that it was developed originally under opensuse as you just said it if you didn't have said it.
> It would be maybe nice to add a remark about that in the erasme.
> 

No, it was not developed originally by SUSE at all. I’m simply one of the two co-maintainers for open-iscsi, and I happen to work at SUSE, so I have intimate experience with open-iscsi on SUSE/openSUSE, including the distribution-specific things done. But I do not have much experience with the distribution-specific things other distributions do unless I download an ISO from them and try it out.
> I think I found the problem which is external to yours, it seems that peertube left a process opened which impeach home to be unmounted. And so of course your package was still needed after the termination of the network to unmount /home
> I will try to work it out with peertube maintainer for yunohost.
> And if I found it I will do a ticket in Debian to talk about this.
> 
> If you ever come across or have any idea about which section of Debian I should target in their ticket system or any mailing list lead, don't hesitate to communicate to me :)
> Thanks again
> 
Google found this link: https://www.debian.org/Bugs/Reporting <https://www.debian.org/Bugs/Reporting>

You might start there.

**Comment by boistordu** [comment]
Thanks anyway for everything :)
