### ISSUE TITLE
Plaintext Key issue

### ISSUE THREAD

**Issue by wenchao-hao** [open-iscsi/open-iscsi#267]
If we configure iscsi initiator with CHAP certification, the username and password would be written in each node's configure file such as ```/etc/iscsi/nodes/iqn.2003-01.org.linux-iscsi.localhost.test:sn.12345678abcd/9.84.111.6,3260,1/default``` as string. This makes it visiable to everyone who can access these configure file. 

```
cat /etc/iscsi/nodes/iqn.2003-01.org.linux-iscsi.localhost.test\:sn.12345678abcd/9.84.111.6\,3260\,1/default | grep -E 'username|password'
node.session.auth.username = demo
node.session.auth.password = 123
node.session.auth.username_in = demo_in
node.session.auth.password_in = demo_in
```

Is this reasonable ? And shall we change these plaintext key to ciphertext？

**Comment by gonzoleeman** [comment]
Yes, this is reasonable. These files are protected with read-write permissions, so that only root can see them. And when you display this info from iscsiadm, they are hidden.

They are not that "safe" anyway. Anyone with a network snooper (or a computer on the network where they can snoop) can see the passwords, since they are sent in plaintext.

**Comment by wenchao-hao** [comment]
> They are not that "safe" anyway. Anyone with a network snooper (or a computer on the network where they can snoop) can see the passwords, since they are sent in plaintext.

I am confused about this, here is a frame which captured by tcpdump. It seems that the passwords are transmitted with a encrypted string.

```
Frame 42: 122 bytes on wire (976 bits), 122 bytes captured (976 bits)
iSCSI (Login Command)
    Opcode: Login Command (0x03)
    1... .... = T: Transit to next login stage
    .0.. .... = C: Text is complete
    .... 00.. = CSG: Security negotiation (0x0)
    .... ..01 = NSG: Operational negotiation (0x1)
    VersionMax: 0x00
    VersionMin: 0x00
    TotalAHSLength: 0x00
    DataSegmentLength: 54 (0x00000036)
    ISID: 00023d000005
    TSIH: 0x0000
    InitiatorTaskTag: 0x00000000
    CID: 0x0000
    CmdSN: 0x00000000
    ExpStatSN: 0xc018d69d
    Key/Value Pairs
        KeyValue: CHAP_N=demo
        KeyValue: CHAP_R=0x10f12068cc637e960a09141a80f42af0
    Padding: 0000
```

**Comment by cleech** [comment]
It's CHAP, so the password isn't transmitted in plaintext (the name is) but both the initiator and target need access to the plaintext password in order to generate/check the response.  It's also not considered secure anymore.  Because the plaintext password is needed to complete authentication, I think we'd need some reasonable proposal for secret management that shows a real security improvement before considering changing anything.  It has to be saved somewhere, it's needed by a system service, and potentially during early boot in order to access the root filesystem.

**Comment by gonzoleeman** [comment]
On Jul 30, 2021, at 10:04 AM, Chris Leech ***@***.***> wrote:
> 
> 
> It's CHAP, so the password isn't transmitted in plaintext (the name is) but both the initiator and target need access to the plaintext password in order to generate/check the response. It's also not considered secure anymore. Because the plaintext password is needed to complete authentication, I think we'd need some reasonable proposal for secret management that shows a real security improvement before considering changing anything. It has to be saved somewhere, it's needed by a system service, and potentially during early boot in order to access the root filesystem.
> 
> 

Yes, apologies for saying it was sent in the clear without checking first. :) Chris worked on improving CHAP, but it’s still not considered secure.

The official open-iscsi advice is to use kerberos, I believe. :) But nobody really goes to that much trouble in my (limited) experience.

And IIUC the data read via iscsi from a remote node is sent in the clear on the network wire, no matter the CHAP usage.

— 
Lee

**Comment by wenchao-hao** [comment]
Thank you for your answers, and would you like to ask if the community has any plans to change it?

**Comment by gonzoleeman** [comment]
> On Aug 31, 2021, at 7:07 PM, Wenchao Hao ***@***.***> wrote:
> 
> 
> Thank you for your answers, and would you like to ask if the community has any plans to change it?
> 
> 
> 

No, no plans to change the security of open-iscsi at this time.

--
Ignore the Lee-Man behind the curtain ...

"Life's a long song. But the tune ends too soon for us all." -- Ian Anderson

**Comment by gonzoleeman** [comment]
My intention is to close this issue, unless I hear any objections.

**Comment by wenchao-hao** [comment]
OK, this issue would be closed
