### ISSUE TITLE
Quick Question on "flash vs Non-flash"

### ISSUE THREAD

**Issue by arajapa** [open-iscsi/open-iscsi#27]
Hi,

Just had a quick question.  I was wondering if you could tell me in this function, what is flash vs non-flash referring to? It doesnt appear to be referring to the actually media type.

static char *get_iscsi_node_type(struct session_info *info)
{
	int pid = iscsi_sysfs_session_user_created(info->sid);

	if (!pid)
		return "flash";
	else
		return "non-flash";
}

Example:
[root@iop061046 ~]# iscsiadm -m session -P 3 | grep -i flash
Target: iqn.2003-01.org.linux-iscsi.iop061048.x8664:sn.ceedd03dc66d (non-flash)

Thank you in advance,
Alan

**Comment by cleech** [comment]
Yeah, the terminology there is a bit confusing.

"Flash" is referring to records stored in non-volitile flash storage on an iSCSI HBA.  While "non-flash" is a normal record type saved in a local filesystem.

So if there's no stored pid of the iscsid process that created the session, then it was created by an offloading iSCSI HBA from it's own configuration, and the sysfs records were populated by the driver.  That's a "flash" record.

**Comment by arajapa** [comment]
Thank you!
