### ISSUE TITLE
README points to a squatter domain?

### ISSUE THREAD

**Issue by justinclift** [open-iscsi/open-iscsi#28]
The main README file is pointing to a domain squatter, not an actual iSCSI related website:

* https://github.com/open-iscsi/open-iscsi/blob/f951a06beb55d7ccc4d9c13a3a83ec2bee96636d/README#L29

Should this be updated to the .com instead?

**Comment by cleech** [comment]
Changed to open-iscsi.com in README and man pages, thanks!
