### ISSUE TITLE
discovery on same portal would override node's configure

### ISSUE THREAD

**Issue by wenchao-hao** [open-iscsi/open-iscsi#286]
Step1: A server(192.168.1.2) deployed with ``` iqn.2003-01.org.linux-iscsi.localhost.first``` only
Step2: Client discovery ``` iqn.2003-01.org.linux-iscsi.localhost.first```  and make some changes of this node
Step3: Another ``` iqn.2003-01.org.linux-iscsi.localhost.second``` is deployed to the same portal(192.168.1.2)
Step4: Client perform discovery operation to portal 192.168.1.2

The previous discovered node's configure would be overrided to default value.

Is this reasonable? Shall we add another discover option to avoid overriding configure file?

```
root192@~:# iscsiadm -m node 
192.168.1.2:3260,1 iqn.2003-01.org.linux-iscsi.localhost.first
root192@~:# iscsiadm -m node -T iqn.2003-01.org.linux-iscsi.localhost.first -o update -n node.startup -v automatic
root192@~:# iscsiadm -m node -T iqn.2003-01.org.linux-iscsi.localhost.first | grep "node.startup"
node.startup = automatic
root192@~:# iscsiadm -m discovery -t st -p 192.168.1.2
192.168.1.2:3260,1 iqn.2003-01.org.linux-iscsi.localhost.first
192.168.1.2:3260,1 iqn.2003-01.org.linux-iscsi.localhost.second
root192@~:# iscsiadm -m node -T iqn.2003-01.org.linux-iscsi.localhost.first | grep "node.startup"
node.startup = manual
```

**Comment by gonzoleeman** [comment]
On Nov 15, 2021, at 7:49 PM, Wenchao Hao ***@***.***> wrote:
> 
> 
> Step1: A server(192.168.1.2) deployed with iqn.2003-01.org.linux-iscsi.localhost.first only
> Step2: Client discovery iqn.2003-01.org.linux-iscsi.localhost.first and make some changes of this node
> Step3: Another iqn.2003-01.org.linux-iscsi.localhost.second is deployed to the same portal(192.168.1.2)
> Step4: Client perform discovery operation to portal 192.168.1.2
> 
> The previous discovered node's configure would be overrided to default value.
> 
> Is this reasonable? Shall we add another discover option to avoid overriding configure file?
> 
> root192@~:# iscsiadm -m node 
> 192.168.1.2:3260,1 iqn.2003-01.org.linux-iscsi.localhost.first
> root192@~:# iscsiadm -m node -T iqn.2003-01.org.linux-iscsi.localhost.first -o update -n node.startup -v automatic
> root192@~:# iscsiadm -m node -T iqn.2003-01.org.linux-iscsi.localhost.first | grep "node.startup"
> node.startup = automatic
> root192@~:# iscsiadm -m discovery -t st -p 192.168.1.2
> 192.168.1.2:3260,1 iqn.2003-01.org.linux-iscsi.localhost.first
> 192.168.1.2:3260,1 iqn.2003-01.org.linux-iscsi.localhost.second
> root192@~:# iscsiadm -m node -T iqn.2003-01.org.linux-iscsi.localhost.first | grep "node.startup"
> node.startup = manual
> root192@~:# 
Iscsiadm is doing what you told it to do.

If you do not supply an “op” when doing discovery, it defaults to NEW | DELETE | UPDATE, i.e. it will create new nodes, it will update existing nodes, and it will delete nodes that are not discovered. The problem here is “update”, i.e. replace the existing DB entry to with what we discover and what is in the config file (in the case of node.startup).

You can pass in the “—op new” flag, if you wish, telling it to only add new nodes, but do not update existing nodes. Or you can change node.startup in the config file, so that all new nodes get the “onboot” value. Your choice.
-- 
Lee Duncan

"God is a comedian playing to an audience too afraid to laugh." -- Voltaire

**Comment by wenchao-hao** [comment]
> On Nov 15, 2021, at 7:49 PM, Wenchao Hao ***@***.***> wrote: Step1: A server(192.168.1.2) deployed with iqn.2003-01.org.linux-iscsi.localhost.first only Step2: Client discovery iqn.2003-01.org.linux-iscsi.localhost.first and make some changes of this node Step3: Another iqn.2003-01.org.linux-iscsi.localhost.second is deployed to the same portal(192.168.1.2) Step4: Client perform discovery operation to portal 192.168.1.2 The previous discovered node's configure would be overrided to default value. Is this reasonable? Shall we add another discover option to avoid overriding configure file? root192@~:# iscsiadm -m node 192.168.1.2:3260,1 iqn.2003-01.org.linux-iscsi.localhost.first root192@~:# iscsiadm -m node -T iqn.2003-01.org.linux-iscsi.localhost.first -o update -n node.startup -v automatic root192@~:# iscsiadm -m node -T iqn.2003-01.org.linux-iscsi.localhost.first | grep "node.startup" node.startup = automatic root192@~:# iscsiadm -m discovery -t st -p 192.168.1.2 192.168.1.2:3260,1 iqn.2003-01.org.linux-iscsi.localhost.first 192.168.1.2:3260,1 iqn.2003-01.org.linux-iscsi.localhost.second root192@~:# iscsiadm -m node -T iqn.2003-01.org.linux-iscsi.localhost.first | grep "node.startup" node.startup = manual root192@~:#
> Iscsiadm is doing what you told it to do. If you do not supply an “op” when doing discovery, it defaults to NEW | DELETE | UPDATE, i.e. it will create new nodes, it will update existing nodes, and it will delete nodes that are not discovered. The problem here is “update”, i.e. replace the existing DB entry to with what we discover and what is in the config file (in the case of node.startup). You can pass in the “—op new” flag, if you wish, telling it to only add new nodes, but do not update existing nodes. Or you can change node.startup in the config file, so that all new nodes get the “onboot” value. Your choice. -- Lee Duncan "God is a comedian playing to an audience too afraid to laugh." -- Voltaire

I did not notice this operation, thank you for your answer. I would close this issue
