### ISSUE TITLE
iscsid: Could not successful login iscsi target for a long time 

### ISSUE THREAD

**Issue by leymon** [open-iscsi/open-iscsi#294]
Hi,
   I tried to login iscsi target, but it failed for a long time. 
The logs iscsi target reported is:
![image](https://user-images.githubusercontent.com/8075059/145364086-6136d386-e6d7-484d-b789-7f8806cbe3f5.png)

and the log of iscsid and kernel reported is:
![image](https://user-images.githubusercontent.com/8075059/145366169-ebd63644-933f-4f91-93af-931bf28ae28a.png)

![image](https://user-images.githubusercontent.com/8075059/145365550-5d960c59-6809-401f-9d21-44b0b94f78aa.png)
the iscsid and kernel had reported this error log for 3 hours, and it still reported now, which result in iscsi initiator could not login iscsi 
target.

my environment is:
iscsi-initiator-utils-6.2.0.874-7.el7.x86_64
CentOS Linux release 7.5.1804

Thank you for your attention!

**Comment by gonzoleeman** [comment]
On Dec 9, 2021, at 1:06 AM, Chao ***@***.***> wrote:
> 
> 
> Hi,
> I tried to login iscsi target, but it failed for a long time.
> The logs iscsi target reported is:
>  <https://user-images.githubusercontent.com/8075059/145364086-6136d386-e6d7-484d-b789-7f8806cbe3f5.png>
> and the log of iscsid and kernel reported is:
>  <https://user-images.githubusercontent.com/8075059/145366169-ebd63644-933f-4f91-93af-931bf28ae28a.png>
> 
It looks like you have a name/password set on your targets(s)? The “Login authentication” message implies this.

What targets are you using? LIO/targetcli on Linux?
>  <https://user-images.githubusercontent.com/8075059/145365550-5d960c59-6809-401f-9d21-44b0b94f78aa.png>
> the iscsid and kernel had reported this error log for 3 hours, and it still reported now, which result in iscsi initiator could not login iscsi
> target.
> 
> my environment is:
> iscsi-initiator-utils-6.2.0.874-7.el7.x86_64
> CentOS Linux release 7.5.1804
> 
> Thank you for your attention!

**Comment by leymon** [comment]
Yes, the target has CHAP one-way authentication using name and password. The target is based on SPDK iscsi target on Linux.

> On Dec 9, 2021, at 1:06 AM, Chao ***@***.***> wrote: Hi, I tried to login iscsi target, but it failed for a long time. The logs iscsi target reported is: <https://user-images.githubusercontent.com/8075059/145364086-6136d386-e6d7-484d-b789-7f8806cbe3f5.png> and the log of iscsid and kernel reported is: <https://user-images.githubusercontent.com/8075059/145366169-ebd63644-933f-4f91-93af-931bf28ae28a.png>
> It looks like you have a name/password set on your targets(s)? The “Login authentication” message implies this. What targets are you using? LIO/targetcli on Linux?
> […](#)
> <https://user-images.githubusercontent.com/8075059/145365550-5d960c59-6809-401f-9d21-44b0b94f78aa.png> the iscsid and kernel had reported this error log for 3 hours, and it still reported now, which result in iscsi initiator could not login iscsi target. my environment is: iscsi-initiator-utils-6.2.0.874-7.el7.x86_64 CentOS Linux release 7.5.1804 Thank you for your attention!

**Comment by gonzoleeman** [comment]
On Dec 9, 2021, at 5:52 PM, Chao ***@***.***> wrote:
> 
> Yes, the target has CHAP one-way authentication using name and password. The target is based on SPDK iscsi target on Linux.
> 
> 
Ok, it seems that CHAP is not set up correctly. Make sure you have the same username and password on both sides. If you need help setting up CHAP for open-iscsi, the documentation should cover it.
> On Dec 9, 2021, at 1:06 AM, Chao @.***> wrote: Hi, I tried to login iscsi target, but it failed for a long time. The logs iscsi target reported is: https://user-images.githubusercontent.com/8075059/145364086-6136d386-e6d7-484d-b789-7f8806cbe3f5.png <https://user-images.githubusercontent.com/8075059/145364086-6136d386-e6d7-484d-b789-7f8806cbe3f5.png> and the log of iscsid and kernel reported is: https://user-images.githubusercontent.com/8075059/145366169-ebd63644-933f-4f91-93af-931bf28ae28a.png <https://user-images.githubusercontent.com/8075059/145366169-ebd63644-933f-4f91-93af-931bf28ae28a.png>
> It looks like you have a name/password set on your targets(s)? The “Login authentication” message implies this. What targets are you using? LIO/targetcli on Linux?
> … <x-msg://28/#>
> https://user-images.githubusercontent.com/8075059/145365550-5d960c59-6809-401f-9d21-44b0b94f78aa.png <https://user-images.githubusercontent.com/8075059/145365550-5d960c59-6809-401f-9d21-44b0b94f78aa.png> the iscsid and kernel had reported this error log for 3 hours, and it still reported now, which result in iscsi initiator could not login iscsi target. my environment is: iscsi-initiator-utils-6.2.0.874-7.el7.x86_64 CentOS Linux release 7.5.1804 Thank you for your attention!
> 

-- 
Lee Duncan

"Man is the center of a circle of infinite circumference." -- John Lilly

**Comment by leymon** [comment]
but，I have successed to login in target, 5 minutes before the problem reported . And the username and password had not changed since then.

**Comment by gonzoleeman** [comment]
On Dec 13, 2021, at 1:29 AM, Chao ***@***.***> wrote:
> 
> 
> but，I have successed to login in target, 5 minutes before the problem reported . And the username and password had not changed since then.
> 
> 

The data seems to say otherwise. There is an authentication error. That means the target did not like the username/password supplied. So either the initiator must have changed, or the target must have changed.

You can snoop the TCP/IP and use wireshark to look at the iSCSI traffic, if you wish. Or you could just check the initiator and target to make sure they still match?

— 
Lee

**Comment by gonzoleeman** [comment]
Any progress/update?

**Comment by gonzoleeman** [comment]
I'm going to close this if there is no response ...

**Comment by gonzoleeman** [comment]
No response for a year. Closing.
