### ISSUE TITLE
Shell we make sure the count of actually login session is equal to node.session.nr_sessions

### ISSUE THREAD

**Issue by wenchao-hao** [open-iscsi/open-iscsi#302]
A issue is found when node.session.nr_sessions is larger than 1, more sessions than node.session.nr_sessions would be created if login command is executed concurrently.

Like execute commands as following:

```
iscsiadm -m node -l &
iscsiadm -m node -l &
iscsiadm -m node -l &
iscsiadm -m node -l &
iscsiadm -m node -l &
```

nr_sessions was introduces in this commit: https://github.com/open-iscsi/open-iscsi/commit/6b13206f

It says at least nr_sessions sessions of session would created. What confused me is the name of this parameter which looks like specify the count of session.

**Comment by mikechristie** [comment]
I don't think we want to change it.

I think the original idea was that nr_sessions was not a hard limit on the number of sessions. In the git commit comment you will see it only says:

will ensure that at least that number of sessions are present for that recordr

So it was just a setting the user could set and tell the iscsi init code to create at least $nr_sessions at start up or whenever you ran the iscsiadm login command.

It was used for multipathing where a single session could not saturate the network link/port It's possible that we created nr_sessions initially then the user created additional sessions after that based on increased network resources. If we made nr_sessions a hard limit then this would break.

**Comment by gonzoleeman** [comment]
Part of the reason here, IMHO, that nr_sessions isn't followed exactly is that you are running logins in parallel. The open-iscsi code is not set up to handle that well. In addition, there is no reason to do that. You can use "iscsiadm -m node -l -W", which sends off login requests, as needed, but doesn't wait for the reply.

**Comment by wenchao-hao** [comment]
> I don't think we want to change it.
> 
> I think the original idea was that nr_sessions was not a hard limit on the number of sessions. In the git commit comment you will see it only says:
> 
> will ensure that at least that number of sessions are present for that recordr
> 

Got it. What confused me is the description of this parameter in iscsid.conf:

```
If node.session.nr_sessions is greater than 1, performing a 'login' for that node will ensure that the
appropriate number of sessions is created.
```

I think here should explains that nr_sessions is not hard limit of session numbers.

> So it was just a setting the user could set and tell the iscsi init code to create at least $nr_sessions at start up or whenever you ran the iscsiadm login command.
> 
> It was used for multipathing where a single session could not saturate the network link/port It's possible that we created nr_sessions initially then the user created additional sessions after that based on increased network resources. If we made nr_sessions a hard limit then this would break.

**Comment by wenchao-hao** [comment]
> Part of the reason here, IMHO, that nr_sessions isn't followed exactly is that you are running logins in parallel. The open-iscsi code is not set up to handle that well. In addition, there is no reason to do that. You can use "iscsiadm -m node -l -W", which sends off login requests, as needed, but doesn't wait for the reply.

Thanks for your reply, I understand the original intention of nr_sessions now.

**Comment by gonzoleeman** [comment]
Closing this issue, since it seems to be resolved.
