### ISSUE TITLE
No facility for session establishment on boot and ensuring session stays up through failures?

### ISSUE THREAD

**Issue by philipflesher** [open-iscsi/open-iscsi#304]
Apologies if this is a RTFM issue instead of a feature request.

Is there any way to ensure that a session will be retried forever? I'd like to start sessions if possible at boot, and then retry them forever if any failure occurs. This would include if the session drops at any point -- I need the session to be automatically retried until it's reestablished.

I see a lot of options for retrying up to certain limits, but no indication for infinite retries in the docs that I've read.

**Comment by gonzoleeman** [comment]
Are you talking initial login attempts, or session reestablishment?

For initial login, it looks like there is no way to retry forever. You can set a really high retry count and retry timeout, but you cannot set it to "retry forever".

Looking at the code, it also look like recovery_tmo cannot be set to "infinity".

In general, open-iscsi is not designed to lurk in the background and notice when a target becomes available. It assumes that if the target isn't available after a reasonable delay/timeout, then it's just not available.

The only case where open-iscsi can retry forever is on session re-establishment, i.e. when iscsid starts up and finds that sessions were present before, it can retry those forever, but that is the default (i.e. reopen_max=0).

**Comment by philipflesher** [comment]
@gonzoleeman thank you for the reply!

I am talking "session reestablishment" in the sense that, once configured and proven to be a working session at some point, the session will be reestablished indefinitely thereafter, through any interruptions of any length. That would include across reboots of course, but also any network interruptions.

I don't expect infinite retries on an initial session configuration, before the system has proven that it's possible to establish said connection. I do expect (or hope to be able to expect!) that once configured and proven to work, I can essentially forget about the connection thereafter and assume it will be kept alive for me.

What I have seen so far is that sessions are _not_ automatically reopened after a reboot if there's a failure on the initial attempt to reestablish the session. In my case, there are a couple of minutes or so after boot where the session isn't able to be established due to a networking delay.

You seem to be indicating to me that I should expect an infinite retry loop after a reboot provided reopen_max is set to 0. But I haven't touched that setting yet, and I don't seem to be getting the behavior I want.

**Comment by gonzoleeman** [comment]
> @gonzoleeman thank you for the reply!
> 
> I am talking "session reestablishment" in the sense that, once configured and proven to be a working session at some point, the session will be reestablished indefinitely thereafter, through any interruptions of any length. That would include across reboots of course, but also any network interruptions.

There are various mechanisms here, but I'm doubtful they will add up to your wish list.

There is the reopen_max config variable in iscsid.conf. Setting it to zero says "retry forever". That will handle the case when iscsid starts up and finds some session was present before and needs reestablishment.

There is also the replacement timeout. It controls how long we wait before failing IO and trying to reestablish the session.

If you want sessions to be established when you boot the system, you need to set startup to automatic in their node database entry and ensure that iscsi.service is enabled.

I would also suggest disabling NOPs, unless you want to discover temporary outages when they occur. Leaving them off would mean that a temporary outage would not effect you unless you were doing IO then.

> 
> I don't expect infinite retries on an initial session configuration, before the system has proven that it's possible to establish said connection. I do expect (or hope to be able to expect!) that once configured and proven to work, I can essentially forget about the connection thereafter and assume it will be kept alive for me.

Good, because it doesn't do that.

> 
> What I have seen so far is that sessions are _not_ automatically reopened after a reboot if there's a failure on the initial attempt to reestablish the session. In my case, there are a couple of minutes or so after boot where the session isn't able to be established due to a networking delay.

No, that's correct. Open-iscsi does not assume that the target will just magically start working, so it should keep trying forever.

> 
> You seem to be indicating to me that I should expect an infinite retry loop after a reboot provided reopen_max is set to 0. But I haven't touched that setting yet, and I don't seem to be getting the behavior I want.

Yes, if reopen_cnt is set to zero.

**Comment by mikechristie** [comment]
The problem is that after a reboot iscsid doesn't know that the login attempt is the first time it's being done or we had successfully logged in before. iscsid only knows if while it was running it has seen a successful login. We have a setting that almost does what you want. When you run iscsiadm ... login, the node.session.initial_login_retry_max setting controls how many times we retry.

I think a simple change could be to have node.session.initial_login_retry_max support a value that indicates infinite retries (-1). The user could set this after they have seen a successful login when they first set things up. On later reboots then when iscsid starts up, it will see that value and just not give up until the user runs the iscsiadm command to kill it.

There are a couple hiccups which are the reason infinite retries are not support:
1. If you have run iscsiadm ... login and it's still trying to do that login, then you can't kill the session. The code needs a somewhat simple fix.
2. You also have an issue where if that first login hits a long network issue then system start up might be blocked for a long time.

What you might want to do is just create a script/service that after/during boot checks the sessions that got created and if the node.startup value is set to automatic. If iscsiadm -m session doesn't report the session, then retry the iscsiadm login command for it.

**Comment by philipflesher** [comment]
Thanks, @mikechristie -- that all makes sense and matches the behavior I'm seeing.

I did what you've said already: wrote a script that attempts to re-establish sessions at all times if `-m session` doesn't return with a 0 exit code. I was just hoping that there was a way to avoid having this extra piece of custom automation. It sounds like the answer is, "not today."

I think it makes sense that all libraries that involve connections between systems that are expected to be up/down would be capable of retries/reconnects in a transparent way. That would certainly apply to open-iscsi as well! It feels to me that there should be no difference between a retry loop that happens at boot time and a retry loop that happens at any other time. Neither case should block anything (i.e., blocking shouldn't happen on boot if the net happens to be down, or the remote system isn't ready, or any other failure case). Rather, on boot, session re-enablement should be started, and then be allowed to run constantly in the background according to the settings for each session. That kind of pattern would fix your problem #2 as stated, right?

**Comment by gonzoleeman** [comment]
On Feb 25, 2022, at 9:10 AM, Philip Flesher ***@***.***> wrote:
> 
> 
> Thanks, @mikechristie <https://github.com/mikechristie> -- that all makes sense and matches the behavior I'm seeing.
> 
> I did what you've said already: wrote a script that attempts to re-establish sessions at all times if -m session doesn't return with a 0 exit code. I was just hoping that there was a way to avoid having this extra piece of custom automation. It sounds like the answer is, "not today."
> 
> I think it makes sense that all libraries that involve connections between systems that are expected to be up/down would be capable of retries/reconnects in a transparent way. That would certainly apply to open-iscsi as well! It feels to me that there should be no difference between a retry loop that happens at boot time and a retry loop that happens at any other time. Neither case should block anything (i.e., blocking shouldn't happen on boot if the net happens to be down, or the remote system isn't ready, or any other failure case). Rather, on boot, session re-enablement should be started, and then be allowed to run constantly in the background according to the settings for each session. That kind of pattern would fix your problem #2 <https://github.com/open-iscsi/open-iscsi/pull/2> as stated, right?
> 
> 


You want iscsid to work when the network is down?

I think of iscsi as more of a layered service. You don’t expect ftp or xterm to stay running if the remote system they’re connected to goes away. Or if it is not there at startup, to retry forever.

What if a target just goes away? Is iscsid supposed to keep retrying forever? What if there are a thousand targets that have went away? (Don’t laugh, some try to use iscsid that way.)

— 
Lee D

**Comment by philipflesher** [comment]
iscsid, the daemon? Yes, it should stay running and keep trying until the network comes back. That makes perfect sense to me -- is there a reason that doesn't make sense?

I agree iscsid is like a layered service. But it isn't like ftp or xterm. Those are clients that are not daemons. If it's a daemon, it should always be attempting to get itself into the desired state, within the configurable limits (which, by default, should be "keep trying at a reasonable frequency").

If a target goes away in the sense that the connection drops, the daemon should keep trying until it's instructed not to do so. A thousand targets -- sure, same thing. The scale isn't the question here. Note that if somebody has a thousand targets, and all are configured to be "kept alive" because they're important, then we can assume they have a system and network and what-not capable of handling those sessions and their associated retries. I'm not sure I understand why 1 session or 1M sessions makes a difference in terms of desired behavior.

Apologies if I am missing something about the design intent of open-iscsid! I am very new to this stack.

**Comment by gonzoleeman** [comment]
On Feb 25, 2022, at 10:09 AM, Philip Flesher ***@***.***> wrote:
> 
> 
> iscsid, the daemon? Yes, it should stay running and keep trying until the network comes back. That makes perfect sense to me -- is there a reason that doesn't make sense?
> 
> I agree iscsid is like a layered service. But it isn't like ftp or xterm. Those are clients that are not daemons. If it's a daemon, it should always be attempting to get itself into the desired state, within the configurable limits (which, by default, should be "keep trying at a reasonable frequency").
> 
> If a target goes away in the sense that the connection drops, the daemon should keep trying until it's instructed not to do so. A thousand targets -- sure, same thing. The scale isn't the question here. Note that if somebody has a thousand targets, and all are configured to be "kept alive" because they're important, then we can assume they have a system and network and what-not capable of handling those sessions and their associated retries. I'm not sure I understand why 1 session or 1M sessions makes a difference in terms of desired behavior.
> 
> Apologies if I am missing something about the design intent of open-iscsid! I am very new to this stack.
> 
> 

What you are missing is that open-iscsi doesn’t do this. It has never done this. As Mike mentioned (he’s much nicer than me), there are things that can be added that are reasonable, like handling “0” (or -1) as a “retry forever” option to some config variables.

I’d suggest you submit a pull request to show your proposed changes. Then we can look at if your suggested fix actually works and is not too complicated.

Or create/use a layer above iscsi that handles this (like multipathing)?
— 
Lee D

**Comment by philipflesher** [comment]
Hmm, okay, so before I go down that path further, and to clarify for my sake, please: is open-iscsi meant to be a single-shot initiator of sessions to a target, or a resilient daemon that manages session lifecycle in a robust (fault-tolerant) way? I had thought the latter, because there is an attempt to do some retry-forever logic in some cases (although not apparently across reboots). But if you told me that this is more of me trying to put a square peg in a round hole, and that I should instead be looking to a different system to do robust lifecycle management of sessions, that would also make sense to me and I would go that direction (not sure if that's multi-pathing in my case -- I have only a single path...).

I ask this because I don't want to try to push something into open-iscsi where it doesn't belong. I do understand already that the service has not ever done what I expected it to do. :)

**Comment by mikechristie** [comment]
> I think it makes sense that all libraries that involve connections between systems that are expected to be up/down would be capable of retries/reconnects in a transparent way. That would certainly apply to open-iscsi as well! It feels to me that there should be no difference between a retry loop that happens at boot time and a retry loop that happens at any other time. Neither case should block anything (i.e., blocking shouldn't happen on boot if the net happens to be down, or the remote system isn't ready, or any other failure case). Rather, on boot, session re-enablement should be started, and then be allowed to run constantly in the background according to the settings for each session. That kind of pattern would fix your problem number 2, right?

Yes.

If you set the systemd startup timeout to infinity and just do what we do today where we run the iscsiadm login command, will boot get stuck waiting? When I wrote my number 2 above, I was thinking you were doing that and I thought that would hang the boot.

Do you start your service so it starts (does not wait for the return value) the iscsiadm login commands in the background, and then report success to systemd? I think that is what you describe above and I think will work.

Maybe you want something else though. Have you seen the iscsid discoveryd feature? In this mode, iscsid does discovery every N seconds. Every target that it finds, it will log into if it there is no session already. In this case, as long as on the target side you are returning targets that you want the initiator to log into, then it should always login whenever it can finally login.

**Comment by gonzoleeman** [comment]
No reply for a year, so closing as inactive. I believe Mike (and I) answered your questions.
