### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by scaleoutsean** [open-iscsi/open-iscsi#306]
"do not has value" at https://github.com/open-iscsi/open-iscsi/blame/3f3f7a457d5d480636fddbddd35a9e9ed3cf6df5/usr/idbm.c#L1244

**Comment by gonzoleeman** [comment]
On Feb 19, 2022, at 10:10 PM, scaeloutSean ***@***.***> wrote:
> 
> 
> "do not has value" at https://github.com/open-iscsi/open-iscsi/blame/3f3f7a457d5d480636fddbddd35a9e9ed3cf6df5/usr/idbm.c#L1244 <https://github.com/open-iscsi/open-iscsi/blame/3f3f7a457d5d480636fddbddd35a9e9ed3cf6df5/usr/idbm.c#L1244>
> 

Submit a pull request to fix it?

— 
Lee Duncan
