### ISSUE TITLE
RFC: open-iscsi needs to move it's home from /etc/iscsi to ???

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/open-iscsi#308]
Hi All:

I knew this day was coming ... there's an effort in some places now to disable use of the /etc directory for most programs.

Certainly, having the iscsi database in /etc/iscsi goes against the intent of the "/etc" (configuration) directory.

Also, some edge-compute systems are moving towards read-only root, which means no open-iscsi.

I would like to solicit ideas on whether or not we should move /etc/iscsi, and if so, where to move it to.

I'm thinking this location could be a build variable, so that one could build open-iscsi for /etc/iscsi or /some/other/place.

The "other place" is the hard part. I can see moving the databases (node and send_target) to /usr/lib/iscsi_database or something similar. But I'm not sure the configuration file should be there nor the initiator name.

Right now, in /etc/iscsi, we have:

    lduncan@linux-s2(1):lduncan~> ls /etc/iscsi
    ./  ../  ifaces/  initiatorname.iscsi  iscsid.conf  lock  nodes/  send_targets/

Obviously, the "lock" file doesn't belong there. 

Thoughts? @cleech and @mikechristie  -- and anyone else!

**Comment by cleech** [comment]
Build time configuration sounds good.  Red Hat has patched to separate the record and lock files to /var/lib/iscsi while leaving iscsid.conf and initiatorname.iscsi in /etc/iscsi for a long while.

**Comment by gonzoleeman** [comment]
On Feb 24, 2022, at 1:12 PM, Chris Leech ***@***.***> wrote:
> 
> 
> Build time configuration sounds good. Red Hat has patched to separate the record and lock files to /var/lib/iscsi while leaving iscsid.conf and initiatorname.iscsi in /etc/iscsi for a long while.
> 
Where would you suggest (if anywhere) for the config files if they had to move from /etc/iscsi?

I’m thinking maybe two different build-time variables:

1. Config files (default to /etc/iscsi)

2. database files (default to /var/lib/iscsi)

— 
Lee

**Comment by gonzoleeman** [comment]
I'll submit a pull request soon to address this issue. It'll add two new top-level Makefile options for moving files.

It'll add "homedir=<SOMEDIR>" for moving iscsid.conf and initiatorname.iscsi.

It'll add "dbdir=<SOMEDIR>" for moving the databases and lock files.

Both will default to /etc/iscsi for now, but I'd like to move dbdir to /var/lib/iscsi some day soon? It may take longer to move homedir.

**Comment by gonzoleeman** [comment]
I have submitted pull request #325 that addresses this issue. It actually adds HOMEDIR= and DBROOT= options, i.e. the names are slightly different that I initially suggested.

**Comment by zeha** [comment]
Not sure if this is possible, but maybe the initiatorname wants to be derived from machine-id. At least when its not explicitly set. One less thing to worry about, especially on stateless setups.

**Comment by zeha** [comment]
And, re iscsid.conf: I think software supporting stateless systems is moving towards "defaults are compiled in, no config file needed". So maybe /etc/iscsi is fine for iscsid.conf, but normally you wouldn't have the file installed, because iscsid/iscsiadm have the correct defaults for the distribution.

**Comment by gonzoleeman** [comment]
> Not sure if this is possible, but maybe the initiatorname wants to be derived from machine-id. At least when its not explicitly set. One less thing to worry about, especially on stateless setups.

I'm not sure what you're talking about here. I'm not aware of any issue with the initiatorname.

Currently, there are several ways it can be set, and all of them involve having a unique initiatorname on each system. So there is no need to derive it from machine ID. What value would that add.

Currently, for SUSE, we set the initiatorname during install, using this in %post:

```
if [ ! -f %{_sysconfdir}/iscsi/initiatorname.iscsi ] ; then
    %{_sbindir}/iscsi-gen-initiatorname
fi
```
From the iscsi-gen-initiatorname(8) man page:

> The Initiator Name will be taken from the kernel command line, if present  (from  the  rd.initiatorname  parameter),
> else from the iBFT subsystem (if present in sysfs), else it will be generated using the iscsi-iname command.

**Comment by gonzoleeman** [comment]
> And, re iscsid.conf: I think software supporting stateless systems is moving towards "defaults are compiled in, no config file needed". So maybe /etc/iscsi is fine for iscsid.conf, but normally you wouldn't have the file installed, because iscsid/iscsiadm have the correct defaults for the distribution.

The config file is only needed for open-iscsi if you want to tune things. The default values, listed in iscsid.conf, are already compiled in. Still, I'm not sure what iscsid/iscsiadm would do if the file was missing. It should probably be a warning.

The open-iscsi code is anything but stateless. IO is not stateless. It's all about state.

**Comment by gonzoleeman** [comment]
I believe I'm going to close this issue, for now. I have updated the build system such that the iscsi config files and database files can each separately be configured to different locations.
