### ISSUE TITLE
lun not attached if no luns during target login

### ISSUE THREAD

**Issue by slesru** [open-iscsi/open-iscsi#31]
[root@blocksync bin]# iscsiadm -m session --rescan
Rescanning session [sid: 1, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.224.184,3260]
Rescanning session [sid: 2, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.224.185,3260]
Rescanning session [sid: 3, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.223.184,3260]
Rescanning session [sid: 4, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.223.185,3260]
Rescanning session [sid: 5, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.223.132,3260]
Rescanning session [sid: 6, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.224.132,3260]
Rescanning session [sid: 7, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.224.131,3260]
Rescanning session [sid: 8, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.223.131,3260]
[root@blocksync bin]# 

mpatha (may be other letter) should be here ,but no...

[root@blocksync bin]# multipath -ll
mpathinetgw2 (3600c0ff00026940805c1005801000000) dm-1 HP      ,MSA 2040 SAN  
size=300G features='1 queue_if_no_path' hwhandler='0' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 7:0:0:1 sdf 8:80  active ready running
| `- 6:0:0:1 sdd 8:48  active ready running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 8:0:0:1 sde 8:64  active ready running
  `- 9:0:0:1 sdn 8:208 active ready running
mpathinetgw1 (3600c0ff00026940808c1005801000000) dm-2 HP      ,MSA 2040 SAN    
size=300G features='1 queue_if_no_path' hwhandler='0' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 6:0:0:2 sdg 8:96  active ready running
|`\- 7:0:0:2 sdi 8:128 active ready running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 8:0:0:2 sdh 8:112 active ready running
`\- 9:0:0:2 sdo 8:224 active ready running
mpathinetgw1inetgw2 (3600c0ff0002694081dc1005801000000) dm-3 HP      ,MSA 2040 SAN  
size=150G features='1 queue_if_no_path' hwhandler='0' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 7:0:0:3 sdl 8:176 active ready running
| `- 6:0:0:3 sdj 8:144 active ready running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 8:0:0:3 sdk 8:160 active ready running
  `- 9:0:0:3 sdp 8:240 active ready running
mpathzabbixroot (3600c0ff000269408711efd5701000000) dm-0 HP      ,MSA 2040 SAN    
size=200G features='1 queue_if_no_path' hwhandler='0' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 6:0:0:0 sda 8:0   active ready running
|`\- 7:0:0:0 sdb 8:16  active ready running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 8:0:0:0 sdc 8:32  active ready running
`\- 9:0:0:0 sdm 8:192 active ready running
[root@blocksync bin]# 

reloging helps:

[root@blocksync bin]# ./iscsi-logoff
Logging out of session [sid: 1, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.224.184,3260]
Logging out of session [sid: 2, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.224.185,3260]
Logging out of session [sid: 3, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.223.184,3260]
Logging out of session [sid: 4, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.223.185,3260]
Logging out of session [sid: 5, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.223.132,3260]
Logging out of session [sid: 6, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.224.132,3260]
Logging out of session [sid: 7, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.224.131,3260]
Logging out of session [sid: 8, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.223.131,3260]
Logout of [sid: 1, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.224.184,3260] successful.
Logout of [sid: 2, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.224.185,3260] successful.
Logout of [sid: 3, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.223.184,3260] successful.
Logout of [sid: 4, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.223.185,3260] successful.
Logout of [sid: 5, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.223.132,3260] successful.
Logout of [sid: 6, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.224.132,3260] successful.
Logout of [sid: 7, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.224.131,3260] successful.
Logout of [sid: 8, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.223.131,3260] successful.

[root@blocksync bin]# ./iscsi-login
Logging in to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.223.184,3260](multiple)
Login to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.223.184,3260] successful.
Logging in to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.223.185,3260](multiple)
Login to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.223.185,3260] successful.
Logging in to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.224.184,3260](multiple)
Login to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.224.184,3260] successful.
Logging in to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.224.185,3260](multiple)
Login to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268533, portal: 192.168.224.185,3260] successful.
Logging in to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.223.131,3260](multiple)
Login to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.223.131,3260] successful.
Logging in to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.223.132,3260](multiple)
Login to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.223.132,3260] successful.
Logging in to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.224.131,3260](multiple)
Login to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.224.131,3260] successful.
Logging in to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.224.132,3260](multiple)
Login to [iface: default, target: iqn.1986-03.com.hp:storage.msa2040.1533268539, portal: 192.168.224.132,3260] successful.

[root@blocksync bin]# multipath -ll
mpathe (3600c0ff000267d5355e8055801000000) dm-0 HP      ,MSA 2040 SAN  
size=200G features='1 queue_if_no_path' hwhandler='0' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 2:0:0:0 sda 8:0   active ready running
| `- 4:0:0:0 sdc 8:32  active ready running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 3:0:0:0 sdb 8:16  active ready running
  `- 5:0:0:0 sdd 8:48  active ready running

This happens not every time, though.
If lun from target presents during login, then looks like new luns are recognized OK.
Linux 4.8.1.

**Comment by slesru** [comment]
what is more interesting here- is low read ( may be write performance) on first lun , discovered after such logoff/logon...

workaround is to have at least one mapped lun.
but... why?

Thank you!

**Comment by gonzoleeman** [comment]
If the LUN is not present when you first connect to the target then how do you expect open-iscsi to detect it when it appears?

**Comment by mikechristie** [comment]
The iscsiadm rescan command they ran is supposed to pick up new LUNs or if the target sends a iSCSI SCSI async PDU then iscsid would rescan for you.

Because it is LUN0, it is probably a BLIST_* issue or some issue with how the scsi layer or target is handling/sending wlun or PQ/PDT values.

**Comment by slesru** [comment]
By rescan :-)
 

    On Friday, November 4, 2016 4:19 AM, mikechristie <notifications@github.com> wrote:
 

 The iscsiadm rescan command they ran is supposed to pick up new LUNs or if the target sends a iSCSI SCSI async PDU then iscsid would rescan for you.Because it is LUN0, it is probably a BLIST_* issue or some issue with how the scsi layer or target is handling/sending wlun or PQ/PDT values.—

**Comment by cleech** [comment]
Thanks for the ideas Mike.  I'm trying to figure out what would help debug this.

A network trace during the failed rescan, assuming it manages to generate any traffic at all.

Maybe a kernel function trace to see where the execution gets to?  Something like the output of:
# trace-cmd record -p function_graph -g store_scan iscsiadm -m session --rescan
# trace-cmd report

**Comment by gonzoleeman** [comment]
I'm trying to clean up old issues. Is this still relevant?

**Comment by slesru** [comment]
I'll try to reproduce this at Monday using latest centos kernel-ml and inform you.

**Comment by slesru** [comment]
Hello! 
quick test shows everything is fine using kernel 4.14.2.
Could you, please, wait until tomorrow- I'll do backup using this next night and , thus, will be sure it is fixed, before closing this issue?  Thank you!

**Comment by slesru** [comment]
Hello!

night backup looks good, i.e. looks like issue is fixed.

Thank you!

**Comment by gonzoleeman** [comment]
Cool that all is working now, so closing this issue, as suggested.
