### ISSUE TITLE
Failed to run make in usr subdirectories

### ISSUE THREAD

**Issue by wenchao-hao** [open-iscsi/open-iscsi#327]
I found a small issue, we would fail to run make in usr subdirectories before running make in libopeniscsiusr, utils/sysdeps and utils/fwparam_ibft. The root reason is that programs in usr subdirectories depends on object files in other directories.

**Comment by gonzoleeman** [comment]
I think this pull request of mine addresses your issue in a reasonable way. Now, in a clean tree, "make" in "usr" will succeed.

I believe we can close this issue once that pull request is merged.

**Comment by gonzoleeman** [comment]
Marking as closed. Thank you for your issue and the review.
