### ISSUE TITLE
Tag New Release? (April 2022)

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/open-iscsi#329]
I would like to tag yet another release -- it makes it a bit easier to update my distro when there is a new version number.

Any objections? Anyone want to add any changes first?

@cleech @mikechristie @wenchao-hao ??

Anyone else?

**Comment by wenchao-hao** [comment]
What about waitting #312 closed?

**Comment by wenchao-hao** [comment]
> What about waitting #312 closed?

@gonzoleeman Hi, Lee, it seems would take some time to finish(I ran pressure test and found a NULL pointer reference in kernel space which can be recurrent both with code before and after my changes. I did not address it yet, I would post the stack to mail list tomorrow). If you want to tag a release, do not wait it.

**Comment by gonzoleeman** [comment]
@wenchao-hao   I'm kind of holding of for now, in hopes that fixes from Mike here get finalized.

**Comment by gonzoleeman** [comment]
Tagged release 2.1.7. Closing this issue.
