### ISSUE TITLE
centos7 iscsi is adding ipv6 nodes on ipv4 only system

### ISSUE THREAD

**Issue by devZer0** [open-iscsi/open-iscsi#33]
i have had some boot problems on centos 7 host

apparently when doing iscsisadmin discovery, the following is being added to /var and prevented proper automatic start on boot, as ipv6 is firewalled within our network. iscsi service hung forever on boot, as there also was no timeout defined in systemd configuration

./lib/iscsi/nodes
./lib/iscsi/nodes/iqn.2000-01.com.synology:DiskStation4.Target-1.3ea3d7a31e
./lib/iscsi/nodes/iqn.2000-01.com.synology:DiskStation4.Target-1.3ea3d7a31e/192.168.1.87,3260,1
./lib/iscsi/nodes/iqn.2000-01.com.synology:DiskStation4.Target-1.3ea3d7a31e/192.168.1.87,3260,1/default
./lib/iscsi/nodes/iqn.2000-01.com.synology:DiskStation4.Target-1.3ea3d7a31e/fe80::211:32ff:fe0c:d12,3260,1
./lib/iscsi/nodes/iqn.2000-01.com.synology:DiskStation4.Target-1.3ea3d7a31e/fe80::211:32ff:fe0c:d12,3260,1/default
./lib/iscsi/nodes/iqn.2000-01.com.synology:DiskStation4.Target-11.3ea3d7a31e
./lib/iscsi/nodes/iqn.2000-01.com.synology:DiskStation4.Target-11.3ea3d7a31e/192.168.1.87,3260,1
./lib/iscsi/nodes/iqn.2000-01.com.synology:DiskStation4.Target-11.3ea3d7a31e/192.168.1.87,3260,1/default
./lib/iscsi/nodes/iqn.2000-01.com.synology:DiskStation4.Target-11.3ea3d7a31e/fe80::211:32ff:fe0c:d12,3260,1
./lib/iscsi/nodes/iqn.2000-01.com.synology:DiskStation4.Target-11.3ea3d7a31e/fe80::211:32ff:fe0c:d12,3260,1/default
./lib/iscsi/send_targets
./lib/iscsi/send_targets/192.168.1.87,3260
./lib/iscsi/send_targets/192.168.1.87,3260/st_config
./lib/iscsi/send_targets/192.168.1.87,3260/iqn.2000-01.com.synology:DiskStation4.Target-1.3ea3d7a31e,192.168.1.87,3260,1,default
./lib/iscsi/send_targets/192.168.1.87,3260/iqn.2000-01.com.synology:DiskStation4.Target-1.3ea3d7a31e,fe80::211:32ff:fe0c:d12,3260,1,default
./lib/iscsi/send_targets/192.168.1.87,3260/iqn.2000-01.com.synology:DiskStation4.Target-11.3ea3d7a31e,192.168.1.87,3260,1,default
./lib/iscsi/send_targets/192.168.1.87,3260/iqn.2000-01.com.synology:DiskStation4.Target-11.3ea3d7a31e,fe80::211:32ff:fe0c:d12,3260,1,default

manually removing the ipv6 entries from filesystem fixed the problem, reboot works now

i`m curious why iscsi is adding ipv6 information when i even disabled ipv6 on the initiator host (don`t know how to disable on synology nas)

i`m missing at least a configuration switch in iscsd.conf to disable ipv6 

in manpage from iscsiadm, i found --portal_type option which looks i can force ipv4 with that - but it doesn`t work on centos7

# iscsiadm -m discovery -t sendtargets -p 192.168.1.87:3260 --portal_type=ipv4
iscsiadm: discovery mode: option '-A' is not allowed/supported

# iscsiadm -m node -T iqn.2000-01.com.synology:DiskStation4.Target-1.3ea3d7a31e -p 192.168.1.87 -A ipv4 --login
iscsiadm: node mode: option '-A' is not allowed/supported

# iscsiadm -m node -T iqn.2000-01.com.synology:DiskStation4.Target-1.3ea3d7a31e -p 192.168.1.87 --portal_type=ipv4 --login
iscsiadm: node mode: option '-A' is not allowed/supported

i`m asking here because i`m unsure if this is a centos or upstream issue

**Comment by gonzoleeman** [comment]
My first response is that the target is the problem. The protocol sets forth the sequence: We ask the target portal to send a list of targets, with their IQNs. There is no protocol for telling a target portal you just want a subset of it's LUNs. But that's just my first response ...

**Comment by cleech** [comment]
Lee's right that there's no way to request a subset of portals during sendtargets discovery, so the options are to either remove the IPv6 portals from the target if IPv6 is not allowed in your network or do some sort of post filtering on the initiator.  Deleting the records is fine, as would be disabling automatic startup for them by switching them to manual.

The man page states that the -A/--portal_type option is specific to flashnode new commands, but something like that for selecting records for update or delete could be nice.  We don't have that now.

Improved handling of connection errors and timeouts would be nice as well, but I've heard opinions go both ways (don't ever give up completely vs. time out faster) depending on use case.

You should be able to adjust the default initial_login_retry_max and login_timeout settings in /etc/iscsi/iscsid.conf down to give up on the IPv6 portals much faster.

**Comment by devZer0** [comment]
yes, instead of removing the ipv6 entries in the filesystem, changing 

/var/lib/iscsi/nodes/iqn.2000-01.com.synology\:DiskStation4.Target-1.3ea3d7a31e/fe80\:\:211\:32ff\:fe0c\:d12\,3260\,1/default )

entry 

node.startup = automatic

into 

node.startup = manual 

also fixes the problem for me.
