### ISSUE TITLE
Failed to link iscsiuio during build

### ISSUE THREAD

**Issue by wenchao-hao** [open-iscsi/open-iscsi#337]
commit 9fbd6009cd917f1152a367fa7e5ae3993133c1e4 changed the Makefile.am
It's ok with fedora, while for my old version distro the building failed. It seems iscsiuio_LIBS did not work

```
ps.c' || echo './'`../../../utils/sysdeps/sysdeps.c
mv -f .deps/iscsiuio-packet.Tpo .deps/iscsiuio-packet.Po
mv -f .deps/iscsiuio-main.Tpo .deps/iscsiuio-main.Po
mv -f .deps/iscsiuio-sysdeps.Tpo .deps/iscsiuio-sysdeps.Po
mv -f .deps/iscsiuio-nic_nl.Tpo .deps/iscsiuio-nic_nl.Po
mv -f .deps/iscsiuio-ping.Tpo .deps/iscsiuio-ping.Po
mv -f .deps/iscsiuio-nic.Tpo .deps/iscsiuio-nic.Po
mv -f .deps/iscsiuio-nic_utils.Tpo .deps/iscsiuio-nic_utils.Po
mv -f .deps/iscsiuio-iscsid_ipc.Tpo .deps/iscsiuio-iscsid_ipc.Po
/bin/sh ../../libtool  --tag=CC   --mode=link gcc -I../../src/uip -I../../src/apps/brcm-iscsi -I../../src/apps/dhcpc -I../../src/unix/libs -I../../../include -I../../../usr  -DBYTE_ORDER=LITTLE -g -O2 -Wall   -o iscsiuio iscsiuio-build_date.o iscsiuio-main.o iscsiuio-clock-arch.o iscsiuio-logger.o iscsiuio-nic.o iscsiuio-nic_id.o iscsiuio-nic_vlan.o iscsiuio-nic_nl.o iscsiuio-nic_utils.o iscsiuio-packet.o iscsiuio-iscsid_ipc.o iscsiuio-ping.o iscsiuio-sysdeps.o  ../../src/uip/lib_iscsi_uip.a ../../src/apps/dhcpc/lib_apps_dhcpc.a ../../src/apps/brcm-iscsi/lib_apps_brcm_iscsi.a ../../src/unix/libs/lib_iscsiuio_hw_cnic.a -lsystemd 
libtool: link: gcc -I../../src/uip -I../../src/apps/brcm-iscsi -I../../src/apps/dhcpc -I../../src/unix/libs -I../../../include -I../../../usr -DBYTE_ORDER=LITTLE -g -O2 -Wall -o iscsiuio iscsiuio-build_date.o iscsiuio-main.o iscsiuio-clock-arch.o iscsiuio-logger.o iscsiuio-nic.o iscsiuio-nic_id.o iscsiuio-nic_vlan.o iscsiuio-nic_nl.o iscsiuio-nic_utils.o iscsiuio-packet.o iscsiuio-iscsid_ipc.o iscsiuio-ping.o iscsiuio-sysdeps.o  ../../src/uip/lib_iscsi_uip.a ../../src/apps/dhcpc/lib_apps_dhcpc.a ../../src/apps/brcm-iscsi/lib_apps_brcm_iscsi.a ../../src/unix/libs/lib_iscsiuio_hw_cnic.a -lsystemd
/usr/bin/ld: iscsiuio-iscsid_ipc.o: undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:483: iscsiuio] Error 1
make[5]: Leaving directory '/root/open-iscsi/iscsiuio/src/unix'
make[4]: *** [Makefile:727: all-recursive] Error 1
make[4]: Leaving directory '/root/open-iscsi/iscsiuio/src/unix'
make[3]: *** [Makefile:351: all-recursive] Error 1
make[3]: Leaving directory '/root/open-iscsi/iscsiuio/src'
make[2]: *** [Makefile:400: all-recursive] Error 1
make[2]: Leaving directory '/root/open-iscsi/iscsiuio'
make[1]: *** [Makefile:332: all] Error 2
make[1]: Leaving directory '/root/open-iscsi/iscsiuio'
make: *** [Makefile:58: user] Error 2
```

**Comment by gonzoleeman** [comment]
The change you mention only changed (1) make depend target, and (2) changed "rm -f" to "$(RM)".

There are no changes to iscsiuio/Makefile.am that should effect this.

It looks like whatever old system you have doesn't have pthread_join() available in the standard places. I'm guessing  autoconf/automake (used by iscsiuio)  is the problem, as that is supposed to add "-pthread" for some OSes and not others? (I'm not automate exert).

Can you try just manually updating the Makefile to add "-pthread" here, as a test?

What OS/release is this? If it's not too hard to find/get I can try this myself.

But, again, I can't see how this would be related to any changes recently made to the build system.

**Comment by wenchao-hao** [comment]
> The change you mention only changed (1) make depend target, and (2) changed "rm -f" to "$(RM)".
> 
> There are no changes to iscsiuio/Makefile.am that should effect this.
> 

Sorry, it's this commit: https://github.com/open-iscsi/open-iscsi/commit/9fbd6009cd917f1152a367fa7e5ae3993133c1e4

> It looks like whatever old system you have doesn't have pthread_join() available in the standard places. I'm guessing autoconf/automake (used by iscsiuio) is the problem, as that is supposed to add "-pthread" for some OSes and not others? (I'm not automate exert).
> 
> Can you try just manually updating the Makefile to add "-pthread" here, as a test?

It's ok to add -pthread manually in generated Makefile, while iscsiuio's Makefile is generated automaticly, we need a way to add it.

> 
> What OS/release is this? If it's not too hard to find/get I can try this myself.
> 
> But, again, I can't see how this would be related to any changes recently made to the build system.

It's not caused by your changes.

**Comment by gonzoleeman** [comment]
> > The change you mention only changed (1) make depend target, and (2) changed "rm -f" to "$(RM)".
> > There are no changes to iscsiuio/Makefile.am that should effect this.
> 
> Sorry, it's this commit: [9fbd600](https://github.com/open-iscsi/open-iscsi/commit/9fbd6009cd917f1152a367fa7e5ae3993133c1e4)

Okay, got it. That doesn't look like it should cause an issue. Can you try reverting it and see if your issue goes away? That would save me from having to download then configure a new OS. :)

> 
> > It looks like whatever old system you have doesn't have pthread_join() available in the standard places. I'm guessing autoconf/automake (used by iscsiuio) is the problem, as that is supposed to add "-pthread" for some OSes and not others? (I'm not automate exert).
> > Can you try just manually updating the Makefile to add "-pthread" here, as a test?
> 
> It's ok to add -pthread manually in generated Makefile, while iscsiuio's Makefile is generated automaticly, we need a way to add it.

Yes, I meant would you try this, to see if it fixes the issue. Not as a permanent fix.

I believe the problem is in autoconf/automake and/or the way it's being used, particularly after this update. What the update _should_ have done is add some more (default) link flags, so that may be the issue.

Please capture the full output from top-level make for both before and after this revert, so I can see what linker flags are being changed. I'm perfectly happy to revert this change, at least for now, if it fixes your problem (since others may have the same problem).


> 
> > What OS/release is this? If it's not too hard to find/get I can try this myself.
> 
> You can build it with centos7 which would failed.
> 
> > But, again, I can't see how this would be related to any changes recently made to the build system.
> 
> It's not caused by your changes.

Okay, that's good, but we still have to figure out the issue.

Thanks!

**Comment by gonzoleeman** [comment]
@thesamesam ping? This issue is with your commit:

    9fbd6009cd91 iscsiuio: respect LDFLAGS fully

**Comment by thesamesam** [comment]
I'll take a look shortly!

**Comment by thesamesam** [comment]
@wenchao-hao Can you try https://github.com/open-iscsi/open-iscsi/pull/341 for me? If it fails, can you share the full log (from `./configure ; make clean ; make`)?

**Comment by wenchao-hao** [comment]
> > > The change you mention only changed (1) make depend target, and (2) changed "rm -f" to "$(RM)".
> > > There are no changes to iscsiuio/Makefile.am that should effect this.
> > 
> > 
> > Sorry, it's this commit: [9fbd600](https://github.com/open-iscsi/open-iscsi/commit/9fbd6009cd917f1152a367fa7e5ae3993133c1e4)
> 
> Okay, got it. That doesn't look like it should cause an issue. Can you try reverting it and see if your issue goes away? That would save me from having to download then configure a new OS. :)

Build failed with opensuse too, here is details of distro:

```
root@suse ~/open-iscsi:# hostnamectl status 
   Static hostname: suse
         Icon name: computer-vm
           Chassis: vm
        Machine ID: aea82330b84549878c3b0d91dd937403
           Boot ID: 0c88649d905a471d83e4aa8518b4c45d
    Virtualization: kvm
  Operating System: openSUSE Leap 15.3
       CPE OS Name: cpe:/o:opensuse:leap:15.3
            Kernel: Linux 5.3.18-150300.59.60-default
      Architecture: x86-64
```

> 
> > > It looks like whatever old system you have doesn't have pthread_join() available in the standard places. I'm guessing autoconf/automake (used by iscsiuio) is the problem, as that is supposed to add "-pthread" for some OSes and not others? (I'm not automate exert).
> > > Can you try just manually updating the Makefile to add "-pthread" here, as a test?
> > 
> > 
> > It's ok to add -pthread manually in generated Makefile, while iscsiuio's Makefile is generated automaticly, we need a way to add it.
> 
> Yes, I meant would you try this, to see if it fixes the issue. Not as a permanent fix.
> 
> I believe the problem is in autoconf/automake and/or the way it's being used, particularly after this update. What the update _should_ have done is add some more (default) link flags, so that may be the issue.
> 
> Please capture the full output from top-level make for both before and after this revert, so I can see what linker flags are being changed. I'm perfectly happy to revert this change, at least for now, if it fixes your problem (since others may have the same problem).

The full log is too long to add it here.

> 
> > > What OS/release is this? If it's not too hard to find/get I can try this myself.
> > 
> > 
> > You can build it with centos7 which would failed.
> > > But, again, I can't see how this would be related to any changes recently made to the build system.
> > 
> > 
> > It's not caused by your changes.
> 
> Okay, that's good, but we still have to figure out the issue.
> 
> Thanks!

**Comment by wenchao-hao** [comment]
> > > The change you mention only changed (1) make depend target, and (2) changed "rm -f" to "$(RM)".
> > > There are no changes to iscsiuio/Makefile.am that should effect this.
> > 
> > 
> > Sorry, it's this commit: [9fbd600](https://github.com/open-iscsi/open-iscsi/commit/9fbd6009cd917f1152a367fa7e5ae3993133c1e4)
> 
> Okay, got it. That doesn't look like it should cause an issue. Can you try reverting it and see if your issue goes away? That would save me from having to download then configure a new OS. :)

Build failed with opensuse too, here is details of distro:

```
root@suse ~/open-iscsi:# hostnamectl status 
   Static hostname: suse
         Icon name: computer-vm
           Chassis: vm
        Machine ID: aea82330b84549878c3b0d91dd937403
           Boot ID: 0c88649d905a471d83e4aa8518b4c45d
    Virtualization: kvm
  Operating System: openSUSE Leap 15.3
       CPE OS Name: cpe:/o:opensuse:leap:15.3
            Kernel: Linux 5.3.18-150300.59.60-default
      Architecture: x86-64
```

> 
> > > It looks like whatever old system you have doesn't have pthread_join() available in the standard places. I'm guessing autoconf/automake (used by iscsiuio) is the problem, as that is supposed to add "-pthread" for some OSes and not others? (I'm not automate exert).
> > > Can you try just manually updating the Makefile to add "-pthread" here, as a test?
> > 
> > 
> > It's ok to add -pthread manually in generated Makefile, while iscsiuio's Makefile is generated automaticly, we need a way to add it.
> 
> Yes, I meant would you try this, to see if it fixes the issue. Not as a permanent fix.
> 
> I believe the problem is in autoconf/automake and/or the way it's being used, particularly after this update. What the update _should_ have done is add some more (default) link flags, so that may be the issue.
> 
> Please capture the full output from top-level make for both before and after this revert, so I can see what linker flags are being changed. I'm perfectly happy to revert this change, at least for now, if it fixes your problem (since others may have the same problem).

The full log is too long to add it here.

> 
> > > What OS/release is this? If it's not too hard to find/get I can try this myself.
> > 
> > 
> > You can build it with centos7 which would failed.
> > > But, again, I can't see how this would be related to any changes recently made to the build system.
> > 
> > 
> > It's not caused by your changes.
> 
> Okay, that's good, but we still have to figure out the issue.
> 
> Thanks!

**Comment by wenchao-hao** [comment]
> @wenchao-hao Can you try #341 for me? If it fails, can you share the full log (from `./configure ; make clean ; make`)?

I woud try it later, and you can test it with opensuse too.

```
root@suse ~/open-iscsi:# hostnamectl status 
   Static hostname: suse
         Icon name: computer-vm
           Chassis: vm
        Machine ID: aea82330b84549878c3b0d91dd937403
           Boot ID: 0c88649d905a471d83e4aa8518b4c45d
    Virtualization: kvm
  Operating System: openSUSE Leap 15.3
       CPE OS Name: cpe:/o:opensuse:leap:15.3
            Kernel: Linux 5.3.18-150300.59.60-default
      Architecture: x86-64
```

**Comment by wenchao-hao** [comment]
> @wenchao-hao Can you try #341 for me? If it fails, can you share the full log (from `./configure ; make clean ; make`)?

I test it with centos8 and openSUSE Leap 15.3, fedora35, all build ok. But have some questions about your changes which I left in your PR.
