### ISSUE TITLE
Format-overflow issue

### ISSUE THREAD

**Issue by shugaley** [open-iscsi/open-iscsi#355]
I have built with `gcc-11.3` with:

```bash
-O2 -fwrapv-pointer
```

and got an error:

```bash
In function 'ipaddr_is_ipv6',
    inlined from 'iface_setup_from_boot_context.part.0' at iface.c:1106:4:
iface.c:1017:9: error: '%s' directive argument is null [-Werror=format-overflow=]
 1017 |         log_debug(8, "%s(%s) -> %u",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1018 |                 __FUNCTION__, ipaddr, res);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

See code:
https://github.com/open-iscsi/open-iscsi/blob/c2e4320dd5f605924082da1d9b33326c805a431e/usr/iface.c#L1003-L1020
https://github.com/open-iscsi/open-iscsi/blob/c2e4320dd5f605924082da1d9b33326c805a431e/usr/log.h#L80-L81

It seems a legitimate warning, because the previos check for null means that `ipaddr` may be a null pointer here. Passing a null pointer to the `log_debug` function (with an attribute `(format (printf, 2, 3))`) is detected here by format-overflow warning. I also checked `log_debug` function and didn't find any argument checks.

**Comment by gonzoleeman** [comment]
Please feel free to submit a pull request to fix this. I'd suggest moving the log message inside the "if", and adding a different log message if the pointer is null (which shouldn't of course happen).
