### ISSUE TITLE
Add more options for iscsi and isns

### ISSUE THREAD

**Issue by tianyuanhao** [open-iscsi/open-iscsi#373]
Many Linux distributions split `iscsi` and `isns` into multiple packages. For example `libisns0`, `open-isns-server`, `open-iscsi`, `iscsiuio`, etc.

Recently I was trying to add `open-iscsi` support to [`Buildroot`](https://github.com/buildroot/buildroot), I split `iscsi` and `isns` in the form of these two patches [[1]](http://patchwork.ozlabs.org/project/buildroot/patch/20220913070008.1036079-1-tianyuanhao3@163.com/) [[2]](http://patchwork.ozlabs.org/project/buildroot/patch/20220926154320.35494-1-tianyuanhao3@163.com/).

However @tpetazzoni pointed out that we should provide more options in `meson.build` to achieve the above.

**Comment by gonzoleeman** [comment]
open-isns is already a separate package. I’m not sure what you mean by “split”.

**Comment by tianyuanhao** [comment]
@gonzoleeman

For `isns`, we should add options to disable compiling `isns*` to only compile `libisns.so`.

For `iscsi`. We can add options that only compile `iscsistart`. In this case, we do not rely on `libisns`. We can add options to allow the compilation of `iscsi{d,adm,-iname}` and related `systemd` units. At this time, we will get a minimal `iscsi` toolset. We can add options to allow the compilation of `iscsiuio`. Finally, we can add options to compile and install all other stuff.

**Comment by eli-schwartz** [comment]
Is this a case where you want to offer the ability to only compile one, or where you want to conveniently offer the ability to only install one -- but expect that the distributor doing so is going to build them all?



> Many Linux distributions split `iscsi` and `isns` into multiple packages. For example `libisns0`, `open-isns-server`, `open-iscsi`, `iscsiuio`, etc.

In this case, they would build everything, and install everything too, but install some files in one split package and some files in another. Meson's [install tags](https://mesonbuild.com/Installing.html#installation-tags) offer convenience mechanisms around this. Some tags are handled by default (e.g. devel corresponds to libisns0, vs runtime), but fine tuning the tags does require Meson 0.60.0.

**Comment by tianyuanhao** [comment]
@eli-schwartz I think we can at least provide `install_tag`.

@tpetazzoni However, `pkg-meson.mk` uses `ninja` instead of `meson` to perform the installation, which does not support `tags` flag.

**Comment by gonzoleeman** [comment]
Yes, please be more specific. Give examples. I'd like to accommodate your request, but I need to understand it first.

**Comment by tianyuanhao** [comment]
> Yes, please be more specific. Give examples. I'd like to accommodate your request, but I need to understand it first.

@gonzoleeman Add configuration options to build `iscsistart` and `iscsid` and `iscsiuio` separately, (`libisns` and `isnsd` for `open-isns`). Check build dependencies individually for them.

**Comment by gonzoleeman** [comment]
I believe I understand at least part of what you're asking.

Right now we only require meson version 0.54,  I believe. So it might be a year or so until version 0.60 is distrubuted widely enough so that we can use tags. [There are other more advanced options I'd love to use, as well.]

You could always do a "meson build", then just manually install the things you need from builddir/... Or write a script to do that.

**Comment by tianyuanhao** [comment]
Yes, I think so.

**Comment by gonzoleeman** [comment]
I'm leaving this open, as an enhancement request, since we should be able to do this once we've been using meson for a while (and we no longer have to support older versions).

**Comment by gonzoleeman** [comment]
See pull request #407

**Comment by gonzoleeman** [comment]
open-isns use is now optional. Is that enough for you @tianyuanhao ?

**Comment by tianyuanhao** [comment]
> open-isns use is now optional. Is that enough for you @tianyuanhao ?

Very good, that's enough.
