### ISSUE TITLE
libopeniscsiusr licensing

### ISSUE THREAD

**Issue by tbzatek** [open-iscsi/open-iscsi#379]
Just noticed that `libopeniscsiusr` is GPL3+ while the project itself and the rest of the code is GPLv2+. Is that on purpose? Any chance of relicensing? @cathay4t ?

FYI, we're evaluating use of `libopeniscsiusr` in https://github.com/storaged-project/udisks/ with the intention to further extend the library with initiator operations.

**Comment by gonzoleeman** [comment]
Different people contributed the open-iscsi general code, vs. the library, which was added later.

Based on your question, it seems you don't like something in the GPL3+ license for libopeniscsiusr? Whatever that is, in general I believe it's non-trivial to change the license on already-released code. At the very least, I assume it would require the permission of the original author(s). So please explain your issues with GPL3+ -- slowly, since I'm a license idiot.

**Comment by gonzoleeman** [comment]
@tbzatek any response?

**Comment by gonzoleeman** [comment]
Sorry for not moving on this, but (1) it doesn't seem like a fire that has to be put out, and (2) I'm not sure what to do. So I've been thinking about it.

I'd like to make all the licenses play nice together, but I'm unsure how I would go about changing the license of libopeniscsiusr, when the author seems to no longer be around.

**Comment by cathay4t** [comment]
I am OK on relicensing my contributions to GPLv2+.

**Comment by cathay4t** [comment]
You got my approval on re-licensing my contributions to LGPL3+ considering it is a library. I will leave it to your expertise to decide.

**Comment by gonzoleeman** [comment]
> You also got my approval on re-licensing my contributions to LGPL3+ considering it is a library. I will leave it to your expertise to decide.

It looks like that if we change the library to LGPLv3, that would mean the license of open-iscsi would become GPLv3, even though it's licensed as GPLv2+. Never the less, this might be the best approach, as I don't really want to track down enough contributors to be able to actually change open-iscsi (sans libopeniscsiusr) as GPLv3.

I really don't think we should use GPLv2+ for the library. It's an old license, and it isn't mean for shared libraries that we want to actually share.

Does anyone have an objection to changing the libopeniscsiusr license from GLPv3 to LGPLv3?

**Comment by tbzatek** [comment]
> Does anyone have an objection to changing the libopeniscsiusr license from GLPv3 to LGPLv3?

Fine with me, thanks!

**Comment by gonzoleeman** [comment]
See pull request #403 

Questions:

- I added a COPYING file in libopeniscsiusr/ for LPGLv3. Is that enough?
- The only place I found any mention of the libopeniscsiusr license was in the man page for the library. Should it be some place else as well?
- Should I mention anything about this in the high-level README for open-iscsi (or any other place in the documentation?)
- I thought about mentioning the date this license change is taking place, e.g. in the library man page, but I'm not sure we need that -- that's what the git repository is for. What do you think?
- Am I missing anything else?

**Comment by gonzoleeman** [comment]
Thanks for taking the time to give valuable feedback, @tbzatek 

Two more commits pushed, changing the wording in the source files, and adding some info to the top-level README file.

Please review, if you can.

**Comment by gonzoleeman** [comment]
I'm planning on merging the reference pull request today. If you have issues with anything, please mention them here. I will close this if you don't have any more issues.

**Comment by tbzatek** [comment]
Fine with me, thanks!
