### ISSUE TITLE
iscsiadm

### ISSUE THREAD

**Issue by royrosen** [open-iscsi/open-iscsi#38]
Hi,
I am using iscsiadm to create many connections.
I can see that isid fields a and b contain the driver id, isid c has a number 0-0xFF but isid d is always 0.
so if I create more than 256 logins on the same session new logins get the same isid since only field c is changing and it has only 1 byte.
Can you please tell if this is misconfiguration, because from the code it seems that the id should be written into fields c and d together, so why is the always in the range of 0-0xFF?
Thanks, Roy.

**Comment by royrosen** [comment]
For example, running
iscsiadm -m session -r /sys/devices/platform/host891/session883/ -o new
257 times would mean that the first and last login are getting the same isid.
Can you please tell what is wrong here?

**Comment by cleech** [comment]
This should be fixed with commit 4c1f2d9
I responded on the mailing list regarding distro packages that include this change
