### ISSUE TITLE
overlinked with libopeniscsiusr

### ISSUE THREAD

**Issue by shaba** [open-iscsi/open-iscsi#380]
Build with meson.
All utils (iscsid, iscsiadm, and iscsistart) link with libopeniscsiusr, but only one iscsiadm realy need linking with libopeniscsiusr

**Comment by eli-schwartz** [comment]
The library isn't optimized out by `-Wl,--as-needed`, and removing it causes various missing symbol errors at link time due to iface.c -- both of the other binaries call into iface.

What is your reason for thinking they don't need to link to it?

**Comment by shaba** [comment]
We are use --as-needed globally.
I was try build iscsid and iscsistart without link libopeniscsiusr.
You can see: https://git.altlinux.org/tasks/archive/done/_302/309941
git - https://git.altlinux.org/tasks/archive/done/_302/309941/gears/100/git
log build - https://git.altlinux.org/tasks/archive/done/_302/309941/build/100/x86_64/log

I think successfully build because in meson.build:
iscsid_src_files = files([iscsi_lib_srcs, initiator_srcs, discovery_srcs, iscsid_srcs])
and iscsid included src files(and iface.c too) from iscsi_lib_srcs.
As result iscsid included iscsi_lib and not necessary link with libopeniscsiusr.
Мaybe it wasn't planned, but meson build this way.

**Comment by gonzoleeman** [comment]
I have modified the meson build files so that all binaries (iscsid, iscsiadm, iscsistart) build against the shared library. After this change, none of the binaries will run without the library, since that's the way it was originally designed.

I will submit a pull request soon, and when I do I'll put a link to it here.

It turns out all I had to do was add a "link_with: libiscsi_usr" to the "executable()" call.

Please speak up if you don't want this.

**Comment by gonzoleeman** [comment]
See pull request #384

**Comment by eli-schwartz** [comment]
It's not that I don't want this.

I just think that it's already being done. :P

**Comment by gonzoleeman** [comment]
Indeed, I should have tested first.

I just tested setting "-Wl,--as-needed" set in c_flags, and sure enough, iscsistart, iscsid, and iscsiadm all still need libopeniscsiusr.so.0.

I'll cancel this pull request.

And I'll close this issue unless we hear from @shaba about what issue he is still having.

**Comment by gonzoleeman** [comment]
Closing.
