### ISSUE TITLE
typo error __LC_SWTICH_H__

### ISSUE THREAD

**Issue by baker915** [open-iscsi/open-iscsi#385]
https://github.com/open-iscsi/open-iscsi/blob/fd0b3973ac90f6b0e57f5007034705628f7d6b3e/iscsiuio/src/uip/lc-switch.h#L57

TI should be IT

**Comment by gonzoleeman** [comment]
On Dec 21, 2022, at 11:46 PM, baker915 ***@***.***> wrote:
> 
> 
> https://github.com/open-iscsi/open-iscsi/blob/fd0b3973ac90f6b0e57f5007034705628f7d6b3e/iscsiuio/src/uip/lc-switch.h#L57
> 
> TI should be IT
> 
Submit a pull request to github.com/open-iscsi/open-iscsi?

— 
Lee Duncan
