### ISSUE TITLE
How to create an application in c programming for network data transfer using iSCSI target protocol.

### ISSUE THREAD

**Issue by ReninRoy** [open-iscsi/open-iscsi#390]
I want to use the target discovery and login and log out of ISCSI target server configuration functions from my initiator device.  please provide me  step by step procedure/program for developing the application. Thanks in advance.

**Comment by gonzoleeman** [comment]
It sounds like you're asking for an open-iscsi tutorial. I just googled that, and there are quite a few links that seem like they would be helpful to you.

I'll be glad to list some simple steps you could take, using open-iscsi, to connect to a target. I will assume you have a systemd-managed system, and you have iscsi services you will need to enable/start.

First, the systemd part: you will need the iscsi daemon (iscsid) service running. On socket-driven systems, that means iscsid may not be running until the first time you try to access it. You will also, of course, have to be root (or use pseudo).

Let's also assume you have no current targets that open-iscsi knows about.

Open-iscsi can use a "database" of known "nodes" (target endpoints). You can also use open-iscsi without the node database, but I'll leave describing how to do that as an exercise for the reader. The basic steps in open-iscsi connection are simple:

1. "Discover" one or more targets, adding them to the node database, then
2. Connect (login) to one or more targets listed in the node database, creating an iSCSI "session"
3. Once connected to a target, if it is a disc, the system will instantiate a disc entry in /dev
4. Use your target (i.e. do IO to/from it), perhaps mounting it first (if it has a filesystem)
5. When done, unmount if mounted
6. Tell open-iscsi to logout of the target (thus ending one or more sessions)

There are a few types of "discovery", but I'll just mention the most common type: "SendTargets", in which we send a request to get a list of targets.

You only need to do the discovery once, as the database is persistent. If you do discovery again, by default, it replaces the old database entry, so many just re-dicsover when there are changes.

Also, if you wish to have the target logged into each time the system starts up, you can update the node database entry for a target to set it's "startup" value to "automatic". (The default is "manual".) If you choose to do this, you need to make sure that the systemd service that manages this is running. On my distribution, it's called "iscsi.service". Basically, it logs into all "automatic" targets at startup, and logs out of them when the system is shutting down.

More specifically, the steps using open-iscsi might look something like:

> #sh iscsiadm -m discovery -t st -p some-remote-host
> <output goes here>
> #sh iscsiadm -m node -l
> 
> <use the target>
> 
> #sh iscsiadm -m session -u

The first line tells iscsiadm/iscsid to discover targets at some-remote-host using SendTargets. It would list the targets it found, if any, and create Node DB entries.

The second iscsiadm call tells iscsiadm/iscsid to log into each node in the Node DB, creating one or more sessions. This would do nothing if there are no Node DB entries.

After using the target, you could end the session using the third iscsiadm call.

Apologies for this being so long, and kudos if you are still reading! As far as "developing an application", I'm not sure what you mean or how I can help with that.

**Comment by ReninRoy** [comment]
Ok thanks for your reply. I understand the concept about iSCSI communication you described above. I am trying to write a C program in Ubuntu system. I am planning to use open ISCSI library there and try to compile it in gcc. So can you tell me more about programming side not command line part. Like how all the APIs/functions made in open_iscsi to discover targets, to login and to logout target. So i can directly call that APIs and compile it easily.

**Comment by ReninRoy** [comment]
can u help me with a sample c program? then i can easily understand the working.

**Comment by gonzoleeman** [comment]
> On Jan 13, 2023, at 1:31 AM, ReninRoy ***@***.***> wrote:
> 
> 
> can u help me with a sample c program? then i can easily understand the working.
> 

Heh. That’s quite a request.

I suggest you look at iscsistart.c, as this is a good example of a minimal iscsi program. It was hacked from (I believe) iscsid, but it does not implement any background daemon, i.e. it does work then goes away.

You can also look at the header files for the library, or the man pages generated from those header files. the header files are in the open-iscsi-devel package in SUSE - not sure of the package name in other distributions. They are /usr/include/libopeniscsiusr*.h (5 of them?). The man pages are of the form iscsi_*(3), and libopeniscsiusr.h(3). The are also in the sources for open-iscsi, of course, under libopeniscsiusr.

The routines seem to be grouped by:

* iscsi_context*() — manages context
* iscsi_*iface*() — interface routines
* iscsi_node*() — node routines (for the Node DB)
* iscsi_session*() — session routines
* others — a few other routines, like iscsi_strerror(3), iscsi_log_priority_tmo_get(3)

Disclaimer: I did not create this library nor do the conversion from pre-library to post-library. This change was submitted by Gris Gre and Redhat (in 2018).

If you do pursue using the library to create your own binary, you might consider writing up what you’ve done, or even presenting it at a conference. :)
-- 
Lee Duncan

"A witty saying proves nothing." -- Voltaire

**Comment by ReninRoy** [comment]
Ok thanks for the help. Let me try to figure out the file and proceed.

**Comment by gonzoleeman** [comment]
I'm closing this issue. Please open a new one if you have problems using the library, or further questions I might know the answer to. :)
