### ISSUE TITLE
My iSCSI is not working properly

### ISSUE THREAD

**Issue by yunyizea** [open-iscsi/open-iscsi#405]
There are two network cards in this server, one 1G network card, one 10G network card, one 1G network card connected to the switch, the 10G network card directly connected to the iSCSI server, the iSCSI server also has two network cards, which are linked in the same way as the operating server. Then I can use iscsiadm to discover the iSCSI storage of the storage server with 1G network port. But with a 10G port you will get the error "iscsiadm: cannot make connection to 192.168.0.3: Connection refused", and then my server is debian's operating system. 

This problem has been bothering me for a long time, and using a 1G network card is not a problem, but it is too slow and the added 10G cannot work properly.  

---
This is the configuration file for iface  
![image](https://user-images.githubusercontent.com/59525863/225788587-9e5928f0-8c8d-4596-949b-4fa95798d229.png)  
This is the IP configuration  
![image](https://user-images.githubusercontent.com/59525863/225789261-370a4ae9-b174-4136-9f51-80f439fc5ca2.png)  
This is an iscsi target discovered using a 1G network port  
![image](https://user-images.githubusercontent.com/59525863/225789749-e8b58720-e8f8-496a-9dad-b55499b06215.png)  
---
| ServerName | IP |
| - | - |
| Operating Server | 172.28.91.2,192.168.0.2 |
| Storage Server | 172.28.91.3,192.168.0.3 |

**Comment by yunyizea** [comment]
This is the discovery command I used  
![image](https://user-images.githubusercontent.com/59525863/225790005-668ef069-b158-4cb1-9739-60ea7b7b61d6.png)  
This is iscsi - m iface  
![image](https://user-images.githubusercontent.com/59525863/225790080-2a07529e-4cfa-46a3-a252-42e20c4e0ca0.png)

**Comment by gonzoleeman** [comment]
@samy-mahmoudi can I assume by your non-reply that all is working for you now?

**Comment by yunyizea** [comment]
@gonzoleeman  Sorry sir, I apologize for my long reply, I have changed this server, on the new server it works fine, I don't know what is causing it.

**Comment by gonzoleeman** [comment]
> @gonzoleeman Sorry sir, I apologize for my long reply, I have changed this server, on the new server it works fine, I don't know what is causing it.

If it's working now for you, no problem. If you still have this problem, then please reopen this issue.
