### ISSUE TITLE
Systemd issue: socket activation breaks the rules for ordering units!

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/open-iscsi#416]
Hi All:

I recently was dealing with an issue involving iscsiuio, iscsid, and booting using iSCSI (using both daemons).

For iscsiuio, the unit iscsiuio.service is set up. For iscsid, the iscsid.service unit is used. These two units are supposed to be started in the order of iscsiuo, then iscsid. Then, the iscsi.service unit can be started. The order is important. And, indeed, if we enable all units, systemd orders them correctly.

The problem is that we are using "systemd socket activation" for both iscsiuio and iscsid. That means that they both have a "socket" unit (i.e. iscsid.socket and iscsiuio.socket), and that once those units are started, anybody can start up the daemon just by trying to talk to it!

This normally has not been a problem for normal (non-root) iSCSI usage. But it can mean that an iSCSI-root system intermittently fails, and that's not good.

One way to fix this is to enable the units iscsid.service and iscsiuio.service. This means that they get started in the right order, which is great. But, if that's the case, why have socket activation at all? The whole value added from socket activation is that the daemon doesn't have to be running until it's needed. If we just enable these units, we loose the value of socket-activation. So why not just remove it? Of course, a change like that would take some time, since many distros currently count on the socket files being there.

One way for my distro to address this issue is to ensure that both services are just enabled when building an iSCSI root in dracut. That seems to be the only time that the system is in a race condition, where we need "root" as soon as possible.

Anyone have any good ideas here?

**Comment by cleech** [comment]
I'm curious as to where in the boot sequence you're seeing problems.  Is it in the initramfs, or after pivot root when the services need to start for session recovery?

**Comment by gonzoleeman** [comment]
I believe it’s during root pivot. I’ll check. --Lee-Man DuncanSent from my iPhone, dudeOn Apr 24, 2023, at 2:56 PM, Chris Leech ***@***.***> wrote:﻿
I'm curious as to where in the boot sequence you're seeing problems.  Is it in the initramfs, or after pivot root when the services need to start for session recovery?

**Comment by gonzoleeman** [comment]
On Apr 24, 2023, at 3:11 PM, Lee Duncan ***@***.***> wrote:
> 
> I believe it’s during root pivot. I’ll check. 
> 
> --
> Lee-Man Duncan
> Sent from my iPhone, dude
> 
> 
>> On Apr 24, 2023, at 2:56 PM, Chris Leech ***@***.***> wrote:
>> 
>> ﻿
>> 
>> I'm curious as to where in the boot sequence you're seeing problems. Is it in the initramfs, or after pivot root when the services need to start for session recovery?
>> 

I was wrong. It is on boot. Using iscsiuio. The heart of the problem (according to Nilesh) is that iscsiuio needs to start first, then iscsid, then iscsi.service. But Martin and I have verified with systemd developers that socket activation can break ordering and transaction rules. And if you use socket activation, iscsid starts, then tries to talk to iscsiuio, which fails. Then systemd retries it several times, all similarly failing.

Yes, I *do* with iscsiuio could handle being started after iscsid, and I’m not sure why it doesn’t.

But we clearly have told systemd the order we want these services to start in, and it clearly violates that with socket activation. We verified that if we just enable the services themselves, the intermittent failures go away.

— 
Lee

**Comment by gonzoleeman** [comment]
> On Apr 24, 2023, at 3:11 PM, Lee Duncan ***@***.***> wrote: I believe it’s during root pivot. I’ll check. -- Lee-Man Duncan Sent from my iPhone, dude > On Apr 24, 2023, at 2:56 PM, Chris Leech ***@***.***> wrote: > > ﻿ > > I'm curious as to where in the boot sequence you're seeing problems. Is it in the initramfs, or after pivot root when the services need to start for session recovery? >
> I was wrong. It is on boot. Using iscsiuio. The heart of the problem (according to Nilesh) is that iscsiuio needs to start first, then iscsid, then iscsi.service. But Martin and I have verified with systemd developers that socket activation can break ordering and transaction rules. And if you use socket activation, iscsid starts, then tries to talk to iscsiuio, which fails. Then systemd retries it several times, all similarly failing. Yes, I *do* with iscsiuio could handle being started after iscsid, and I’m not sure why it doesn’t. But we clearly have told systemd the order we want these services to start in, and it clearly violates that with socket activation. We verified that if we just enable the services themselves, the intermittent failures go away. — Lee

Okay, I spent time looking closely at the bug. Turns out that it is in real root, **after** the pivot. And the fix was to enable iscsid.service and iscsiuio.service, so that systemd realized it needed to include those units in it's transactions. (when socket-activated but not enabled, the services do not count as "enabled".)

For now, for me, this will have to be fixed by yast, which is our installation tool.

In the long term, I'd like to remove socket activation, but I fear that would be difficult, since it would be an incompatable change.

**Comment by gonzoleeman** [comment]
I looked at the service, @cleech, and considered adding it to our distro. But it turns out the problem here was really iscsiuio, and when that's fixed then the ordering doesn't matter any longer (between iscsid and iscsiuio). So I'm closing this issue.
