### ISSUE TITLE
2.1.8:`[-Werror=format-security]` errors

### ISSUE THREAD

**Issue by kloczek** [open-iscsi/open-iscsi#420]
On passing in CFLAGS `-Werror=format-security` build fails with
```console
[tkloczko@pers-jacek SPECS]$ ninja -k 0
ninja: error: loading 'build.ninja': No such file or directory
[tkloczko@pers-jacek SPECS]$
[tkloczko@pers-jacek x86_64-redhat-linux-gnu]$ ninja -k 0
[1/12] Compiling C object libsysdeps.a.p/sysdeps_sysdeps.c.o
FAILED: libsysdeps.a.p/sysdeps_sysdeps.c.o
/usr/bin/gcc -Ilibsysdeps.a.p -I. -I.. -Iusr -I../usr -I../include -Ilibopeniscsiusr -I../libopeniscsiusr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -Wno-all -MD -MQ libsysdeps.a.p/sysdeps_sysdeps.c.o -MF libsysdeps.a.p/sysdeps_sysdeps.c.o.d -o libsysdeps.a.p/sysdeps_sysdeps.c.o -c ../sysdeps/sysdeps.c
cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
cc1: some warnings being treated as errors
[2/12] Compiling C object libfwparam.a.p/usr_fwparam_ibft_fw_entry.c.o
FAILED: libfwparam.a.p/usr_fwparam_ibft_fw_entry.c.o
/usr/bin/gcc -Ilibfwparam.a.p -I. -I.. -Iusr -I../usr -I../include -Ilibopeniscsiusr -I../libopeniscsiusr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -D_GNU_SOURCE -DOFFLOAD_BOOT_SUPPORTED '-DISCSI_CONFIG_ROOT="/etc/iscsi"' '-DISCSI_DB_ROOT="/etc/iscsi"' '-DLOCK_DIR="/run/lock/iscsi"' '-DISCSI_VERSION_STR="2.1.8"' -Wno-all -MD -MQ libfwparam.a.p/usr_fwparam_ibft_fw_entry.c.o -MF libfwparam.a.p/usr_fwparam_ibft_fw_entry.c.o.d -o libfwparam.a.p/usr_fwparam_ibft_fw_entry.c.o -c ../usr/fwparam_ibft/fw_entry.c
cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
cc1: some warnings being treated as errors
[3/12] Compiling C object libfwparam.a.p/usr_fwparam_ibft_prom_parse.tab.c.o
FAILED: libfwparam.a.p/usr_fwparam_ibft_prom_parse.tab.c.o
/usr/bin/gcc -Ilibfwparam.a.p -I. -I.. -Iusr -I../usr -I../include -Ilibopeniscsiusr -I../libopeniscsiusr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -D_GNU_SOURCE -DOFFLOAD_BOOT_SUPPORTED '-DISCSI_CONFIG_ROOT="/etc/iscsi"' '-DISCSI_DB_ROOT="/etc/iscsi"' '-DLOCK_DIR="/run/lock/iscsi"' '-DISCSI_VERSION_STR="2.1.8"' -Wno-all -MD -MQ libfwparam.a.p/usr_fwparam_ibft_prom_parse.tab.c.o -MF libfwparam.a.p/usr_fwparam_ibft_prom_parse.tab.c.o.d -o libfwparam.a.p/usr_fwparam_ibft_prom_parse.tab.c.o -c ../usr/fwparam_ibft/prom_parse.tab.c
cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
cc1: some warnings being treated as errors
[4/12] Compiling C object libfwparam.a.p/usr_fwparam_ibft_fwparam_sysfs.c.o
FAILED: libfwparam.a.p/usr_fwparam_ibft_fwparam_sysfs.c.o
/usr/bin/gcc -Ilibfwparam.a.p -I. -I.. -Iusr -I../usr -I../include -Ilibopeniscsiusr -I../libopeniscsiusr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -D_GNU_SOURCE -DOFFLOAD_BOOT_SUPPORTED '-DISCSI_CONFIG_ROOT="/etc/iscsi"' '-DISCSI_DB_ROOT="/etc/iscsi"' '-DLOCK_DIR="/run/lock/iscsi"' '-DISCSI_VERSION_STR="2.1.8"' -Wno-all -MD -MQ libfwparam.a.p/usr_fwparam_ibft_fwparam_sysfs.c.o -MF libfwparam.a.p/usr_fwparam_ibft_fwparam_sysfs.c.o.d -o libfwparam.a.p/usr_fwparam_ibft_fwparam_sysfs.c.o -c ../usr/fwparam_ibft/fwparam_sysfs.c
cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
cc1: some warnings being treated as errors
[5/12] Compiling C object libfwparam.a.p/usr_fwparam_ibft_fwparam_ppc.c.o
FAILED: libfwparam.a.p/usr_fwparam_ibft_fwparam_ppc.c.o
/usr/bin/gcc -Ilibfwparam.a.p -I. -I.. -Iusr -I../usr -I../include -Ilibopeniscsiusr -I../libopeniscsiusr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -D_GNU_SOURCE -DOFFLOAD_BOOT_SUPPORTED '-DISCSI_CONFIG_ROOT="/etc/iscsi"' '-DISCSI_DB_ROOT="/etc/iscsi"' '-DLOCK_DIR="/run/lock/iscsi"' '-DISCSI_VERSION_STR="2.1.8"' -Wno-all -MD -MQ libfwparam.a.p/usr_fwparam_ibft_fwparam_ppc.c.o -MF libfwparam.a.p/usr_fwparam_ibft_fwparam_ppc.c.o.d -o libfwparam.a.p/usr_fwparam_ibft_fwparam_ppc.c.o -c ../usr/fwparam_ibft/fwparam_ppc.c
cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
cc1: some warnings being treated as errors
[6/12] Compiling C object libfwparam.a.p/usr_fwparam_ibft_prom_lex.c.o
FAILED: libfwparam.a.p/usr_fwparam_ibft_prom_lex.c.o
/usr/bin/gcc -Ilibfwparam.a.p -I. -I.. -Iusr -I../usr -I../include -Ilibopeniscsiusr -I../libopeniscsiusr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -D_GNU_SOURCE -DOFFLOAD_BOOT_SUPPORTED '-DISCSI_CONFIG_ROOT="/etc/iscsi"' '-DISCSI_DB_ROOT="/etc/iscsi"' '-DLOCK_DIR="/run/lock/iscsi"' '-DISCSI_VERSION_STR="2.1.8"' -Wno-all -MD -MQ libfwparam.a.p/usr_fwparam_ibft_prom_lex.c.o -MF libfwparam.a.p/usr_fwparam_ibft_prom_lex.c.o.d -o libfwparam.a.p/usr_fwparam_ibft_prom_lex.c.o -c ../usr/fwparam_ibft/prom_lex.c
cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
cc1: some warnings being treated as errors
ninja: build stopped: cannot make progress due to previous errors.
```

**Comment by gonzoleeman** [comment]
> On Jun 14, 2023, at 4:40 AM, Tomasz Kłoczko ***@***.***> wrote:
> 
> 
> On passing in CFLAGS -Werror=format-security build fails with
> 
> ***@***.*** SPECS]$ ninja -k 0
> ninja: error: loading 'build.ninja': No such file or directory
> ***@***.*** SPECS]$
> ***@***.*** x86_64-redhat-linux-gnu]$ ninja -k 0
> [1/12] Compiling C object libsysdeps.a.p/sysdeps_sysdeps.c.o
> FAILED: libsysdeps.a.p/sysdeps_sysdeps.c.o
> /usr/bin/gcc -Ilibsysdeps.a.p -I. -I.. -Iusr -I../usr -I../include -Ilibopeniscsiusr -I../libopeniscsiusr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -Wno-all -MD -MQ libsysdeps.a.p/sysdeps_sysdeps.c.o -MF libsysdeps.a.p/sysdeps_sysdeps.c.o.d -o libsysdeps.a.p/sysdeps_sysdeps.c.o -c ../sysdeps/sysdeps.c
> cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
> cc1: some warnings being treated as errors
> [2/12] Compiling C object libfwparam.a.p/usr_fwparam_ibft_fw_entry.c.o
> FAILED: libfwparam.a.p/usr_fwparam_ibft_fw_entry.c.o
> /usr/bin/gcc -Ilibfwparam.a.p -I. -I.. -Iusr -I../usr -I../include -Ilibopeniscsiusr -I../libopeniscsiusr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -D_GNU_SOURCE -DOFFLOAD_BOOT_SUPPORTED '-DISCSI_CONFIG_ROOT="/etc/iscsi"' '-DISCSI_DB_ROOT="/etc/iscsi"' '-DLOCK_DIR="/run/lock/iscsi"' '-DISCSI_VERSION_STR="2.1.8"' -Wno-all -MD -MQ libfwparam.a.p/usr_fwparam_ibft_fw_entry.c.o -MF libfwparam.a.p/usr_fwparam_ibft_fw_entry.c.o.d -o libfwparam.a.p/usr_fwparam_ibft_fw_entry.c.o -c ../usr/fwparam_ibft/fw_entry.c
> cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
> cc1: some warnings being treated as errors
> [3/12] Compiling C object libfwparam.a.p/usr_fwparam_ibft_prom_parse.tab.c.o
> FAILED: libfwparam.a.p/usr_fwparam_ibft_prom_parse.tab.c.o
> /usr/bin/gcc -Ilibfwparam.a.p -I. -I.. -Iusr -I../usr -I../include -Ilibopeniscsiusr -I../libopeniscsiusr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -D_GNU_SOURCE -DOFFLOAD_BOOT_SUPPORTED '-DISCSI_CONFIG_ROOT="/etc/iscsi"' '-DISCSI_DB_ROOT="/etc/iscsi"' '-DLOCK_DIR="/run/lock/iscsi"' '-DISCSI_VERSION_STR="2.1.8"' -Wno-all -MD -MQ libfwparam.a.p/usr_fwparam_ibft_prom_parse.tab.c.o -MF libfwparam.a.p/usr_fwparam_ibft_prom_parse.tab.c.o.d -o libfwparam.a.p/usr_fwparam_ibft_prom_parse.tab.c.o -c ../usr/fwparam_ibft/prom_parse.tab.c
> cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
> cc1: some warnings being treated as errors
> [4/12] Compiling C object libfwparam.a.p/usr_fwparam_ibft_fwparam_sysfs.c.o
> FAILED: libfwparam.a.p/usr_fwparam_ibft_fwparam_sysfs.c.o
> /usr/bin/gcc -Ilibfwparam.a.p -I. -I.. -Iusr -I../usr -I../include -Ilibopeniscsiusr -I../libopeniscsiusr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -D_GNU_SOURCE -DOFFLOAD_BOOT_SUPPORTED '-DISCSI_CONFIG_ROOT="/etc/iscsi"' '-DISCSI_DB_ROOT="/etc/iscsi"' '-DLOCK_DIR="/run/lock/iscsi"' '-DISCSI_VERSION_STR="2.1.8"' -Wno-all -MD -MQ libfwparam.a.p/usr_fwparam_ibft_fwparam_sysfs.c.o -MF libfwparam.a.p/usr_fwparam_ibft_fwparam_sysfs.c.o.d -o libfwparam.a.p/usr_fwparam_ibft_fwparam_sysfs.c.o -c ../usr/fwparam_ibft/fwparam_sysfs.c
> cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
> cc1: some warnings being treated as errors
> [5/12] Compiling C object libfwparam.a.p/usr_fwparam_ibft_fwparam_ppc.c.o
> FAILED: libfwparam.a.p/usr_fwparam_ibft_fwparam_ppc.c.o
> /usr/bin/gcc -Ilibfwparam.a.p -I. -I.. -Iusr -I../usr -I../include -Ilibopeniscsiusr -I../libopeniscsiusr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -D_GNU_SOURCE -DOFFLOAD_BOOT_SUPPORTED '-DISCSI_CONFIG_ROOT="/etc/iscsi"' '-DISCSI_DB_ROOT="/etc/iscsi"' '-DLOCK_DIR="/run/lock/iscsi"' '-DISCSI_VERSION_STR="2.1.8"' -Wno-all -MD -MQ libfwparam.a.p/usr_fwparam_ibft_fwparam_ppc.c.o -MF libfwparam.a.p/usr_fwparam_ibft_fwparam_ppc.c.o.d -o libfwparam.a.p/usr_fwparam_ibft_fwparam_ppc.c.o -c ../usr/fwparam_ibft/fwparam_ppc.c
> cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
> cc1: some warnings being treated as errors
> [6/12] Compiling C object libfwparam.a.p/usr_fwparam_ibft_prom_lex.c.o
> FAILED: libfwparam.a.p/usr_fwparam_ibft_prom_lex.c.o
> /usr/bin/gcc -Ilibfwparam.a.p -I. -I.. -Iusr -I../usr -I../include -Ilibopeniscsiusr -I../libopeniscsiusr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -D_GNU_SOURCE -DOFFLOAD_BOOT_SUPPORTED '-DISCSI_CONFIG_ROOT="/etc/iscsi"' '-DISCSI_DB_ROOT="/etc/iscsi"' '-DLOCK_DIR="/run/lock/iscsi"' '-DISCSI_VERSION_STR="2.1.8"' -Wno-all -MD -MQ libfwparam.a.p/usr_fwparam_ibft_prom_lex.c.o -MF libfwparam.a.p/usr_fwparam_ibft_prom_lex.c.o.d -o libfwparam.a.p/usr_fwparam_ibft_prom_lex.c.o -c ../usr/fwparam_ibft/prom_lex.c
> cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
> cc1: some warnings being treated as errors
> ninja: build stopped: cannot make progress due to previous errors.

It looks like the compiler is telling you why it failed: you cannot supply “-Werror=format-security” without also passing in “-Werror=format” first.

I verified this works just fine.
— 
Lee

**Comment by kloczek** [comment]
> It looks like the compiler is telling you why it failed: you cannot supply “-Werror=format-security” without also passing in “-Werror=format” first. I verified this works just fine. — Lee

Those two warnings/errors are different clasess.
Please verify actual code.

**Comment by gonzoleeman** [comment]
Note: you can use either "-Wformat", or "-Werror=format", I found.

**Comment by gonzoleeman** [comment]
Closing as resolved.
