### ISSUE TITLE
ifndef is not equal to def

### ISSUE THREAD

**Issue by renyi9777** [open-iscsi/open-iscsi#431]
usr/iscsid_req.h 
There is a possible problem with this file. There's an underline difference.
#ifndef ISCSID_REQ_H_
#define ISCSID_REQ_H
Is there any reason for this?
This difference causes the Clang alarm header-guard.

**Comment by gonzoleeman** [comment]
No, that looks like an error. Feel free to submit a pull request.

**Comment by gonzoleeman** [comment]
Pull request was merged, so closing.
