### ISSUE TITLE
Use of deprecated inet_aton, inet_ntoa fuctions

### ISSUE THREAD

**Issue by martinhoyer** [open-iscsi/open-iscsi#433]
As I understand, inet_ntop and inet_pton are the successors for these functions, which have been flagged by [Fedora linter](https://github.com/rpminspect/rpminspect-data-fedora/blob/0195c42882161cde10a8ab4fb39ca795014b1d3a/fedora.yaml#L745C16-L745C16) 

The functions can be found in the following files.
inet_aton:
/usr/iscsi_net_util.c

inet_ntoa:
/iscsiuio/src/uip/uip_arp.c
/iscsiuio/src/unix/iscsid_ipc.c
/iscsiuio/src/unix/libs/cnic.c
/iscsiuio/src/unix/nic.c

**Comment by gonzoleeman** [comment]
See pull request #435
