### ISSUE TITLE
mount iscsci volume only allows root to write

### ISSUE THREAD

**Issue by stephan1827** [open-iscsi/open-iscsi#442]
Hi,
I created an iSCSI volume on my NAS and connected it with iSCSI. I also created a mount point, but I can't change permission on this drive. root can copy files onto the drive, but everybody else just has read access. I tried to change permission and even ownership, but I get an error message that I can't change permission. Is there anything special I have to do to give users write access?

Stephan

**Comment by gonzoleeman** [comment]
Root should be able to change permissions on any drive or device. I just verified it works fine. I mounted an iSCSI volume, as root, then once mounted, did "chown lduncan /mnt/point". Please show the failing command sequence?

**Comment by gonzoleeman** [comment]
I'm closing this as solved, since there's been no response, and it looks like an operator error. Please re-open if this is still an issue.
