### ISSUE TITLE
profiles of iscsid.conf

### ISSUE THREAD

**Issue by Neetz** [open-iscsi/open-iscsi#447]
Hi Team, 

When i searched - i couldn't quite get any documentation and wondering if any help can be done here. 

- We have one VM and we want to support multiple iscsi vendors such as Oracle, Azure Elastic SAN etc. 
- How can i make have different iscsid.conf profiles for each vendor and alternatively each target?

**Comment by gonzoleeman** [comment]
> On Apr 10, 2024, at 1:43 PM, Neetish Bhat ***@***.***> wrote:
> 
> ﻿
> Hi Team,
> 
> When i searched - i couldn't quite get any documentation and wondering if any help can be done here.
> 
> We have one VM and we want to support multiple iscsi vendors such as Oracle, Azure Elastic SAN etc.
> How can i make have different iscsid.conf profiles for each vendor and alternatively each target?

When you discover targets you create a Node DB entry for that target. Those DB entries can be modified/updated. The values in iscsid.conf are just the defaults.

**Comment by gonzoleeman** [comment]
On Apr 10, 2024, at 4:18 PM, Lee Duncan ***@***.***> wrote:
> 
> 
>> On Apr 10, 2024, at 1:43 PM, Neetish Bhat ***@***.***> wrote:
>> 
>> ﻿
>> 
>> Hi Team,
>> 
>> When i searched - i couldn't quite get any documentation and wondering if any help can be done here.
>> 
>> We have one VM and we want to support multiple iscsi vendors such as Oracle, Azure Elastic SAN etc.
>> How can i make have different iscsid.conf profiles for each vendor and alternatively each target?
> 
> When you discover targets you create a Node DB entry for that target. Those DB entries can be modified/updated. The values in iscsid.conf are just the defaults. 
There is also an option in iscsid.conf to specified the config file. That doesn’t do what you want?

But note that if you run iscsid mutliple times, each with possibly different iscsid.conf files, the problem becomes the Node Database. You would have to either clean the Node DB out each time you used a different iscsid.conf, or you could have to figure out a way to manually switch out the Node DB yourself.

Perhaps you need one VM per flavor of iscsid.conf?
— 
Lee Duncan

**Comment by Lazymin3r** [comment]
> On Apr 10, 2024, at 1:43 PM, Neetish Bhat ***@***.***> wrote: ﻿ Hi Team, When i searched - i couldn't quite get any documentation and wondering if any help can be done here. We have one VM and we want to support multiple iscsi vendors such as Oracle, Azure Elastic SAN etc. How can i make have different iscsid.conf profiles for each vendor and alternatively each target?
> When you discover targets you create a Node DB entry for that target. Those DB entries can be modified/updated. The values in iscsid.conf are just the defaults.

Hello @gonzoleeman ,

I also have a similar question as Neetz. I have a host that needs to reach multiple iscsi targets each with a different CHAP username/password. As you mentioned I do see that there are two entries (one for each of my targets) under the /etc/iscsi/nodes/{nodename}. So if I understand correctly, instead of placing the CHAP username and password under the default /etc/iscsi/iscsid.conf file I would place the CHAP credentials:
 
#node.session.auth.username = username
#node.session.auth.password = password

under the DBs for the individual nodes in the /etc/iscsi/nodes/{nodename} file?

Thank you,

**Comment by gonzoleeman** [comment]
On Apr 11, 2024, at 9:03 PM, Lazymin3r ***@***.***> wrote:
> 
> 
> On Apr 10, 2024, at 1:43 PM, Neetish Bhat @.***> wrote: ﻿ Hi Team, When i searched - i couldn't quite get any documentation and wondering if any help can be done here. We have one VM and we want to support multiple iscsi vendors such as Oracle, Azure Elastic SAN etc. How can i make have different iscsid.conf profiles for each vendor and alternatively each target?
> When you discover targets you create a Node DB entry for that target. Those DB entries can be modified/updated. The values in iscsid.conf are just the defaults.
> 
> Hello @gonzoleeman <https://github.com/gonzoleeman> ,
> 
> I also have a similar question as Neetz. I have a host that needs to reach multiple iscsi targets each with a different CHAP username/password. As you mentioned I do see that there are two entries (one for each of my targets) under the /etc/iscsi/nodes/{nodename}. So if I understand correctly, instead of placing the CHAP username and password under the default /etc/iscsi/iscsid.conf file I would place the CHAP credentials:
> 
> #node.session.auth.username = username
> #node.session.auth.password = password
> 
> under the DBs for the individual nodes in the /etc/iscsi/nodes/{nodename} file?
> 
> Thank you,
> 

The Node DB is your friend. :)

Each ITN (Initiator Target Nexus) gets a new Node DB entry.

Once you’ve done discovery to create Node DB entries, then you can update them. You can actually use an editor on the entries, since they are in text, but that’s discouraged, since errors can occur if doing it manually.

To update an entry, first pick the node you want to update. You can see the Node entries with:

> zsh# iscsiadm -m node
>192.168.101.133:3260,1 iqn.2012-04.net.gonzoleeman:test-01
> ...

If I want to update CHAP info for that Node entry:

> zsh# iscsiadm -m node -T iqn.2012-04.net.gonzoleeman:test-01 --op update —name node.session.auth.username --value <some-user-name>
> zsh# iscsiadm -m node -T iqn.2012-04.net.gonzoleeman:test-01 --op update —name node.session.auth.password --value <that-users-password>

Hope this helps.

**Comment by Lazymin3r** [comment]
> On Apr 11, 2024, at 9:03 PM, Lazymin3r ***@***.***> wrote: On Apr 10, 2024, at 1:43 PM, Neetish Bhat @.***> wrote: ﻿ Hi Team, When i searched - i couldn't quite get any documentation and wondering if any help can be done here. We have one VM and we want to support multiple iscsi vendors such as Oracle, Azure Elastic SAN etc. How can i make have different iscsid.conf profiles for each vendor and alternatively each target? When you discover targets you create a Node DB entry for that target. Those DB entries can be modified/updated. The values in iscsid.conf are just the defaults. Hello @gonzoleeman <https://github.com/gonzoleeman> , I also have a similar question as Neetz. I have a host that needs to reach multiple iscsi targets each with a different CHAP username/password. As you mentioned I do see that there are two entries (one for each of my targets) under the /etc/iscsi/nodes/{nodename}. So if I understand correctly, instead of placing the CHAP username and password under the default /etc/iscsi/iscsid.conf file I would place the CHAP credentials: #node.session.auth.username = username #node.session.auth.password = password under the DBs for the individual nodes in the /etc/iscsi/nodes/{nodename} file? Thank you,
> The Node DB is your friend. :) Each ITN (Initiator Target Nexus) gets a new Node DB entry. Once you’ve done discovery to create Node DB entries, then you can update them. You can actually use an editor on the entries, since they are in text, but that’s discouraged, since errors can occur if doing it manually. To update an entry, first pick the node you want to update. You can see the Node entries with:
> zsh# iscsiadm -m node 192.168.101.133:3260,1 iqn.2012-04.net.gonzoleeman:test-01 ...
> If I want to update CHAP info for that Node entry:
> zsh# iscsiadm -m node -T iqn.2012-04.net.gonzoleeman:test-01 --op update —name node.session.auth.username --value <some-user-name> zsh# iscsiadm -m node -T iqn.2012-04.net.gonzoleeman:test-01 --op update —name node.session.auth.password --value <that-users-password>
> Hope this helps.

Fantastic, this was super helpful @gonzoleeman! I appreciate you sharing your knowledge. Was able to apply this configuration to my promox cluster, which is Debian based. 

Cheers!

**Comment by gonzoleeman** [comment]
I believe this issue can be closed. If there is still any issue/problem, please re-open, or perhaps better file a new (more specific) issue.
