### ISSUE TITLE
iscsiadm fails to connect while using hostname except of ip address

### ISSUE THREAD

**Issue by rishabhbansal96** [open-iscsi/open-iscsi#450]
iscsiadm did not accept host names or aliases as valid values for the --portal argument when in "node" mode. This resulted in failure, because iscsiadm expected the value returned during discovery as the value for --portal

The bug was fixed in open-iscsi-2.0.873 but I am see the issue in latest version as well. 
https://github.com/open-iscsi/open-iscsi/blob/master/Changelog#L1044

Can anyone please fix this?

**Comment by gonzoleeman** [comment]
See pull request #451 -- I'm not sure how this ever worked with hostnames, bu tnow I can do:

```
# iscsiadm -m discovery -t st -p HOSTNAME
<output>
# iscsiadm -m node -p HOSTNAME -l
```
Please feel free to pull my branch and try it yourself.

**Comment by gonzoleeman** [comment]
I'm closing this, since I merged the pull request.

**Comment by rishabhbansal96** [comment]
Thanks. When can I except this to be a part of any release?
