### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rishabhbansal96** [open-iscsi/open-iscsi#452]
Hi,

I want to request for a new release with recent code changes or bug fixes especially [#451](https://github.com/open-iscsi/open-iscsi/pull/451)
Please plan to do it asap or share an expected timeline when I can have a new release

**Comment by rishabhbansal96** [comment]
@cleech : Is there any expected timeline for that?

**Comment by gonzoleeman** [comment]
I am planning on a new release soon (sans objections from Chris), but I was hoping to get one last fix in, having to do with DB lock creation.

@cleech any objections?

**Comment by cleech** [comment]
No objections from me

**Comment by rishabhbansal96** [comment]
@gonzoleeman :  That's great! Can you please share if there's any tentative date of release available. We're all eagerly anticipating it, and having an idea of the timeline would be really helpful for our planning

**Comment by gonzoleeman** [comment]
On May 22, 2024, at 12:34 PM, rishabhbansal96 ***@***.***> wrote:
> 
> 
> @gonzoleeman <https://github.com/gonzoleeman> : That's great! Can you please share if there's any tentative date of release available. We're all eagerly anticipating it, and having an idea of the timeline would be really helpful for our planning
> 

I’m thinking within the next week. I’m busy this weekend, or I’d promise it then.

There are a few steps required to tag a new release, so it takes a little while to do it.

— 
Lee

**Comment by rishabhbansal96** [comment]
Thankyou so much Lee! 
Looking forward for the new release. Please make sure to include  #[451](https://github.com/open-iscsi/open-iscsi/pull/451)

**Comment by gonzoleeman** [comment]
> Thankyou so much Lee! Looking forward for the new release. Please make sure to include #[451](https://github.com/open-iscsi/open-iscsi/pull/451)

Of course. I'll tag HEAD, which includes all changes.

**Comment by gonzoleeman** [comment]
Version 2.1.10 has been released.

A couple of pull requests are still pending and haven't been fully addressed, so no need to wait for them IMHO, as it may be a while, and they may or may not get merged.

**Comment by rishabhbansal96** [comment]
Out of curiosity, does pending tasks includes adding this release to centos rpm?
https://gitlab.com/redhat/centos-stream/rpms/iscsi-initiator-utils

**Comment by gonzoleeman** [comment]
No. That’s a job for the maintainers of Debian. I’ll be updating Tumbleweed as part of my real job. --Lee-Man DuncanSent from my iPhone, dudeOn May 31, 2024, at 11:24 AM, rishabhbansal96 ***@***.***> wrote:﻿
Out of curiosity, does pending tasks includes adding this release to centos rpm?
https://gitlab.com/redhat/centos-stream/rpms/iscsi-initiator-utils

**Comment by rishabhbansal96** [comment]
@cleech : Can you please add the latest release to centos rpm?
