### ISSUE TITLE
DataDigest updates don't work

### ISSUE THREAD

**Issue by neetz07** [open-iscsi/open-iscsi#459]
Hi, 

I'm seeing that the data and header digests update don't work. I'm pretty sure the syntax is right

`sudo iscsiadm -m node --op update --name node.conn[0].iscsi.DataDigest --value CRC32C` 
But it fails with 
`
iscsiadm: Cannot modify node.conn[0].iscsi.DataDigest. Invalid param name.
iscsiadm: Could not execute operation on all records: invalid parameter`

But other attributes work, for example.
`sudo iscsiadm -m node --op update --name node.conn[0].iscsi.MaxRecvDataSegmentLength --value 262148`

So what could be the issue? Can you help navigate?

**ENV details**
multipath - 0.8.4-41.el8.x86_64 
udev- 239-78.el8.x86_64
OS- Rocky Linux 8.9

**Comment by gonzoleeman** [comment]
The command to update the DataDigest value to CRC32C works just fine for me.

What distro are you on, and what version of open-iscsi are you running?

**Comment by cleech** [comment]
DataDigests were disabled for RHEL a long time ago due to race conditions with the block layer during re-transmits.  They were never turned back on due to the validation efforts and a lack of customer demand.

This would need to be brought up with Rocky Linux.

**Comment by gonzoleeman** [comment]
On Sep 13, 2024, at 11:39 AM, Chris Leech ***@***.***> wrote:
> 
> 
> DataDigests were disabled for RHEL a long time ago due to race conditions with the block layer during re-transmits. They were never turned back on due to the validation efforts and a lack of customer demand.
> 
> This would need to be brought up with Rocky Linux.
> 

Interesting …

They are still enabled in SUSE Linux (and Tumbleweed), but to my knowledge are not used much.

Chris, is this something we should address here? Should open-iscsi not support Data Digests (even though they are in the standard)? Or perhaps we should add something to the README and/or iscsid.conf warning about this issue?

— 
Lee

**Comment by cleech** [comment]
The problems were a really long time ago, (I didn't disable DataDigests, I just never turned them back on).  I think things should be OK now with stable writes enabled on the block queue.  See iscsi_sw_tcp_device_configure in iscsi_tcp.c.

Are other iSCSI drivers susceptible to digest errors if page cache contents change before the write completes?  I don't know.  HBAs might not ever need to re-fetch the payload and therefor not run into this.

**Comment by neetz07** [comment]
Hi @gonzoleeman , @cleech 

Thanks for looking into this. 

The version of open-iscsi is **6.2.1.4-8.git095f59c.el8_8** and the linux distro is Rocky Linux 8.9
This is the highest open-iscsi package supported on Rocky. 

A couple of questions which I have
- Assuming there's no private patching on the kernel. Since this has been disabled on quite a few distro (rocky, fedora?, rhel) over the years, does that mean storage clients/companies who are in this configuration - are they still using iscsi with data digest off in production? 
- I could check this with rockyOS but if you have any reference to their code where they are disabling it, it will be great.

**Comment by gonzoleeman** [comment]
On Sep 16, 2024, at 9:11 AM, Neetish Bhat ***@***.***> wrote:
> 
> 
> Hi @gonzoleeman <https://github.com/gonzoleeman> , @cleech <https://github.com/cleech>
> Thanks for looking into this.
> 
> The version of open-iscsi is 6.2.1.4-8.git095f59c.el8_8 and the linux distro is Rocky Linux 8.9
> This is the highest open-iscsi package supported on Rocky.
> 

That is fairly old.
> A couple of questions which I have
> 
> Assuming there's no private patching on the kernel. Since this has been disabled on quite a few distro (rocky, fedora?, rhel) over the years, does that mean storage clients/companies who are in this configuration - are they still using iscsi with data digest off in production?
> I could check this with rockyOS but if you have any reference to their code where they are disabling it, it will be great.
To your first question, in my experience Data Digests are not used much at all. We are already transporting over TCP/IP, and it just slows things down. But I cannot speak for all users. I have not seen many bugs filed in this area, nor have I debugged many cases where they were in use.

I cannot address your second question, but why do you ask? Do you wish to enable it? You could always compile and install open-iscsi yourself. But I would advise against that if your only reason is to get Data Digests.

— 
lee

**Comment by gonzoleeman** [comment]
No response for 2 weeks ... I'm going to close this soon.

**Comment by neetz07** [comment]
Thank you @gonzoleeman . Feel free to close it.
