### ISSUE TITLE
New node record with different iface will overwrite existing node record

### ISSUE THREAD

**Issue by fengye87** [open-iscsi/open-iscsi#461]
Hi, I was trying to create two nodes, both with same target and portal, but different ifaces (with different initiator names respectively). Like:

```shell
iscsiadm -m iface -I foo -o new
iscsiadm -m iface -I bar -o new

iscsiadm -m iface -I foo -o update -n iface.initiatorname -v iqn.1994-05.com.redhat:foo
iscsiadm -m iface -I bar -o update -n iface.initiatorname -v iqn.1994-05.com.redhat:bar

iscsiadm -m node -T <my-target> -p <my-portal> -I foo -o new
iscsiadm -m node -T <my-target> -p <my-portal> -I bar -o new

iscsiadm -m node -T <my-target> -p <my-portal> -I foo   # -> ❌ no records
iscsiadm -m node -T <my-target> -p <my-portal> -I bar   # -> ✅ 
```

I would expect there be two nodes, but there was only 1.

But if I use discovery with `-o new`, there would be two nodes:

```shell
# same ifaces setup as above

iscsiadm -m discovery -t sendtargets -p <my-portal> -I foo -o new
iscsiadm -m discovery -t sendtargets -p <my-portal> -I bar -o new

iscsiadm -m node -T <my-target> -p <my-portal> -I foo   # -> ✅ 
iscsiadm -m node -T <my-target> -p <my-portal> -I bar   # -> ✅ 
```

So my questions is: what's the difference between discovery and manually adding node? Is it possible to add two nodes that differs only in iface manually?

**Comment by mikechristie** [comment]
It was so long ago that I wrote that code. I think it was for some compat with older tools reasons.

Note the code path is:

open-iscsi/user/iscsiadm.c:add_static_rec() looks like it calls idbm_add_node() with overwrite=true.

so we would need to change the behavior and OP_NEW for static creation would mean overwrite=false.

I'm not sure if we can just change it now. Maybe we would have to add another op type or something to indicate what we want.

**Comment by gonzoleeman** [comment]
@fengye87 are you okay with Mike's explanation?

**Comment by fengye87** [comment]
@gonzoleeman Sorry I forgot to reply. Yeah, as long as it's by design, I'm OK with it.

**Comment by gonzoleeman** [comment]
@fengye87 no problem. Thank you for responding now.
