### ISSUE TITLE
iSCSI disk error handling questions

### ISSUE THREAD

**Issue by steven-b89** [open-iscsi/open-iscsi#483]
Hi,

I am experiencing an "issue" (may be default behavior?) with the iSCSI initiator, I am running on AlmaLinux 9.4.
I have demo environment (hypervisor running QEMU-KVM), with 2 virtual machines, 1 for the iSCSI initiator, 1 for the target.
When I am logged in to the target all is fine and all, but if I for example shut down the target VM or stop the target service, the disk never gets removed.

It states first it is blocked for a while before going into a transport-offline state, but the disk never gets removed like for example when running lsblk command which I would think should happen?

If I test this on a Windows Server 2022 Standard with the same target with default settings the disk gets removed from the disk manager.
I would think that a linux client should also do this but this maybe wrong from my point of view?

I have already adjusted settings in /etc/iscsi/iscsid.conf without the wanted/expected result, the only thing that happen is that it will immediately fail to transport-offline state instead of keeping it blocked for a while.

I am running AlmaLinux 9.4 with kernel 5.14.0-427.37.1.el9_4.x86_64.
iSCSI initiator package version is 6.2.1.9, release 1.gita65a472.el9.
TargetCLI package version is 2.1.57.

I have disabled firewalld for testing purposes, I already turned it back on because default roles block the traffic for the client/target but this does not make any difference in the behavior.

output from /etc/iscsi/iscsid.conf:

iscsid.startup = /bin/systemctl start iscsid.socket iscsiuio.socket
node.startup = automatic
node.leading_login = No
node.session.timeo.replacement_timeout = 120 // changing this value to 0 will immediately fail the IO (transport-offline)
node.conn[0].timeo.login_timeout = 15
node.conn[0].timeo.logout_timeout = 15
node.conn[0].timeo.noop_out_interval = 5
node.conn[0].timeo.noop_out_timeout = 5
node.session.err_timeo.abort_timeout = 15
node.session.err_timeo.lu_reset_timeout = 30
node.session.err_timeo.tgt_reset_timeout = 30
node.session.err_timeo.host_reset_timeout = 60
node.session.initial_login_retry_max = 8 // also tried settings this to 0 or 1, keeps reconnecting.
node.session.cmds_max = 128
node.session.queue_depth = 32
node.session.xmit_thread_priority = -20
node.session.iscsi.InitialR2T = No
node.session.iscsi.ImmediateData = Yes
node.session.iscsi.FirstBurstLength = 262144
node.session.iscsi.MaxBurstLength = 16776192
node.conn[0].iscsi.MaxRecvDataSegmentLength = 262144
node.conn[0].iscsi.MaxXmitDataSegmentLength = 0
discovery.sendtargets.iscsi.MaxRecvDataSegmentLength = 32768
node.session.nr_sessions = 1
node.session.reopen_max = 0 // Also played with this value, keeps trying to reconnect.
node.session.iscsi.FastAbort = Yes
node.session.scan = auto // settings this value to manual means I need to manually (re)scan for the disk.

I have also played with ERL (Error Recovery Level) settings without any success so I have put these back to their default value 0.
Also worth mentioning I am not using multipath, these tools are not installed at this moment cause this seems unnecessary to me since I do not have multiple paths from 1 host to the the target nor using multiple sessions.

**Comment by mikechristie** [comment]
The iscsi initiator in linux does not remove the device when the replacement timer expires.

It's just one of those things where 20 years ago, users didn't like the device being removed. Overtime fibre channel and SAS in linux added support, but no one's ever requested it for iscsi in linux so we just never did it.

If you have a case for it let us know.
