### ISSUE TITLE
Login hangs with node.session.scan = manual

### ISSUE THREAD

**Issue by sbogomolov** [open-iscsi/open-iscsi#484]
I have noticed that iSCSI Kubernetes Persistent Volumes stopped working after upgrading `open-iscsi` from `2.1.9` to `2.1.10`. I was also able to reproduce the issue on my desktop using the same version of `open-iscsi`, so it is not distribution-specific. When `kubelet` is trying to attach a volume it does this:

```
iscsiadm -m iface -I default -o show
iscsiadm -m discoverydb -t sendtargets -p 192.168.70.20:3260 -I default -o new
iscsiadm -m discoverydb -t sendtargets -p 192.168.70.20:3260 -I default --discover
iscsiadm -m node -p 192.168.70.20:3260 -T iqn.2000-01.com.synology:nas.authentik-redis.2edf3217d57 -I default -o update -n node.session.scan -v manual
iscsiadm -m node -p 192.168.70.20:3260 -T iqn.2000-01.com.synology:nas.authentik-redis.2edf3217d57 -I default --login
```

With `open-iscsi` `2.1.10` the last command hangs and never completes.

- If I set `node.session.scan = auto` - login works.
- If I downgrade `open-iscsi` to `2.1.9` - login works with both `node.session.scan = manual` and `node.session.scan = auto`.

Context and initial investigation: https://github.com/siderolabs/extensions/issues/490

**Comment by gonzoleeman** [comment]
I believe this behavior changed with the following commit:

> 48e683c858fa ('iscsid: Rescan devices on relogin (#444)')

by Mike Christie on 4/2/2024. It fixed an issue with resizing and having iscsid block.

Perhaps you can just enable node.session.scan=auto (which is the default)?

**Comment by gonzoleeman** [comment]
@mikechristie do you wish to comment?

**Comment by sbogomolov** [comment]
> Perhaps you can just enable node.session.scan=auto (which is the default)?

I don't think I can do that. This behavior is controlled by k8s. `kubelet` explicitly sets `node.session.scan=manual` for the specific target right before logging in.

**Comment by gonzoleeman** [comment]
On Oct 18, 2024, at 10:30 AM, Sergii Bogomolov ***@***.***> wrote:
> 
> 
> Perhaps you can just enable node.session.scan=auto (which is the default)?
> 
> I don't think I can do that. This behavior is controlled by k8s. kubelet explicitly sets node.session.scan=manual for the specific target right before logging in.
> 

That seems like the bug. Why do they do that?

They are explicitly turning rediscovery off.

Perhaps you can try reverting this commit and building open-iscsi yourself, to see if it actually fixes your issue? But if you do, I’m not sure what we can do, but I can look at it a bit more.

— 
Lee

**Comment by gonzoleeman** [comment]
I believe that, in our case, something is happening that would normally cause a rescan, such as an async message from the target. Because of the change in the code is it not rescanning when it did before (even though you had rescan set to manual).

**Comment by mikechristie** [comment]
It's a bug in my patch. 

1. My patch should not have changed the scan=manual behavior. For that case we should have returned right away. I think I should have added a:

        if (!rescan && !idbm_session_autoscan(session)) {
                mgmt_ipc_write_rsp(qtask, ISCSI_SUCCESS);
                return;
       }


3. I don't think the bug the user hit is about rescan/redisconvery. It looks like they are saying when they initially login they hit a hang.

4. I think I actually added another bug as well for scan=manual rescan though but it's opposite of what you are thinking :) Before my patch we would never scan or rescan for manual, but with my patch we will now rescan. I think I thought that the scan setting was only for the initial scans.

Will send a patch in a bit.

**Comment by mikechristie** [comment]
PR here:

https://github.com/open-iscsi/open-iscsi/pull/485

**Comment by mikechristie** [comment]
>     3. I think I actually added another bug as well for scan=manual rescan though but it's opposite of what you are thinking :) Before my patch we would never scan or rescan for manual, but with my patch we will now rescan. I think I thought that the scan setting was only for the initial scans.

Ignore this one. We don't actually scan for new devices, but update the existing ones.

**Comment by mikechristie** [comment]
Oh yeah, for rescan we don't add new devices. We just update the state and size of existing ones. We really want this behavior or the device might not be usable after a relogin. I left this behavior in the patches in that PR because you will still get the behavior you wanted where you are doing a userspace based LUN masking and then for relogin if your device goes offline we will fix it up and it will be usable again automatically.

**Comment by sbogomolov** [comment]
> PR here:
> 
> 
> 
> https://github.com/open-iscsi/open-iscsi/pull/485

Thanks for the quick fix!

**Comment by gonzoleeman** [comment]
I will merge today or tomorrow. --Lee-Man DuncanSent from my iPhone, dudeOn Oct 18, 2024, at 11:46 PM, Sergii Bogomolov ***@***.***> wrote:﻿

PR here:
#485

Thanks for the quick fix!

**Comment by gonzoleeman** [comment]
Merged, so closing this issue.
