### ISSUE TITLE
kernel libiscsi queuecommand failure may corrupt ITT pool

### ISSUE THREAD

**Issue by achipper** [open-iscsi/open-iscsi#56]
I've observed (via ethernet analyzer) rare but occasional duplicate ITTs sent to my target from the same initiator session before receiving a response.  When tracking down the cause, it appears in iscsi_queuecommand, when the transport fails to take the command (when session->tt->xmit_task(task) fails) that we jump to iscsi_complete_task and reschedule the command for later.  However for this particular case when calling iscsi_complete_task the session back_lock is not held.  So, on occasion, when kfifo_in gets called there's opportunity for the ITT pool to corrupt.

In my particular setup, I am using the Mellanox ISER transport.  It's somewhat common I see the xmit_task function (in this case iscsi_iser_task_xmit) to fail under very high IOP conditions.  The failures reported by ISER seems to coincide with the duplicate ITTs I also sometimes see very shortly after.  Note though that the xmit_task failures do not cause a problem in general because the rescheduled I/O is submitted just fine on the second go around.

To test my theory I reworked iscsi_queuecommand to release the frwd_lock and grab the back_lock before calling iscsi_complete_task.  It seems to resolve my duplicate ITT problem.  However I am not very familiar with the libiscsi code in general to propose a more permanent fix.  So I wanted to get your ideas on this and if you agree there's a bug not holding back_lock when calling iscsi_complete_task.

Thank you

**Comment by gonzoleeman** [comment]
I did not write this code, nor do I yet have as much experience here as I'd like, but I believe you are correct, according to the code, in that one should be holding the back_lock when completing a task.

The best approach (least ugly) I could come up with is the following diff. Can you try it out, since you have a special target you can test with?

```
diff --git a/drivers/scsi/libiscsi.c b/drivers/scsi/libiscsi.c
index b8d325ce8754..91e0f33a7b49 100644
--- a/drivers/scsi/libiscsi.c
+++ b/drivers/scsi/libiscsi.c
@@ -1791,17 +1791,33 @@ int iscsi_queuecommand(struct Scsi_Host *host, struct scsi_cmnd *sc)
        return 0;
 
 prepd_reject:
+       spin_unlock_bh(&session->frwd_lock);
+       /* regular RX path uses back_lock */
+       spin_lock_bh(&conn->session->back_lock);
        iscsi_complete_task(task, ISCSI_TASK_REQUEUE_SCSIQ);
+       spin_unlock_bh(&conn->session->back_lock);
+       goto reject_already_unlocked;
+
 reject:
        spin_unlock_bh(&session->frwd_lock);
+
+reject_already_unlocked:
        ISCSI_DBG_SESSION(session, "cmd 0x%x rejected (%d)\n",
                          sc->cmnd[0], reason);
        return SCSI_MLQUEUE_TARGET_BUSY;
 
 prepd_fault:
+       spin_unlock_bh(&session->frwd_lock);
+       /* regular RX path uses back_lock */
+       spin_lock_bh(&conn->session->back_lock);
        iscsi_complete_task(task, ISCSI_TASK_REQUEUE_SCSIQ);
+       spin_unlock_bh(&conn->session->back_lock);
+       goto fault_already_unlocked;
+
 fault:
        spin_unlock_bh(&session->frwd_lock);
+
+fault_already_unlocked:
        ISCSI_DBG_SESSION(session, "iscsi: cmd 0x%x is not queued (%d)\n",
                          sc->cmnd[0], reason);
        if (!scsi_bidi_cmnd(sc))

```

I'd love to hear from @cleech and @mikechristie though ...

**Comment by gonzoleeman** [comment]
Okay, that previous (first) attempt at a fix was wrong. You can hold the forward lock while acquiring the back_lock, so there's no need to drop it first. Which greatly simplifies the diffs. The simple fix is to surround iscsi_task_complete() calls with acquisition of the back_lock. There are 3 places I see where that's needed. I will code up a patch and submit it upstream.

Please reply here or msg me if you'd like to see it first.

**Comment by gonzoleeman** [comment]
I believe this is fixed now, and this issue can be closed. Please re-open if still an issue.
