### ISSUE TITLE
"iscsiadm -m discovery..." command forcibly reverts node.startup value to default value

### ISSUE THREAD

**Issue by rkmrHonjo** [open-iscsi/open-iscsi#58]
Hello,

I'm using open-iscsi 2.0.873 on Ubuntu 16.04.

In that environment, all node.startup values will be forcibly reverted to default value[1] if I run "iscsiadm -m discovery..." command.
e.g.
$ sudo iscsiadm -m discovery -t sendtargets -p 172.90.128.16:3260

Is this correct behavior of iscsiadm?
I'm worried about this behavior.
Because I'd like to set node.startup value for node by node.

[1]
Default value means the value set in iscsid.conf.

**Comment by gonzoleeman** [comment]
Yes, you are telling iscsiadm to rediscover each and every target on 172.90.128.16:3260, so it will do so from scratch, regardless of whether you have an existing node entry for that target or not.

I believe you can use "--op update" to only update nodes that have changed, but it's been a while since I tested that.

What is it exactly you're trying to do? You can still manually set each node's startup value after you discover them.

**Comment by rkmrHonjo** [comment]
> Yes, you are telling iscsiadm to rediscover each and every target on 172.90.128.16:3260, so it will do so from scratch, regardless of whether you have an existing node entry for that target or not.

Thank you for explaining!
**I understand that this is the correct behavior of iscsiadm.**


Just in case, My typical operations are following:

1. I want to attach [iSCSI-node-A]'s LV to [HOST-1].
So I run "iscsiadm -m discovery..." for the [iSCSI-node-A] on [HOST-1].
2. I login to the [iSCSI-node-A]'s session.
3. I update [iSCSI-node-A]'s node.startup value with specifying target's iqn.
e.g. $ sudo iscsiadm -m node -T iqn.foo.bar -p 172.90.128.16:3260,2460 --op update -n node.startup -v automatic
4. After several days, I add new target to [iSCSI-node-A].
And I want to attach it to [HOST-1].
5. So I run "iscsiadm -m discovery..." for the [iSCSI-node-A] on [HOST-1].
As a result, all [iSCSI-node-A]'s node.startup values are reverted to default.

Of course, I can re-update node.startup values of  [iSCSI-node-A]'s old targets.
But it requires a lot of work.
**I hope that existed node.startup values won't be reverted even if I attach new disks.**

After reading your reply, I think there are two solutions.

- Stop to update node.startup value by iscsiadm.
Set the expected value to iscsid.conf instead.
- Run "iscsiadm -m node -... --op update -n node.startup" without specifying target's iqn.

Do you think these solutions work?

P.S.
To tell the truth, I do above operations through openstack.
Current OpenStack's iSCSI library does above procedures for attaching disks with multipath.
But the library has the problem that node.startup value will be reverted if user add new volume and attach it.
So I've thought that these procedures are not good.

**Comment by gonzoleeman** [comment]
I believe I was suggesting a different step 5, from above, i.e.:

# iscsiadm -m discovery -t st -p TARGET-HOST --op update

In other words, have the discovery "update" the Node database. The default is "--op new", I believe, though the man page is not clear about that.

**Comment by rkmrHonjo** [comment]
Thanks a lot!!!
Sorry, I hadn't understand your suggestion at first.

My question was solved.

**Comment by rkmrHonjo** [comment]
Hi,

I tried to run "iscsiadm -m discovery..." with specifying "--op update".
But it seemed that wasn't working.
Node.startup values would be changed even if I run "iscsiadm -m discovery..." with specifying "--op update".

Following is my test environment.

**Specifying "--op update":**
`$ sudo iscsiadm -m node -n node.startup --op show|grep node.startup`
`node.startup = manual`
`node.startup = manual`
`$ sudo iscsiadm -m node -n node.startup --op update -v automatic`
`$ sudo iscsiadm -m node -n node.startup --op show|grep node.startup`
`node.startup = automatic`
`node.startup = automatic`
`$ sudo iscsiadm -m discovery -t sendtargets -p 127.0.0.1 --op update`
`127.0.0.1:3260,1 iqn.2011-02.iscsi.test.com:lun1`
`127.0.0.1:3260,1 iqn.2011-02.iscsi.test.com:lun2`
`$ sudo iscsiadm -m node -n node.startup --op show|grep node.startup`
`node.startup = manual`
`node.startup = manual`

**Not specifying "--op update":**
`$ sudo iscsiadm -m node -n node.startup --op show|grep node.startup`
`node.startup = manual`
`node.startup = manual`
`$ sudo iscsiadm -m node -n node.startup --op update -v automatic`
`$ sudo iscsiadm -m node -n node.startup --op show|grep node.startup`
`node.startup = automatic`
`node.startup = automatic`
`$ sudo iscsiadm -m discovery -t sendtargets -p 127.0.0.1`
`127.0.0.1:3260,1 iqn.2011-02.iscsi.test.com:lun1`
`127.0.0.1:3260,1 iqn.2011-02.iscsi.test.com:lun2`
`$ sudo iscsiadm -m node -n node.startup --op show|grep node.startup`
`node.startup = manual`
`node.startup = manual`

**Comment by rkmrHonjo** [comment]
Sorry, I reopened this issue.

**Comment by gonzoleeman** [comment]
Okay, now that I pay more attention to what you are trying to do, update is not going to fix it. What update does for discovery is to update the database record instead of recreating it. As the man page mentions:

> In discovery node, ... [the] update operation will operate on the portals returned by the target, and will update the node records with info from the config file and command line.

So if you want to rediscover nodes you already have in your database, and you want node.startup to be set to automatic, then you need to set the default value in your iscsi daemon configuration file, i.e. */etc/iscsi/iscsid.conf* on my system.

**Comment by rkmrHonjo** [comment]
Thank you for explaining!

I understood that current behavior is correct .
I try to edit /etc/iscsi/iscsid.conf.

I close this issue.
