### ISSUE TITLE
Cannot set MaxRecvDataSegmentLength to max.

### ISSUE THREAD

**Issue by wyllys66** [open-iscsi/open-iscsi#6]
in iscsi_copy_operational_params, the conn->max_recv_dlength is set to _padding(conn_conf->MaxRecvDataSegmentLength);

This (_padding) rounds up the value.  If the configured MaxRecvDataSegmentLength is set to the actual maximum (2^24 -1 :  16777215), the _padding function changes it to 16777216, causing the comparison to fail and it resets the value to the default minimum (262144).

The actual maximum is really 16777212 since 16777212 & 0x03 == 0, which will cause it to pass thru the _padding function with no change.

**Comment by gonzoleeman** [comment]
Is this issue still open?

**Comment by gonzoleeman** [comment]
It's been 3 years, so closing this issue.
