### ISSUE TITLE
./configure script missing (referenced in  README)

### ISSUE THREAD

**Issue by dykeag** [open-iscsi/open-iscsi#62]
The README file instructs users to use a ./configure script to setup the build
No configure script is present in either release or the git repo itself.

A configure script should be added to the build

**Comment by gonzoleeman** [comment]
The only "./configure" mentioned in the README file is on line 89, where it says:

`To install the open-isns headers and library required for open-iscsi, download
the current release and run: 

        ./configure
        make 
        make install
        make install_hdrs
        make install_lib
`
This is talking about getting the open-isns headers and library needed by open-iscsi.

The open-isns package has the "configure" script.
