### ISSUE TITLE
Man page sucks

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/open-iscsi#68]
As pointed out recently by a contributor, we all know the iscsi man page (and interactive help information) is not exceedingly clear.

A rewrite, perhaps by a real doc writer, might be very helpful.

**Comment by gonzoleeman** [comment]
I improved it a little bit recently, but it could use an overhaul.

**Comment by shodanx2** [comment]
Hello, 
As a user, I am confused how to make iscsi work with RDMA, how that related to iSER, whether that must involve RoCE (v1 ? v2 ? both ?). 

And most importantly at the stage I am at, hardware acquisition, what is the minimum required hardware for end to end iscsi netboot with RDMA.

Which network chipsets support RDMA, does software RDMA exist / even make sense  etc..

I'm aiming to build a small, low power, 100gbe, single nvme iSCSI target able to run at full speed. Clients will be regular, 5 year old diskless PCs, with PCIE2.0 and a 40gbe NIC all netbooting off the same target mentioned above.

Documentation makes it really difficult to get a sense of what is even possible without first buying all the hardware and trying it out.

**Comment by gonzoleeman** [comment]
> Hello, As a user, I am confused how to make iscsi work with RDMA, how that related to iSER, whether that must involve RoCE (v1 ? v2 ? both ?).
> 
> And most importantly at the stage I am at, hardware acquisition, what is the minimum required hardware for end to end iscsi netboot with RDMA.
> 
> Which network chipsets support RDMA, does software RDMA exist / even make sense etc..
> 
> I'm aiming to build a small, low power, 100gbe, single nvme iSCSI target able to run at full speed. Clients will be regular, 5 year old diskless PCs, with PCIE2.0 and a 40gbe NIC all netbooting off the same target mentioned above.
> 
> Documentation makes it really difficult to get a sense of what is even possible without first buying all the hardware and trying it out.

I'm sorry, I have never used the iSER transport. From open-iscsi's point of view, it would just be a different transport (I believe).

You may have to use an interface file, which is how you tell iscsi about a unique transport or transport-specific parameters.

Which cards support RDMA/iSER are a mystery to me.

Perhaps others know? @mikechristie @cleech ???

**Comment by gonzoleeman** [comment]
I'm marking this as done, since the man page is a bit better, and I'm not sure how one could make a "man page" (not very user-friendly by nature) much better. I actually think it would take an "iscsiadm re-write", so that the command was less confusing, to enable a better man page.

**Comment by shodanx2** [comment]
Thanks that DMA over network stuff for iscsi is quite a mystery, but at the same time, it seems to be essential if you don't want to push entire gigabits of data through the CPU itself. 

This is still arcane industry knowledge. Hopefully someone can make heads or tails of this topic.
It does seem the kernel and the software already has all the functionality for this. 

Maybe it all configures itself automagically and the user doesn't know about it ?
Still waiting on 40gbps network cables, then I'll know how hard it is to get to work
