### ISSUE TITLE
Delayed-OPT-ISCSI start.

### ISSUE THREAD

**Issue by necrose99** [open-iscsi/open-iscsi#7]
my Linux distro now rams it down new kernels. and patches. 

the service loader wont FAIL...... or disable. 

@ Login screan or as X-loads ,  in backgound load service, if Kernel module fails 
(sys-block / iscsitarget builds for newer kernels pending) 
DBUS message.  if service fails dbus message to root / username... 

since ISCSI wont fail , my laptop is a nice brick with their stock kernel..... 
using genkerel-next to make one for systemD to load GRRRRRR.  so removing it not good. 

but since the service wont gracefully fail , my laptop infinitely loops on and on. trying to load. 

prior to that i could remove open-ISCSI and the km Package and go for a fresh install. (Problem solved) 

Try N times load kernel module
initiator not found sorry cant load ISCSI,
esle load KM , if ISCSI is bugged  IE build from binary isn't working and fails ( ie bugs) load N times 
Fail send alert. 

since my root is a physical drive and on my laptop I could care less least for Boot-time load. 
now if i build up a Freenas having it run to keep my backups and repos (ie github) etc , oh yeah iscsi quite good for that , and or client shares. 

ISUE="-Boot-start +Delayed-start"  

Sabayon/Gentoo isn't the only distro suffering, IE Redhat were Sabayon ports things to the Gentoo land etc, is also affected...

if your a mobile user with quirky hardware and a bleeding edge distro , shit happens like Nvida drivers...  download the *.run and do install works ever time.  however since the open-iscis breaks and when it breaks it really breaks  it's now forced , were as previously i could remove it temporally .

**Comment by gonzoleeman** [comment]
This issue appears stale, with no action for 3 years. I will close it if I don't hear an objection.

**Comment by gonzoleeman** [comment]
so noted. Closed.
