### ISSUE TITLE
Bigger iscsi_segment.size

### ISSUE THREAD

**Issue by huang-b** [open-iscsi/open-iscsi#70]
In the struct iscsi_segment, there is an attribute named "size". I have found that the value of "size" is always 4096, but I can't  find the assignment. And I want to replace it with a bigger value, such as 16384. How can I do?

**Comment by gonzoleeman** [comment]
Is this still an issue you care about? If not, I will close it. If so, I will try to help. Adding "stale" label, for now.

**Comment by gonzoleeman** [comment]
Closing this, since nobody seems to care or know about this issue.
