### ISSUE TITLE
open-iscsi does not automatically login into portal

### ISSUE THREAD

**Issue by myghacc** [open-iscsi/open-iscsi#73]
**Description of problem:**

Although "node.startup = automatic" and "node.conn[0].startup = automatic" are configured in a specific portal to start automatically after reboot no login is done although iscsid is running.

**Steps to Reproduce:**

1. In /etc/iscsi/iscsi.conf the correct path for the iscsi daemon has to be specified. In Mageia 6 (mga6) the daemon (iscsid) is installed in /sbin. So, the part of the daemon configuration has to be adjusted:

Default for upstream open-iscsi scripts (uncomment to activate).
iscsid.startup = /sbin/iscsid

   If this is not done iscsiadm cannot start the daemon:

iscsiadm -m discovery -t st -p 192.168.10.10
sh: /etc/rc.d/init.d/iscsid: Datei oder Verzeichnis nicht gefunden
iscsiadm: can not connect to iSCSI daemon (111)!
sh: /etc/rc.d/init.d/iscsid: Datei oder Verzeichnis nicht gefunden
iscsiadm: can not connect to iSCSI daemon (111)!
iscsiadm: Cannot perform discovery. Initiatorname required.
iscsiadm: Could not perform SendTargets discovery: could not connect to iscsid

2. start the daemon:
   systemctl start open-iscsi.service

3. configure nodes:
   iscsiadm -m discovery -t sendtargets -p 192.168.10.10:3260

4. login into specific portal:
   iscsiadm --mode node --targetname iqn.2010-08.eu.n-tec:icebox-rix6r-000905600:dev0.ctr1 --portal 192.168.10.10:3260 --login

5. After login the new device can be configured. I created a volume group and some logical volumes which have been formatted with xfs and can be mounted 
   via an entry in /etc/fstab:
   ...
   /dev/vg_icebox/lv_projects      /projects       xfs     _netdev,rw,inode64,logbufs=8    1       2
   ...

6. logout of the portal:
   iscsiadm --mode node --targetname iqn.2010-08.eu.n-tec:icebox-rix6r-000905600:dev0.ctr1 --portal 192.168.10.10:3260 --logout

7. update iface parameters for automatic login:
   iscsiadm -m node -T iqn.2010-08.eu.n-tec:icebox-rix6r-000905600:dev0.ctr1 -p 192.168.10.10 --op update -n node.startup -v automatic
   iscsiadm -m node -T iqn.2010-08.eu.n-tec:icebox-rix6r-000905600:dev0.ctr1 -p 192.168.10.10 --op update -n node.conn[0].startup -v automatic

8. reboot the system

9. no portal login ...

-------------------------------------------------
Hardware:
BCM57840 NetXtreme II 10 Gigabit Ethernet (QLogic 3442)

Software:
open-iscsi Version: 2.0-872.13.mga6

System:
Linux thalamus_nfs 4.9.56-server-1.mga6 #1 SMP Thu Oct 12 23:46:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gonzoleeman** [comment]
I know the automatic login stuff works, so let's figure out why it's not working here.

First of all, which distribution is this? Where did you get the open-iscsi package you are using?

Next, it seems like you are mixing old-school and new-school methods for starting your service. Newer open-iscsi packages use systemd, which means (1) they do not use /etc/init.d scripts, and (2) you should never set the "iscsid.startup = /some/path/to/iscsid". That is because systemd does all the starting/stopping/restarting for you.

Assuming you are using systemd, what systemd services to you have for iscsi? I see you have ran "systemctl start open-iscsi.service". Are there any others? (Run "ls /usr/lib/systemd/system/*iscsi*" as root.) I'm trying to understand if your open-iscsi is socket-activated or not.

Lastly, just as a guess, I never say that you ran "systemctl enable open-iscsi.service". This tells sytemd to start your service at boot time, whereas "systemctl start open-iscsi.service" just starts it up right now.

**Comment by myghacc** [comment]
Distribution is Mageia 6 64-bit with open-iscsi from their repositories.

I deleted everything in /var/lib/iscsi and uninstalled open-iscsi. After that I created a new interface with iscsiadm (iscsiadm -m iface -I icebox --op=new) and re-installed open-iscsi. Then I did a discovery with iscsiadm (iscsiadm --mode discovery --type sendtargets --portal 192.168.10.10 --discover) and checked that the portal I want to use is set to automatic (cat nodes/iqn.2010-08.eu.n-tec\:icebox-rix6r-000905600\:dev0.ctr1/192.168.10.10\,3260\,0/icebox | grep automatic). Finally I rebooted the system. The following output I get after the reboot:

[root@thalamus_nfs iscsi]# systemctl status open-iscsi.service 
● open-iscsi.service - Open iSCSI Daemon
   Loaded: loaded (/usr/lib/systemd/system/open-iscsi.service; enabled; vendor preset: enabled)
   Active: active (running) since Di 2017-12-19 08:25:06 CET; 5min ago
  Process: 2868 ExecStart=/sbin/iscsid (code=exited, status=0/SUCCESS)
  Process: 2808 ExecStartPre=/usr/sbin/modprobe -q iscsi_tcp (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/open-iscsi.service
           ├─2872 /sbin/iscsid
           └─2873 /sbin/iscsid

Dez 19 08:25:06 thalamus_nfs systemd[1]: Starting Open iSCSI Daemon...
Dez 19 08:25:06 thalamus_nfs systemd[1]: Started Open iSCSI Daemon.
Dez 19 08:25:07 thalamus_nfs iscsid[2872]: transport class version 2.0-870. iscsid version 2.0-872
Dez 19 08:25:07 thalamus_nfs iscsid[2872]: iSCSI daemon with pid=2873 started!
[root@thalamus_nfs iscsi]# pwd
/var/lib/iscsi
[root@thalamus_nfs iscsi]# tree
.
├── ifaces
│   └── icebox
├── nodes
│   └── iqn.2010-08.eu.n-tec:icebox-rix6r-000905600:dev0.ctr1
│       ├── 192.168.10.10,3260,0
│       │   └── icebox
│       ├── 192.168.20.10,3260,0
│       │   └── icebox
│       ├── 192.168.3.1,3260,1
│       │   └── icebox
│       └── 192.168.4.1,3260,1
│           └── icebox
└── send_targets
    └── icebox_iscsi_1,3260
        ├── iqn.2010-08.eu.n-tec:icebox-rix6r-000905600:dev0.ctr1,192.168.10.10,3260,0,icebox -> /var/lib/iscsi/nodes/iqn.2010-08.eu.n-tec:icebox-rix6r-000905600:dev0.ctr1/192.168.10.10,3260,0
        ├── iqn.2010-08.eu.n-tec:icebox-rix6r-000905600:dev0.ctr1,192.168.20.10,3260,0,icebox -> /var/lib/iscsi/nodes/iqn.2010-08.eu.n-tec:icebox-rix6r-000905600:dev0.ctr1/192.168.20.10,3260,0
        ├── iqn.2010-08.eu.n-tec:icebox-rix6r-000905600:dev0.ctr1,192.168.3.1,3260,1,icebox -> /var/lib/iscsi/nodes/iqn.2010-08.eu.n-tec:icebox-rix6r-000905600:dev0.ctr1/192.168.3.1,3260,1
        ├── iqn.2010-08.eu.n-tec:icebox-rix6r-000905600:dev0.ctr1,192.168.4.1,3260,1,icebox -> /var/lib/iscsi/nodes/iqn.2010-08.eu.n-tec:icebox-rix6r-000905600:dev0.ctr1/192.168.4.1,3260,1
        └── st_config

13 directories, 6 files
[root@thalamus_nfs iscsi]# ls /usr/lib/systemd/system/iscsi
ls: Zugriff auf '/usr/lib/systemd/system/iscsi' nicht möglich: Datei oder Verzeichnis nicht gefunden
[root@thalamus_nfs iscsi]#

**Comment by gonzoleeman** [comment]
I _think_ I understand your issue. You need an "iscsi login/logout" service. In the distributions that I've looked at, there are generally 3 systemd unit files for iscsi:

1. a "socket" file (e.g. "iscsid.socket"), which allows "socket activation" of the next service if somebody tries to talk to it
1. an "iscsid service" file (e.g. "iscsid.service"), which controls the starting and stopping of the iscsid daemon, and
1. an "iscsi login" file (e.g. "iscsi.service"), which controls starting and stopping "sessions" (i.e. logging into and out of targets)

The example names I gave are from openSUSE.

It is unfortunate that these files are not part of the open-iscsi distribution, but the problem is that these sets of services are implemented differently for each distribution, so their only value to others is as an example. And there's not much motivation to keep examples up to date.

Here is the "iscsi.service" file for openSUSE Leap 42.2:
`[Unit]
Description=Login and scanning of iSCSI devices
Documentation=man:iscsiadm(8) man:iscsid(8)
After=network.target network-online.target iscsid.service
ConditionPathExists=/etc/iscsi/initiatorname.iscsi

[Service]
Type=oneshot
ExecStart=-/sbin/iscsiadm -m node --loginall=automatic
ExecStop=/sbin/iscsiadm -m node --logoutall=automatic
ExecStop=/sbin/iscsiadm -m node --logoutall=manual
SuccessExitStatus=21
RemainAfterExit=true

[Install]
WantedBy=remote-fs.target`

**Comment by myghacc** [comment]
Thank you. I informed the Mageia bug team about this issue. Since it is working for me now I will close this issue.

**Comment by dpanech-wr** [comment]
I'm having the exact same problem on Ubuntu 24.04 (open-iscsi 2.1.9), `--loginall=automatic` doesn't work at all, *however* defining a non-default TCP-type interface fixes it! With only the default interface, this loop never executes: https://github.com/open-iscsi/open-iscsi/blob/master/usr/iscsiadm.c#L555 and I never see the `Establishing leading-logins via iface %s` log message in debug output.

**Comment by gonzoleeman** [comment]
On Sep 12, 2024, at 12:19 PM, Davlet Panech ***@***.***> wrote:
> 
> 
> I'm having the exact same problem on Ubuntu 24.04 (open-iscsi 2.1.9), --loginall=automatic doesn't work at all, however defining a non-default TCP-type interface fixes it! With only the default interface, this loop never executes: https://github.com/open-iscsi/open-iscsi/blob/master/usr/iscsiadm.c#L555 and I never see the Establishing leading-logins via iface %s log message in debug output.
> 

So you are using leading logins?

Please include exact steps.

Output from “egrep -r ‘startup|leading' /var/lib/iscsi/nodes”?

Command being used to attempt to login? “iscsiadm -m node -L automatic”?

Output of your login attempt with “-d5”?

— 
Lee Duncan

**Comment by dpanech-wr** [comment]
Yes, I'm using leading logins.

Exact steps:

```bash
% iscsiadm -m discovery -t sendtargets -p 10.81.32.9
10.81.32.10:3260,1 iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-a-725b50f6
10.81.32.11:3260,1 iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-b-6dfd9c7b


% egrep -r 'startup|leading' /etc/iscsi/nodes
/etc/iscsi/nodes/iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-a-725b50f6/10.81.32.10,3260,1/default:node.startup = automatic
/etc/iscsi/nodes/iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-a-725b50f6/10.81.32.10,3260,1/default:node.leading_login = Yes
/etc/iscsi/nodes/iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-a-725b50f6/10.81.32.10,3260,1/default:node.conn[0].startup = manual
/etc/iscsi/nodes/iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-b-6dfd9c7b/10.81.32.11,3260,1/default:node.startup = automatic
/etc/iscsi/nodes/iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-b-6dfd9c7b/10.81.32.11,3260,1/default:node.leading_login = Yes
/etc/iscsi/nodes/iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-b-6dfd9c7b/10.81.32.11,3260,1/default:node.conn[0].startup = manual


# no sessions established after this
% iscsiadm -d 5 -m node -L automatic
iscsiadm: Max file limits 1024 1048576
iscsiadm: Logging into leading-login portals
iscsiadm: Could not login all leading-login portals

```

But if I can create the interface first and repeat the same commands, the login succeeds:
```bash
% mkdir /etc/iscsi/ifaces
% echo "\
iface.iscsi_ifacename = if1
iface.transport_name = tcp" > /etc/iscsi/ifaces/if1

% iscsiadm -m discovery -t sendtargets -p 10.81.32.9
10.81.32.10:3260,1 iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-a-725b50f6
10.81.32.11:3260,1 iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-b-6dfd9c7b

% egrep -r 'startup|leading' /etc/iscsi/nodes
/etc/iscsi/nodes/iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-a-725b50f6/10.81.32.10,3260,1/if1:node.startup = automatic
/etc/iscsi/nodes/iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-a-725b50f6/10.81.32.10,3260,1/if1:node.leading_login = Yes
/etc/iscsi/nodes/iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-a-725b50f6/10.81.32.10,3260,1/if1:node.conn[0].startup = manual
/etc/iscsi/nodes/iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-b-6dfd9c7b/10.81.32.11,3260,1/if1:node.startup = automatic
/etc/iscsi/nodes/iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-b-6dfd9c7b/10.81.32.11,3260,1/if1:node.leading_login = Yes
/etc/iscsi/nodes/iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-b-6dfd9c7b/10.81.32.11,3260,1/if1:node.conn[0].startup = manual

% iscsiadm -d 5 -m node -L automatic
iscsiadm: Max file limits 1024 1048576
iscsiadm: Logging into leading-login portals
iscsiadm: Establishing leading-logins via iface if1
iscsiadm: doing leading login using iface: if1
iscsiadm: if1: Creating session 1/1
Logging in to [iface: if1, target: iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-a-725b50f6, portal: 10.81.32.10,3260]
iscsiadm: doing leading login using iface: if1
iscsiadm: if1: Creating session 1/1
Logging in to [iface: if1, target: iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-b-6dfd9c7b, portal: 10.81.32.11,3260]
Login to [iface: if1, target: iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-a-725b50f6, portal: 10.81.32.10,3260] successful.
Login to [iface: if1, target: iqn.2015-10.com.dell:dellemc-powerstore-apx00240413185-b-6dfd9c7b, portal: 10.81.32.11,3260] successful.
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'targetname'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'username'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'password'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'username_in'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'password_in'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'recovery_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'lu_reset_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'tgt_reset_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'abort_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'tpgt'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection3:0'/'persistent_address'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection3:0'/'address'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection3:0'/'persistent_port'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection3:0'/'port'
iscsiadm: sysfs_device_get: open '/class/iscsi_session/session3'
iscsiadm: sysfs_resolve_link: path link '/class/iscsi_session/session3' points to '../../devices/platform/host15/session3/iscsi_session/session3'
iscsiadm: sysfs_resolve_link: base '/class/iscsi_session/session3', tail 'devices/platform/host15/session3/iscsi_session/session3', back 2
iscsiadm: sysfs_resolve_link: after moving back ''
iscsiadm: sysfs_device_get: new uncached device '/devices/platform/host15/session3/iscsi_session/session3'
iscsiadm: sysfs_device_set_values: kernel='session3'
iscsiadm: sysfs_device_set_values: kernel_number='3'
iscsiadm: sysfs_device_get: subsystem link '/sys/devices/platform/host15/session3/iscsi_session/session3/subsystem' points to '../../../../../../class/iscsi_session'
iscsiadm: sysfs_device_get: add to cache 'devpath=/devices/platform/host15/session3/iscsi_session/session3', subsystem='iscsi_session', driver=''
iscsiadm: sysfs_device_get_parent: open '/devices/platform/host15/session3/iscsi_session/session3'
iscsiadm: sysfs_device_get_parent: '/devices/platform/host15/session3/iscsi_session/session3'
iscsiadm: sysfs_device_get: open '/devices/platform/host15/session3/iscsi_session'
iscsiadm: sysfs_device_get: new uncached device '/devices/platform/host15/session3/iscsi_session'
iscsiadm: sysfs_device_set_values: kernel='iscsi_session'
iscsiadm: sysfs_device_set_values: kernel_number=''
iscsiadm: sysfs_device_get: add to cache 'devpath=/devices/platform/host15/session3/iscsi_session', subsystem='', driver=''
iscsiadm: sysfs_device_get_parent: open '/devices/platform/host15/session3/iscsi_session'
iscsiadm: sysfs_device_get_parent: '/devices/platform/host15/session3/iscsi_session'
iscsiadm: sysfs_device_get: open '/devices/platform/host15/session3'
iscsiadm: sysfs_device_get: new uncached device '/devices/platform/host15/session3'
iscsiadm: sysfs_device_set_values: kernel='session3'
iscsiadm: sysfs_device_set_values: kernel_number='3'
iscsiadm: sysfs_device_get: add to cache 'devpath=/devices/platform/host15/session3', subsystem='', driver=''
iscsiadm: sysfs_device_get_parent: open '/devices/platform/host15/session3'
iscsiadm: sysfs_device_get_parent: '/devices/platform/host15/session3'
iscsiadm: sysfs_device_get: open '/devices/platform/host15'
iscsiadm: sysfs_device_get: new uncached device '/devices/platform/host15'
iscsiadm: sysfs_device_set_values: kernel='host15'
iscsiadm: sysfs_device_set_values: kernel_number='15'
iscsiadm: sysfs_device_get: subsystem link '/sys/devices/platform/host15/subsystem' points to '../../../bus/scsi'
iscsiadm: sysfs_device_get: add to cache 'devpath=/devices/platform/host15', subsystem='scsi', driver=''
iscsiadm: sysfs_attr_get_value: open '/class/scsi_host/host15'/'proc_name'
iscsiadm: Matched transport tcp
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_transport/tcp'/'handle'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_transport/tcp'/'caps'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host15'/'hwaddress'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host15'/'ipaddress'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host15'/'netdev'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'initiatorname'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host15'/'port_state'
iscsiadm: sysfs_attr_get_value: stat '/sys/class/iscsi_host/host15/port_state' failed: No such file or directory
iscsiadm: Could not read attr port_state on path /class/iscsi_host/host15
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host15'/'port_speed'
iscsiadm: sysfs_attr_get_value: stat '/sys/class/iscsi_host/host15/port_speed' failed: No such file or directory
iscsiadm: Could not read attr port_speed on path /class/iscsi_host/host15
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'ifacename'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'targetname'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'username'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'password'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'username_in'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'password_in'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'recovery_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'lu_reset_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'tgt_reset_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'abort_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'tpgt'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection3:0'/'persistent_address'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection3:0'/'address'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection3:0'/'persistent_port'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection3:0'/'port'
iscsiadm: sysfs_device_get: open '/class/iscsi_session/session3'
iscsiadm: sysfs_resolve_link: path link '/class/iscsi_session/session3' points to '../../devices/platform/host15/session3/iscsi_session/session3'
iscsiadm: sysfs_resolve_link: base '/class/iscsi_session/session3', tail 'devices/platform/host15/session3/iscsi_session/session3', back 2
iscsiadm: sysfs_resolve_link: after moving back ''
iscsiadm: sysfs_device_get: found in cache '/devices/platform/host15/session3/iscsi_session/session3'
iscsiadm: sysfs_device_get_parent: open '/devices/platform/host15/session3/iscsi_session/session3'
iscsiadm: sysfs_device_get_parent: open '/devices/platform/host15/session3/iscsi_session'
iscsiadm: sysfs_device_get_parent: open '/devices/platform/host15/session3'
iscsiadm: sysfs_attr_get_value: open '/class/scsi_host/host15'/'proc_name'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_transport/tcp'/'handle'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_transport/tcp'/'caps'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host15'/'hwaddress'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host15'/'ipaddress'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host15'/'netdev'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'initiatorname'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host15'/'port_state'
iscsiadm: sysfs_attr_get_value: stat '/sys/class/iscsi_host/host15/port_state' failed: No such file or directory
iscsiadm: Could not read attr port_state on path /class/iscsi_host/host15
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host15'/'port_speed'
iscsiadm: sysfs_attr_get_value: stat '/sys/class/iscsi_host/host15/port_speed' failed: No such file or directory
iscsiadm: Could not read attr port_speed on path /class/iscsi_host/host15
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session3'/'ifacename'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session4'/'targetname'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session4'/'username'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session4'/'password'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session4'/'username_in'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session4'/'password_in'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session4'/'recovery_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session4'/'lu_reset_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session4'/'tgt_reset_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session4'/'abort_tmo'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session4'/'tpgt'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection4:0'/'persistent_address'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection4:0'/'address'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection4:0'/'persistent_port'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_connection/connection4:0'/'port'
iscsiadm: sysfs_device_get: open '/class/iscsi_session/session4'
iscsiadm: sysfs_resolve_link: path link '/class/iscsi_session/session4' points to '../../devices/platform/host16/session4/iscsi_session/session4'
iscsiadm: sysfs_resolve_link: base '/class/iscsi_session/session4', tail 'devices/platform/host16/session4/iscsi_session/session4', back 2
iscsiadm: sysfs_resolve_link: after moving back ''
iscsiadm: sysfs_device_get: new uncached device '/devices/platform/host16/session4/iscsi_session/session4'
iscsiadm: sysfs_device_set_values: kernel='session4'
iscsiadm: sysfs_device_set_values: kernel_number='4'
iscsiadm: sysfs_device_get: subsystem link '/sys/devices/platform/host16/session4/iscsi_session/session4/subsystem' points to '../../../../../../class/iscsi_session'
iscsiadm: sysfs_device_get: add to cache 'devpath=/devices/platform/host16/session4/iscsi_session/session4', subsystem='iscsi_session', driver=''
iscsiadm: sysfs_device_get_parent: open '/devices/platform/host16/session4/iscsi_session/session4'
iscsiadm: sysfs_device_get_parent: '/devices/platform/host16/session4/iscsi_session/session4'
iscsiadm: sysfs_device_get: open '/devices/platform/host16/session4/iscsi_session'
iscsiadm: sysfs_device_get: new uncached device '/devices/platform/host16/session4/iscsi_session'
iscsiadm: sysfs_device_set_values: kernel='iscsi_session'
iscsiadm: sysfs_device_set_values: kernel_number=''
iscsiadm: sysfs_device_get: add to cache 'devpath=/devices/platform/host16/session4/iscsi_session', subsystem='', driver=''
iscsiadm: sysfs_device_get_parent: open '/devices/platform/host16/session4/iscsi_session'
iscsiadm: sysfs_device_get_parent: '/devices/platform/host16/session4/iscsi_session'
iscsiadm: sysfs_device_get: open '/devices/platform/host16/session4'
iscsiadm: sysfs_device_get: new uncached device '/devices/platform/host16/session4'
iscsiadm: sysfs_device_set_values: kernel='session4'
iscsiadm: sysfs_device_set_values: kernel_number='4'
iscsiadm: sysfs_device_get: add to cache 'devpath=/devices/platform/host16/session4', subsystem='', driver=''
iscsiadm: sysfs_device_get_parent: open '/devices/platform/host16/session4'
iscsiadm: sysfs_device_get_parent: '/devices/platform/host16/session4'
iscsiadm: sysfs_device_get: open '/devices/platform/host16'
iscsiadm: sysfs_device_get: new uncached device '/devices/platform/host16'
iscsiadm: sysfs_device_set_values: kernel='host16'
iscsiadm: sysfs_device_set_values: kernel_number='16'
iscsiadm: sysfs_device_get: subsystem link '/sys/devices/platform/host16/subsystem' points to '../../../bus/scsi'
iscsiadm: sysfs_device_get: add to cache 'devpath=/devices/platform/host16', subsystem='scsi', driver=''
iscsiadm: sysfs_attr_get_value: open '/class/scsi_host/host16'/'proc_name'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_transport/tcp'/'handle'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_transport/tcp'/'caps'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host16'/'hwaddress'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host16'/'ipaddress'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host16'/'netdev'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session4'/'initiatorname'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host16'/'port_state'
iscsiadm: sysfs_attr_get_value: stat '/sys/class/iscsi_host/host16/port_state' failed: No such file or directory
iscsiadm: Could not read attr port_state on path /class/iscsi_host/host16
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_host/host16'/'port_speed'
iscsiadm: sysfs_attr_get_value: stat '/sys/class/iscsi_host/host16/port_speed' failed: No such file or directory
iscsiadm: Could not read attr port_speed on path /class/iscsi_host/host16
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_session/session4'/'ifacename'
```
