### ISSUE TITLE
Connect iscsi via iscsiadm and run FIO to test the R/W speed but can't reach the speed limit.

### ISSUE THREAD

**Issue by WisQTuser** [open-iscsi/open-iscsi#77]
Setup tgtd by iscsi target service in Linux through 100Gbps break out 4* 25Gbps with 100Gbps Switch, client OS connect to iscsi target using iscsiadm. But Client storage performance will be limited almost 1.5Gbps by FIO.

**Comment by gonzoleeman** [comment]
There are many thing that can effect throughput. Why do you assume it is an initiator issue?

I will close this if no response ...

**Comment by gonzoleeman** [comment]
Oops. Closed already by accident.

**Comment by gonzoleeman** [comment]
Is this still an issue for anyone? Performance seems like an ever-moving target, for which we sadly don't have enough bandwidth to track.

**Comment by gonzoleeman** [comment]
No update for quite a while, so closing.
