### ISSUE TITLE
The README is quite outdated

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/open-iscsi#86]
Related to Issue#35: The README file is outdated, particularly with respect to the kernel part of the code, which has long since been integrated.

**Comment by JohnAZoidberg** [comment]
Is the README in a particular format? Would you want it to be in one or would Markdown be okay?

**Comment by gonzoleeman** [comment]
> Is the README in a particular format? Would you want it to be in one or would Markdown be okay?

It's current plain text, but markdown seems reasonable, and a little better at capturing things like emphasis, etc.

**Comment by gonzoleeman** [comment]
I have updated the README a bit, adding in information about systemd, and adding in some mention of the new "no_wait" option to iscsiadm.
