### ISSUE TITLE
shouldn't iscsiadm logout be aborted if scsi devices still present?

### ISSUE THREAD

**Issue by redbaron** [open-iscsi/open-iscsi#90]
I am investigating kworker CPU spin on iscsi session logout described here https://github.com/coreos/bugs/issues/2357 , after all experiments I found that logout completes successfully if I delete all SCSI devices created on session login.

In a nutshell, if server comes up, discovers disks, then if I  do  following without even mounting any of them:
```
iscsiadm -m node --logoutall=all
```
then 4 kworkers are spinning  on CPU (1 per multipath session).

If I do following instead:
```
multipath -F
for d in $(iscsiadm -m session -P3 |awk '/scsi disk/ {print $4}'); do echo 1 > /sys/block/$d/device/delete; done
iscsiadm -m node --logoutall=all
```
then  it is all happy. 

Not saying that kernel behaves correctly when it happens, but it begs the question if it is legitimate action at all? Is it OK by design to logout from session, while SCSI devices are present (but not used)? If it is not desirable shouldn't iscsiadm detect it and warn user instead of attempting to logout?

Extra info:
```
$ systemctl status iscsid
   Loaded: loaded (/usr/lib/systemd/system/iscsid.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/iscsid.service.d
           └─40-discovery.conf, 50-debug.conf
   Active: active (running) since Wed 2018-02-14 19:07:48 UTC; 55min ago
     Docs: man:iscsid(8)
           man:iscsiuio(8)
           man:iscsiadm(8)
  Process: 1445 ExecStartPost=/sbin/iscsiadm -m node -L all -p 10.1.72.201 -p 10.1.74.204 --login (code=exited, status=0/SUCCESS)
  Process: 995 ExecStartPost=/sbin/iscsiadm -m discovery -t st -p 10.1.72.201 -p 10.1.74.204 (code=exited, status=0/SUCCESS)
  Process: 902 ExecStartPost=/sbin/iscsiadm -m node --loginall=automatic (code=exited, status=21)
  Process: 856 ExecStart=/usr/sbin/iscsid -d8 (code=exited, status=0/SUCCESS)
 Main PID: 864 (iscsid)
    Tasks: 2 (limit: 32768)
   CGroup: /system.slice/iscsid.service
           ├─863 /usr/sbin/iscsid -d8
           └─864 /usr/sbin/iscsid -d8
```

**Comment by gonzoleeman** [comment]
Yes, logging out should normally work just fine. The device should not have to be deleted first. Just try this same exercise on a non-container. I just tested it on openSUSE Tumbleweed, with a 4.15 kernel, and logging out of a single target does not hang at all.

**Comment by redbaron** [comment]
Thanks, I posted to maillist my current findings: https://groups.google.com/forum/#!topic/open-iscsi/Tc6ERb1QOBg
