### ISSUE TITLE
iscsid: Kernel reported iSCSI connection 9:0 error (1011 - ISCSI_ERR_CONN_FAILED: iSCSI connection failed) state (3)

### ISSUE THREAD

**Issue by marcosvlt** [open-iscsi/open-iscsi#97]
Hello

More info

connection10:0: detected conn error (1011)
connection10:0: ping timeout of 15 secs expired, recv timeout 5, last rx 10236428121, last ping 

I have 3 CentOS 6 connecting to a ISCSI server with Targecli suddenly one of then lost connection and my mounted partition have they filesystem go to read-only.

How i can debug properly? 

Thanks for attention.

**Comment by gonzoleeman** [comment]
Is there a lot of IO going on? It sounds like you might be overwhelming your target?

open-iscsi NOPs are dangerous, in that they can cause a busy connection to be considered disconnected, at which point error handling takes over and makes a total mess of a connection that actually was working but was busy. So disable NOPs for your testing, at least. Or you can make them really long.

After that, you need to enable debugging on your connections to find the issue. You can add the "-dN" flag to iscsid (N is a number -- see the man page). This is for the initiators. On the target, you can monitor the output of the kernel target drivers, and you can enable debugging in the target drivers, as well. (See the target-devel mailing list for information on debugging the kernel target code).

Also, note that some filesystems decide to become read-only when IO errors are detected, IIRC.

**Comment by marcosvlt** [comment]
Hello gonzoleeman 

Thanks for attention.  

> Is there a lot of IO going on?

Sometimes, but when i have tested, i run only a rsync(but with a lot of inodes and aprox 500G total) from 1 computer. 

>  Or you can make them really long. 

I increased the NOPs time. Now i only receive the following message:

Kernel reported iSCSI connection 13:0 error (1019 - ISCSI_ERR_XMIT_FAILED: Transmission of iSCSI packet failed) state (3)

I've run tcpdump and notice some  (Destination unreachable) on iscsi port. But when I ping I have 0 packet loss.  Now I suspect something on the network or firewall.


Unfortunately i'll need to stop testing for a while. I think the issue can be closed. Next i'll test debug on target with more time.

Again thanks for attention.
